<h5>Contactos</h5>

<div class="tabbable">
    <ul class="nav nav-tabs">
    <li class="active"><a href="#tab1" data-toggle="tab">Mis Contactos</a></li>
    <li><a href="#tab2" data-toggle="tab">Mis Solicitudes Pendientes</a></li>
    </ul>
    <div class="tab-content">
    <div class="tab-pane active" id="tab1">
    
    	<table width="100%" align="center">
    				<?php 
						$aut = Zend_Auth::getInstance();
						$objAmigoDao = new Application_Model_AmigoDao();
						$columna = 0;
						$cantColumna = 3;
					?>
					<?php foreach ($this->listaContactos as $usuario){
							if($columna == 0){ 
							   echo "<tr>";
							} 
							echo "<td>";?> 
							<!-- imprimir el objeto -->
								<table align="center">
									<tr>
										<td align="center">
											<table>
												<tr>
													<td>
														<div class="btn-group">
												          <a href="#" class="btn btn-primary"><i class="icon-user icon-white"></i> User</a>
												          <a href="#" data-toggle="dropdown" class="btn btn-primary dropdown-toggle"><span class="caret"></span></a>
												          <ul class="dropdown-menu">
												            <li><a href="#"><i class="icon-pencil"></i> Mensaje </a></li>
												            <li><a href="#" onclick="eliminarContacto(<?php echo $usuario->getId();?>)"><i class="icon-trash"></i> Eliminar </a></li>
												            <li class="divider"></li>
												            <li><a href="#"><i class="i"></i> Muro </a></li>
												          </ul>
												        </div>
													</td>
												</tr>
												<tr>
													<td>
														<div style='width: 100px;'>
		            	 	   								<a class='thumbnail'>
																<img src="<?php echo $this->baseUrl()?>/imagenes/usuarios/<?php echo $usuario->getFoto(); ?>"></img>
															</a>
														</div>
													</td>
													<td valign="top" class="contMini">
														<p><?php echo $usuario->getNombre();?></p>
													</td>
												</tr>
											</table>
										</td>
									</tr>
								</table>						
							<!-- fin de imprimir el objeto -->
							<?php 
							echo "</td>"; 
							$columna++;
							 if($columna == $cantColumna){
								 echo "</tr>";				
								 $columna = 0;
							 }
						 }
						 echo "</tr>";
					?>
				</table>
    
    </div>
    <div class="tab-pane" id="tab2">

    	<table>
    	<?php foreach ($this->listaPendientes as $usuarioPendiente){?>
    				<tr>
    					<td>
    						<div id="divMsjEliminado<?php echo $usuarioPendiente->getId();?>">
    							<?php echo $usuarioPendiente->getNombre();?>
    						</div>
    					</td>
    				</tr>
    				<tr id="rowDos<?php echo $usuarioPendiente->getId();?>" style="display: block;">
    					<td>
    						<div style='width: 100px;'>
								<a class='thumbnail'>
									<img src="<?php echo $this->baseUrl()?>/imagenes/usuarios/<?php echo $usuarioPendiente->getFoto(); ?>"></img>
								</a>
							</div>
    					</td>
    					<td>
							<button href="#" class="btn btn-success" onclick="aceptarContacto(<?php echo $usuarioPendiente->getId();?>)">Aceptar</button>
							<button href="#" class="btn btn-danger" onclick="rechazarContacto(<?php echo $usuarioPendiente->getId();?>)">Rechazar</button>	
    					</td>
    				</tr>
    	<?php } ?>
    	</table>
    
    </div>
    </div>
</div>

<script type="text/javascript">
					
function aceptarContacto(id)
{
	$.ajax(
			{
			async: true,
			type: 'POST',
			url: '<?php echo $this->baseUrl()?>/contacto/aceptar',
			data: 'usuario=' + id,	
			dataTypeString: 'text',
			
			beforeSend: function(data){
                //selectDestino.html('<label>Cargando...</label>');
		    },  
		    success: function(requestData){
						var result = requestData;

						var divMsj = "<div class='alert alert-success'>";
						divMsj = divMsj + "<button class='close' data-dismiss='alert'>×</button>";
						divMsj = divMsj + "<strong>Felicidades !!</strong> Ahora son amigos !!";
						divMsj = divMsj + "</div>";
			    		
			    		document.getElementById("rowDos" + id).style.display = "none";
			    		document.getElementById("divMsjEliminado" + id).innerHTML = divMsj;
			    		 
		    },  
		    error: function(requestData, strError, strTipoError){          
		    }
		    
			});
	
}

function rechazarContacto(id)
{
	$.ajax(
			{
			async: true,
			type: 'POST',
			url: '<?php echo $this->baseUrl()?>/contacto/rechazar',
			data: 'usuario=' + id,	
			dataTypeString: 'text',
			
			beforeSend: function(data){
                //selectDestino.html('<label>Cargando...</label>');
		    },  
		    success: function(requestData){
		    			var result = requestData;

			    		var divMsj = "<div class='alert alert-success'>";
						divMsj = divMsj + "<button class='close' data-dismiss='alert'>×</button>";
						divMsj = divMsj + "<strong>Solicitud Rechazada,</strong> Se ha rechazado la solicitud...";
						divMsj = divMsj + "</div>";
			    		
						document.getElementById("rowDos" + id).style.display = "none";
			    		document.getElementById("divMsjEliminado" + id).innerHTML = divMsj;	
		    },  
		    error: function(requestData, strError, strTipoError){          
		    }
		    
			});
	
}

function eliminarContacto(id)
{
	
	$.ajax(
			{
			async: true,
			type: 'POST',
			url: '<?php echo $this->baseUrl()?>/contacto/rechazar',
			data: 'usuario=' + id,	
			dataTypeString: 'text',
			
			beforeSend: function(data){
                //selectDestino.html('<label>Cargando...</label>');
		    },  
		    success: function(requestData){
		    			var result = requestData;
		    },  
		    error: function(requestData, strError, strTipoError){          
		    }
		    
			});
	
}

</script>

