     <?php
    	$aut = Zend_Auth::getInstance();
    ?>
    <?php
    	$objAlbumDao = new Application_Model_AlbumDao();
    	$objAlbum = $objAlbumDao->obtenerPorId($this->idAlbum);
    ?>
	<br><h1> ÁLBUM: " <?php echo $objAlbum->getNombre();?> " </h1><br>
	
	 <?php 
	 	   if($this->success == "ok")
		   {
				    $msj = "";
					$msj .= "<div class='alert alert-success' id='divFotosCargadas'>";
					$msj .= "<button class='close' data-dismiss='alert'>×</button>";
					$msj .= "<strong><img src='/imagenes/proyecto/ok.png'>&nbsp;&nbsp;</strong> Fotos cargadas correctamente !!";
					$msj .= "</div>";
					echo $msj;	
		    }
	?>
	
	<div id="divMensaje"></div>
	
	<?php if($this->album->getUsuario() == $aut->getIdentity()->usu_id){?>
			<p><a href="#" class="btn" onclick="openModalAgregarFoto()"><img src="/imagenes/proyecto/foto.png">&nbsp;&nbsp;Agregar Fotos</a></p>
	<?php } ?>
   	<br>
    
    <div class="tabbable well span9">
	    <ul class="nav nav-tabs">
		    <li class="active"><a href="#tab1" data-toggle="tab"><img src="/imagenes/proyecto/foto.png">&nbsp;&nbsp;Fotos</a></li>
	    </ul>
	    <div class="tab-content">
		    <div class="tab-pane active" id="tab1">
		    <p class="cont2"><?php echo $objAlbum->getDescripcion();?></p>
		    
		    <?php 
				$columna = 0;
				$cantColumna = 4;
			?>
				<table width="100%" align="center">
					<?php foreach ($this->listaFotos as $foto){
							if($columna == 0){ 
							   echo "<tr>";
							} 
							echo "<td>";?> 
							<!-- imprimir el objeto -->
								<table align="center" id="rowUno<?php echo $foto->getId();?>">
									<tr>
										<td align="center">
											<a href="#"><img src="<?php echo $this->baseUrl()?>/imagenes/fotos/icono/<?php echo $foto->getFoto(); ?>" onclick="openModalCarrucel('<?php echo $foto->getFoto(); ?>')"></img></a>
										</td>
									</tr>
									<tr>
										<td align="left">
											<?php if(trim($this->album->getPortada()) != trim($foto->getFoto())){?>
												<a href="#" onclick="openEliminarFoto('<?php echo $foto->getId();?>')"><img src="/imagenes/proyecto/cruz.png" width="20px;">&nbsp;&nbsp;</a>&nbsp;Eliminar
											<?php }else{ ?>
												Portada
											<?php }?>
										</td>
									</tr>
								</table>						
							<!-- fin de imprimir el objeto -->
							<?php 
							echo "</td>"; 
							$columna++;
							 if($columna == $cantColumna){
								 echo "</tr>";				
								 $columna = 0;
							 }
						 }
						 echo "</tr>";
					?>
				</table>
		    
		    </div>
	    </div>
    </div>
    
<div class="modal hide" id="myModalCarrucel" style="width: 700px;">
    <div class="modal-header">
    <button class="close" data-dismiss="modal" onclick="closeModalCarrucel();">×</button>
    <h2><img src="/imagenes/proyecto/foto.png">&nbsp;&nbsp;&nbsp;Fotos del álbum</h2>
    </div>
    <div class="modal-body">
    	
    	<div id="myCarousel" class="carousel">
		    <!-- Carousel items -->
		    
		    <div id="divCarouselInner" class="carousel-inner" align="center">
		    </div>
		    
		    <!-- Carousel nav -->
			<div style="position:absolute; overflow:hidden; left:0px; top: 0px; width:100%; height:80px;"><a class="carousel-control left" href="#myCarousel" data-slide="prev" style="z-index: 1">&lsaquo;</a></div>
			<div style="position:absolute; overflow:hidden; left:0px; top: 0px; width:100%; height:80px;"><a class="carousel-control right" href="#myCarousel" data-slide="next" style="z-index: 1">&rsaquo;</a></div>
		</div>
    	 
    </div>
    <div class="modal-footer">
    		<input type="button" value="Cerrar" data-dismiss="modal" onClick="closeModalCarrucel()" class="btn btn-danger">
    </div>
</div>	

<?php 
	$flag = "modal hide";
	if($this->error == "error")
	{
	    $flag = "modal";
	}else{
	    $flag = "modal hide";
	}
?>
<div class="<?php echo $flag;?>" id="myModalAgregarFoto" style="width: 700px;">
    <div class="modal-header">
    <button class="close" data-dismiss="modal" onclick="closeModalAgregarFoto();">×</button>
    <h2><img src="/imagenes/proyecto/foto.png">&nbsp;&nbsp;Agregar Fotos</h2>
    </div>
    <div class="modal-body">
    
    <div id="divErrores"></div>
    
    <?php 
    	echo $this->form;
    ?>
    	
    </div>
    <div class="modal-footer">
    		<input type="button" value="Agregar" onClick="guardarFotos();" class="btn btn-success">
    		<input type="button" value="Cerrar" data-dismiss="modal" onClick="closeModalAgregarFoto()" class="btn btn-danger">
    </div>
</div>	

<div class="modal hide" id="myModalEliminarFoto" style="width: 700px;">
    <div class="modal-header">
    <button class="close" data-dismiss="modal" onclick="closeEliminarFoto();">×</button>
    <h2><img src="/imagenes/proyecto/papelera.png">&nbsp;&nbsp;&nbsp;Eliminar Foto</h2>
    </div>
    <div class="modal-body">
    	¿Estás seguro de eliminar la foto?
    	<input type="hidden" id="idFotoAEliminar" name="idFotoAEliminar">
    </div>
    <div class="modal-footer">
    		<input type="button" value="Si, eliminar" data-dismiss="modal" onClick="eliminarFoto();" class="btn btn-success"> 
    		<input type="button" value="Cerrar" data-dismiss="modal" onClick="closeEliminarFoto()" class="btn btn-danger">
    </div>
</div>	
    
<script type="text/javascript">
    
    function openModalCarrucel(foto)
	{
	//	var htmlGaleria = "<div class='active item'><img src='/imagenes/fotos/"+foto+"'></div>";
    	var htmlGaleria = "";
    	<?php foreach ($this->listaFotos as $foto){ ?>

    			if("<?php echo $foto->getFoto();?>" == foto){
	    			htmlGaleria = htmlGaleria + "<div class='active item'><img src='/imagenes/fotos/<?php echo $foto->getFoto();?>'>";
    			}else{
    				htmlGaleria = htmlGaleria + "<div class='item'><img src='/imagenes/fotos/<?php echo $foto->getFoto();?>'>";
    			}

    			htmlGaleria = htmlGaleria + "<div class='cont2'><?php echo $foto->getNombre();?></div>";
	    		htmlGaleria = htmlGaleria + "<br> Ingresa un comentario:<br>";   
	    		htmlGaleria = htmlGaleria + "<textarea rows='2' placeholder='Comenta algo aquí...' id='txtComentario<?php echo $foto->getId();?>' class='span4' onkeypress='ValidarCaracteres(this, 249)'></textarea>&nbsp;&nbsp;";
	    		htmlGaleria = htmlGaleria + "<input type='button' id='btnComentar<?php echo $foto->getId();?>' onclick='generarComentario(<?php echo $foto->getId();?>)' class='btn btn-success' value='Comentar'>";
	    		htmlGaleria = htmlGaleria + "<div class='cont' id='divComennt<?php echo $foto->getId();?>'></div>";
	    		htmlGaleria = htmlGaleria + "</div>";
				
	    		comentariosFotos(<?php echo $foto->getId();?>);
		    	
    	<?php } ?>
    	
    	document.getElementById("divCarouselInner").innerHTML = htmlGaleria;
		$('#myModalCarrucel').modal("show");
			
	}

    $('.carousel').carousel({
        interval: 999999999
	})

	function generarComentario(id){

		var texto = document.getElementById("txtComentario"+id).value;

		if(trim(texto) == "")
		{
			return;
		}

		$.ajax(
				{
				async: true,
				type: 'POST',
				url: '<?php echo $this->baseUrl()?>/album/guardar-comentario',
				data: 'texto='+texto+'&id='+id,	//ID FOTO
				dataTypeString: 'text',
				
				beforeSend: function(data){
					//loader
			    },  
			    success: function(requestData){

			    	result  = requestData;
			    	document.getElementById("divComennt"+id).innerHTML = "";
			    	document.getElementById("divComennt"+id).innerHTML = result;
			    	document.getElementById("txtComentario"+id).value = "";
			    },  
			    error: function(requestData, strError, strTipoError){          
			    }
			    
				});
			
		}

	function comentariosFotos(id){

		$.ajax(
				{
				async: true,
				type: 'POST',
				url: '<?php echo $this->baseUrl()?>/album/obtener-comentarios-foto',
				data: 'id='+id,	//ID FOTO
				dataTypeString: 'text',
				
				beforeSend: function(data){
					//loader
			    },  
			    success: function(requestData){

			    	result  = requestData;
			    	document.getElementById("divComennt"+id).innerHTML = result; 
				    
			    },  
			    error: function(requestData, strError, strTipoError){          
			    }
			    
				});
			
		}

    function closeModalCarrucel()
	{
		$('#myModalCarrucel').modal();	
	}

    function openModalAgregarFoto()
	{
		$('#myModalAgregarFoto').modal("show");	
	}

	function closeModalAgregarFoto()
	{
		$('#myModalAgregarFoto').modal();	
	}

	function openEliminarFoto(id)
	{
		document.getElementById("idFotoAEliminar").value = id;
		$('#myModalEliminarFoto').modal("show");	
	}

	function closeEliminarFoto()
	{
		$('#myModalEliminarFoto').modal();	
	}

	function guardarFotos()
	{
		  if(trim(document.getElementById("fileFoto1").value) == "" && trim(document.getElementById("fileFoto2").value) == "" && trim(document.getElementById("fileFoto3").value) == "" && trim(document.getElementById("fileFote4").value) == "" && trim(document.getElementById("fileFoto5").value) == "")
		  {
			  document.getElementById("divErrores").innerHTML = "<ul type = square><li><font color='red'>Debes subir al menos una foto.</font></ul>";
		  }else{
			  document.getElementById("formFotos").submit();
		  }
	}

	function eliminarFoto(){

		var idFoto = document.getElementById("idFotoAEliminar").value;
		
		$.ajax(
				{
				async: true,
				type: 'POST',
				url: '<?php echo $this->baseUrl()?>/album/eliminar-foto',
				data: 'idFoto='+idFoto,	
				dataTypeString: 'text',
				
				beforeSend: function(data){
					//loader
			    },  
			    success: function(requestData){
		               		if(requestData == "ok")
		               		{	
		               			document.getElementById("rowUno"+idFoto).style.display = "none";

		               			var divMsj= "<div class='alert alert-success'>";
		               			divMsj = divMsj + "<button class='close' data-dismiss='alert'>×</button>";
		               			divMsj = divMsj + "<strong><img src='/imagenes/proyecto/ok.png'>&nbsp;&nbsp;</strong> Foto eliminada correctamente !!";
		               			divMsj = divMsj + "</div>";

		               			document.getElementById("divMensaje").innerHTML = divMsj;
		               			document.getElementById("divFotosCargadas").innerHTML = "";
		               		} 
			    },  
			    error: function(requestData, strError, strTipoError){          
			    }
			    
				});
			
		}


	
	
</script>
    