    <?php
    	$objAlbumDao = new Application_Model_AlbumDao();
    	$objAlbum = $objAlbumDao->obtenerPorId($this->idAlbum);
    ?>
	<br><h1> ÁLBUM: " <?php echo $objAlbum->getNombre();?> " </h1><br>
	
	 <?php 
	 	   if($this->success == "ok")
		   {
				    $msj = "";
					$msj .= "<div class='alert alert-success' id='divFotosCargadas'>";
					$msj .= "<button class='close' data-dismiss='alert'>×</button>";
					$msj .= "<strong>Éxito!</strong> Fotos cargadas correctamente !!";
					$msj .= "</div>";
					echo $msj;	
		    }
	?>
	
	<div id="divMensaje"></div>
	
	<p><a href="#" class="btn" onclick="openModalAgregarFoto()"><i class="icon-camera"></i>&nbsp;&nbsp;Agregar Fotos</a></p>
   	<br>
    
    <div class="tabbable hero-unit well">
	    <ul class="nav nav-tabs">
		    <li class="active"><a href="#tab1" data-toggle="tab"><i class="icon-camera"></i>&nbsp;&nbsp;Fotos</a></li>
	    </ul>
	    <div class="tab-content">
		    <div class="tab-pane active" id="tab1">
		    <p class="cont2"><?php echo $objAlbum->getDescripcion();?></p>
		    
		    <?php 
				$columna = 0;
				$cantColumna = 4;
			?>
				<table width="100%" align="center">
					<?php foreach ($this->listaFotos as $foto){
							if($columna == 0){ 
							   echo "<tr>";
							} 
							echo "<td>";?> 
							<!-- imprimir el objeto -->
								<table align="center" id="rowUno<?php echo $foto->getId();?>">
									<tr>
										<td align="center">
											<a href="#"><img src="<?php echo $this->baseUrl()?>/imagenes/fotos/icono/<?php echo $foto->getFoto(); ?>" width="160px;" height="100px;" onclick="openModalCarrucel('<?php echo $foto->getFoto(); ?>')"></img></a>
										</td>
									</tr>
									<tr>
										<td align="left">
											<a href="#" onclick="openEliminarFoto('<?php echo $foto->getId();?>')"><i class="icon-remove"></i></a>&nbsp;Eliminar
										</td>
									</tr>
								</table>						
							<!-- fin de imprimir el objeto -->
							<?php 
							echo "</td>"; 
							$columna++;
							 if($columna == $cantColumna){
								 echo "</tr>";				
								 $columna = 0;
							 }
						 }
						 echo "</tr>";
					?>
				</table>
		    
		    </div>
	    </div>
    </div>
    
<div class="modal hide" id="myModalCarrucel" style="width: 700px;">
    <div class="modal-header">
    <button class="close" data-dismiss="modal" onclick="closeModalCarrucel();">×</button>
    <h2><img src="/imagenes/proyecto/add.png">&nbsp;&nbsp;&nbsp;Fotos del álbum</h2>
    </div>
    <div class="modal-body">
    	
    	<div id="myCarousel" class="carousel">
		    <!-- Carousel items -->
		    
		    <div id="divCarouselInner" class="carousel-inner" align="center">
		    </div>
		    
		    <!-- Carousel nav -->
		    <a class="carousel-control left" href="#myCarousel" data-slide="prev">&lsaquo;</a>
		    <a class="carousel-control right" href="#myCarousel" data-slide="next">&rsaquo;</a>
		    
		</div>
    	
    </div>
    <div class="modal-footer">
    		<input type="button" value="Cerrar" data-dismiss="modal" onClick="closeModalCarrucel()" class="btn btn-danger">
    </div>
</div>	

<?php 
	$flag = "modal hide";
	if($this->error == "error")
	{
	    $flag = "modal";
	}else{
	    $flag = "modal hide";
	}
?>
<div class="<?php echo $flag;?>" id="myModalAgregarFoto" style="width: 700px;">
    <div class="modal-header">
    <button class="close" data-dismiss="modal" onclick="closeModalAgregarFoto();">×</button>
    <h2><img src="/imagenes/proyecto/add.png">&nbsp;&nbsp;&nbsp;Agregar Fotos</h2>
    </div>
    <div class="modal-body">
    
    <div id="divErrores"></div>
    
    <?php 
    	echo $this->form;
    ?>
    	
    </div>
    <div class="modal-footer">
    		<input type="button" value="Agregar" onClick="guardarFotos();" class="btn btn-success">
    		<input type="button" value="Cerrar" data-dismiss="modal" onClick="closeModalAgregarFoto()" class="btn btn-danger">
    </div>
</div>	

<div class="modal hide" id="myModalEliminarFoto" style="width: 700px;">
    <div class="modal-header">
    <button class="close" data-dismiss="modal" onclick="closeEliminarFoto();">×</button>
    <h2><img src="/imagenes/proyecto/add.png">&nbsp;&nbsp;&nbsp;Eliminar Foto</h2>
    </div>
    <div class="modal-body">
    	¿Estás seguro de eliminar la foto?
    	<input type="hidden" id="idFotoAEliminar" name="idFotoAEliminar">
    </div>
    <div class="modal-footer">
    		<input type="button" value="Si, eliminar" data-dismiss="modal" onClick="eliminarFoto();" class="btn btn-success">
    		<input type="button" value="Cerrar" data-dismiss="modal" onClick="closeEliminarFoto()" class="btn btn-danger">
    </div>
</div>	
    
<script type="text/javascript">
    
    function openModalCarrucel(foto)
	{
		var htmlGaleria = "<div class='active item'><img src='/imagenes/fotos/"+foto+"'></div>";
    	
    	<?php foreach ($this->listaFotos as $foto){ ?>
		    	htmlGaleria = htmlGaleria + "<div class='item'><img src='/imagenes/fotos/<?php echo $foto->getFoto();?>'></div>";
    	<?php } ?>

    	document.getElementById("divCarouselInner").innerHTML = htmlGaleria;
		$('#myModalCarrucel').modal("show");	
	}

    function closeModalCarrucel()
	{
		$('#myModalCarrucel').modal();	
	}

    function openModalAgregarFoto()
	{
		$('#myModalAgregarFoto').modal("show");	
	}

	function closeModalAgregarFoto()
	{
		$('#myModalAgregarFoto').modal();	
	}

	function openEliminarFoto(id)
	{
		document.getElementById("idFotoAEliminar").value = id;
		$('#myModalEliminarFoto').modal("show");	
	}

	function closeEliminarFoto()
	{
		$('#myModalEliminarFoto').modal();	
	}

	function guardarFotos()
	{
		  if(trim(document.getElementById("fileFoto1").value) == "" && trim(document.getElementById("fileFoto2").value) == "" && trim(document.getElementById("fileFoto3").value) == "" && trim(document.getElementById("fileFote4").value) == "" && trim(document.getElementById("fileFoto5").value) == "")
		  {
			  document.getElementById("divErrores").innerHTML = "<ul type = square><li><font color='red'>Debes subir al menos una foto.</font></ul>";
		  }else{
			  document.getElementById("formFotos").submit();
		  }
	}

	function eliminarFoto(){

		var idFoto = document.getElementById("idFotoAEliminar").value;
		
		$.ajax(
				{
				async: true,
				type: 'POST',
				url: '<?php echo $this->baseUrl()?>/album/eliminar-foto',
				data: 'idFoto='+idFoto,	
				dataTypeString: 'text',
				
				beforeSend: function(data){
					//loader
			    },  
			    success: function(requestData){
		               		if(requestData == "ok")
		               		{	
		               			document.getElementById("rowUno"+idFoto).style.display = "none";

		               			var divMsj= "<div class='alert alert-success'>";
		               			divMsj = divMsj + "<button class='close' data-dismiss='alert'>×</button>";
		               			divMsj = divMsj + "<strong>Éxito!</strong> Foto eliminada correctamente !!";
		               			divMsj = divMsj + "</div>";

		               			document.getElementById("divMensaje").innerHTML = divMsj;
		               			document.getElementById("divFotosCargadas").innerHTML = "";
		               		} 
			    },  
			    error: function(requestData, strError, strTipoError){          
			    }
			    
				});
			
		}
	
</script>
    