<br /><br />
<div id="view-content">
	
	<div id="divLogin" align="center">
		<form id="frmLogin" name="frmLogin" method="post" action="login/acceso">
			<table>
				<caption><b>Login</b></caption>
				<tr>
					<td>Usuario: </td><td><input type="text" id="txtUsuario" name="txtUsuario" size="12" maxlength="10" value="111-1"/></td>
				</tr>
				<tr>
					<td>Contraseña: </td><td><input type="text" id="txtPassword" name="txtPassword" size="31" maxlength="30" value="123"/></td>
				</tr>
				<tr>
					<td colspan="2" align="center">
						<input type="button" value="Entrar" class="btn btn-success" onclick="validarFormularioLogin()">
					</td>
				</tr>
			</table>
		</form>
	</div>	
	
	<!-- ESTO DEBERIA ESTAR EN EL LAYOUT PARA QUE SE PUEDA UTILIZAR SIEMPRE QUE SE DESEE Y NO TENER SIEMPRE EN TODAS LAS VIEW'S -->
	<div class="modal hide" id="myModalTerminos">
	    <div class="modal-header">
		    <button class="close" data-dismiss="modal">×</button>
		    <h3>Términos y Condiciones</h3>
	    </div>
			<b>Información que recibimos sobre ti</b><br>
			Conoce el tipo de información que recibimos sobre ti.<br>
			<br>
			<b>Información pública</b><br>
			Infórmate de qué información es siempre pública y por qué.<br>
			<br>
			<b>Nombres de usuario e identificadores de usuario</b><br>
			Averigua a qué información sobre ti dan acceso tu nombre de usuario y tu identificador de usuario.<br>
			<br>
			<b>Cómo utilizamos la información que recibimos</b><br>
			Lee esta sección para entender los principios sobre los que basamos el uso de tu información.<br>
			<br>
			<b>Eliminación y desactivación de tu cuenta</b><br>
			Comprende en qué se diferencian la desactivación y la eliminación de tu cuenta.			    
	    <div class="modal-footer">
		    <a href="#" class="btn btn-success" data-dismiss="modal" onclick="grabarAceptacion()">Aceptar Condiciones</a>
		    <a href="#" class="btn btn-danger" data-dismiss="modal">Cerrar</a>
	    </div>
    </div>
	
</div>

<script type="text/javascript">	

	function validarFormularioLogin()
	{		
		if (document.getElementById("txtUsuario").value == "" || document.getElementById("txtPassword").value == "")
		{
			$('#myModal').modal('show');
			return;
		}

		
		
		/*$acepta = 0;
		if($acepta == 0)
		{			
			$('#myModalTerminos').modal('show');
			return;
		}*/

		grabarAceptacion("claudio");

		//document.getElementById("frmLogin").submit();
	}

	/*
	function validarAceptacionDeTerminos()
	{		
		var ajax = nuevoAjax();

		var usuario = document.getElementById("txtUsuario").value;
		
		ajax.open("POST", "login/validar-aceptacion-condiciones", true);
		ajax.setRequestHeader("Content-Type", "application/x-www-form-urlencoded");
		ajax.send("txtUsuario="+usuario);

		ajax.onreadystatechange=function()
		{
			if (ajax.readyState == 4)
			{			
				alert(ajax.responseText);
			}
		}
	}*/

	
/*
	function grabarAceptacion(usuario)
	{		
		var ajax = nuevoAjax();
		
		ajax.open("POST", "login/validarAceptacionCondiciones", true);
		ajax.setRequestHeader("Content-Type", "application/x-www-form-urlencoded");
		ajax.send("txtUsuario="+usuario);

		ajax.onreadystatechange=function()
		{
			if (ajax.readyState == 4)
			{			
				if(ajax.responseText > 0)
				{
					alert("aceptacion de terminos y condiciones aceptadas correctamente...");
				}else{
					alert("no se pudo actualizar los terminos y condiciones");	
				}
			}
		}
	}
*/
	function grabarAceptacion(usuario){

		if(usuario != '') {
			//selectDestino = $('#cont_obra');
				$.ajax(
						{
						async: true,
						type: 'POST',
						url: '<?php echo $this->baseUrl()?>/login/validar-aceptacion-condiciones',
						data: 'txtUsuario=' + usuario,	
						dataTypeString: 'text',
						
						beforeSend: function(data){
			                //selectDestino.html('<label>Cargando...</label>');
			                
					    },  
					    success: function(requestData){  
					               //selectDestino.html(requestData);
					    	alert(requestData);
					              
					    },  
					    error: function(requestData, strError, strTipoError){          
					    }
					    
						});
		}
			
	}
	
	</script>	