 <?php 
 $aut = Zend_Auth::getInstance();
 ?>
 
 <a href="#" onclick="openModalNuevoMensaje()">Nuevo Mensaje</a>
 
 
 
 
 

 
 <div class="modal hide" id="myModalNuevoMensaje" style="width: 700px;">
    <div class="modal-header">
    <button class="close" onclick="closeModalNuevoMensaje()" data-dismiss="modal">×</button>
    		<h3>Crear mensaje</h3>
    </div>
    <div class="modal-body">
 		<form action="/mensajes/index/" method="post" enctype="<?php echo $this->form->getEnctype(); ?>">
			<?php
                
            	$objAmigoDao = new Application_Model_AmigoDao(); 
				
			
			
                $datSource = "[";
                
                $listaUsuarios = $objAmigoDao->obtenerTodosUsuariosPorUsuarioId($aut->getIdentity()->usu_id);
                #$listaUsuarios = $objAmigoDao->obtenerTodosPorNombre($aut->getIdentity()->usu_id);
                echo json_encode($listaUsuarios);
                
                $i = 1;
                foreach ($listaUsuarios as $item)
                {
                	if($item->getNombre() !="ADMINISTRADOR")
                	{
                		$datSource .= "&quot;".$item->getNombre()."&quot;";
                		 
                		if(count($listaUsuarios) != $i){
                			$datSource .= ",";
                		}
                	}
                	$i++;
                }
                $datSource .= "]";
                
                #echo $datSource;
			
				echo $this->form->txtPara;
				echo $this->form->txtTextoMensaje;	
				echo $this->form->enviar;
             ?>
        </form>
    </div>
</div>
 
 <script type="text/javascript">
	function openModalNuevoMensaje()
	{
		$('#myModalNuevoMensaje').modal("show");	
	}

	function closeModalNuevoMensaje()
	{
		$('#myModalNuevoMensaje').modal();	
	}

 
 </script>