 <?php 
 $aut = Zend_Auth::getInstance();
 ?>
 
 <a href="#" onclick="openModalNuevoMensaje()">Nuevo Mensaje</a>
 
<div class="tabbable span9">
    <ul class="nav nav-tabs">
    	<li><a href="#misMensajes" data-toggle="tab">Mis Mensajes</a></li>
    </ul>
    <div class="tab-content">
    	<div class="tab-pane active" id="misMensajes">
    	<table>
    	<?php
    		echo $this->listaGrupoUsuario;
    		foreach ($this->listaUsuarios as $item)
		    {
		?>
			<tr id="rowUno<?php echo $item->getId();?>" style="display: block;">
				<td colspan=2>
					<?php echo $item->getNombre();?>
				</td>			
			</tr>
			<tr id="rowDosInvitacion<?php echo $item->getId();?>" style="display: block;">
				<td>
					<div style='width: 80px;'>
						<a class='thumbnail'>
							<img src="/imagenes/usuarios/<?php echo $item->getFoto();?>" >
						</a>
					</div>
				</td>
			<td>
				<a class="btn btn-info" href="<?php echo $this->url(array('controller'=>'mensajes', 'action'=>'ver', 'id'=>$item->getId())); ?>"> Ver mensaje </a>
			</td>	
    	<?php }?>
    	</table>
    	</div>
    </div>
</div>
 
 <div class="modal hide" id="myModalNuevoMensaje" style="width: 700px;">
    <div class="modal-header">
    	<button class="close" onclick="closeModalNuevoMensaje()" data-dismiss="modal">×</button>
    	<h3>Crear mensaje</h3>
    </div>
    <div class="modal-body">
 		<form action="/mensajes/index/" method="post" enctype="<?php echo $this->form->getEnctype(); ?>">
			<?php
            	echo $this->form->txtPara;
				echo $this->form->txtTextoMensaje;	
				echo $this->form->enviar;
             ?>
        </form>
    </div>
</div>
 
 <script type="text/javascript">
	function openModalNuevoMensaje()
	{
		$('#myModalNuevoMensaje').modal("show");	
	}

	function closeModalNuevoMensaje()
	{
		$('#myModalNuevoMensaje').modal();	
	}

 
 </script>