<?php 
	$objUsuario = new Application_Model_UsuarioDao();
	$aut = Zend_Auth::getInstance();
?>

<br><h1>CONVERSACIÓN</h1><br>

Participantes:<br>
<b><font color='green'><img src="/imagenes/proyecto/notificacion2.png">&nbsp;<?php echo $objUsuario->obtenerPorId($aut->getIdentity()->usu_id)->getNombre(); ?></font></b><br> 
<b><font color='green'><img src="/imagenes/proyecto/notificacion2.png">&nbsp;<?php echo $objUsuario->obtenerPorId($this->id)->getNombre();?></font></b>

<hr>
<table class="span6">
		<?php 
		foreach ($this->listamensajes as $mensaje)
		{ ?>
		<tr>
			<td rowspan="2" valign="top">
				<img src="/imagenes/usuarios/icono/<?php echo $objUsuario->obtenerPorId($mensaje->getDe())->getFoto();?>">
			</td>
			<td valign="top">
				&nbsp;&nbsp;<b><font color='green'><?php echo $objUsuario->obtenerPorId($mensaje->getDe())->getNombre();?></font></b>
			</td>
			<td valign="top" rowspan="2">
				<?php 
		    		$objPublicacionDao = new Application_Model_PublicacionDao();
		    		echo $objPublicacionDao->calcularTiempoTranscurrido($mensaje->getFecha());
		    		$objPublicacionDao = null;
		    	?>
			</td>
		</tr>
		<tr>
			<td valign="top">	
				<div class="cont4">
		  			<?php echo $mensaje->getTexto();?>
		  		</div></td>
			<td>
			</td>
			<td></td>
		</tr>
		<?php } ?>
</table>

			<div class="pagination-centered">
				<?php echo $this->listamensajes;?>
			</div>

<br>
<table> 	
  	<tr>
  		<td>
  			<form method="post" action="<?php echo $this->url(array('controller'=>'mensajes', 'action'=>'ver', 'id'=>$this->id)); ?>">
			<?php
				echo $this->form->txtTextoResponder;	
				echo $this->form->enviar;
             ?>
        </form>
  		</td>
  	</tr>
</table>