<?php
$objIntegracion = new Application_Model_Integracion();
$objIntegracionDao = new Application_Model_IntegracionDao();
$aut = Zend_Auth::getInstance();

	//session aut
	$aut = Zend_Auth::getInstance();
	//listas
	$listaAmigos = new SplObjectStorage();
	//objetos
	$objAmigoDao = new Application_Model_AmigoDao();
	$objUsuarioDao = new Application_Model_UsuarioDao();
	$objEmocionDao = new Application_Model_EmocionDao();
	
	//obtener amigos del contacto
	$listaContactos = $objAmigoDao->obtenerCantidadContactosPorUsuarioId($aut->getIdentity()->usu_id,5);
	
	 if(count($listaContactos) > 0){ 
		 foreach ($listaContactos as $contacto){
			  $listaAmigos->attach($objUsuarioDao->obtenerPorId($contacto->getAmigoUsuarioId()));
		 }
	 }
?>


<div style="left: 0px; top:40px; width:200px; height:3000px;">
         <a class="thumbnail" href="#">
	       	<img alt="" src="<?php echo $this->baseUrl()?>/imagenes/usuarios/<?php echo $objUsuarioDao->obtenerPorId($aut->getIdentity()->usu_id)->getFoto();?>"></a>
        <ul>
	        <li class="span3">
	        	<h5><?php echo $objUsuarioDao->obtenerPorId($aut->getIdentity()->usu_id)->getNombre();?></h5>
				<p>Nacido: <?php echo substr($objUsuarioDao->obtenerPorId($aut->getIdentity()->usu_id)->getFechaNacimiento(),0,10);?></p>
				<p><?php echo $aut->getIdentity()->perfil_ciisa;?></p>
			</li>
		</ul>
        
        <ul class="nav nav-list">
	        <li class="span3">
					<h5>Mensajes</h5>
					<p> Recibidos </p>
					<p> Enviados </p>
			</li>
			<li class="span3">
					<h5>Contactos</h5>
					<p> Solicitudes</p>
							
					<?php foreach ($listaAmigos as $amigo){ ?>
						  <div style="width: 70px;">
				          	<a class="thumbnail" href="#">
				            	<img alt="" 
				            	 <?php $foto = $objEmocionDao->obtenerPorId($amigo->getEmocionId())->getFoto();
				            	 	   $nombre = $amigo->getNombre();
				            	 	   $srcEmocion = $this->baseUrl()."/imagenes/minicaras/".$foto;	
				            	 	   $imgEmocion = "<table><tr><td>$nombre</td><td><div style='width: 60px;'>";
				            	 	   $imgEmocion = $imgEmocion . "<a class='thumbnail'>";
				            	 	   $imgEmocion = $imgEmocion . "<img src='$srcEmocion'>";
				            	 	   $imgEmocion = $imgEmocion . "</a>";
				            	 	   $imgEmocion = $imgEmocion . "</div></td</tr></table>";
				            	 ?>
				            	 src="<?php echo $this->baseUrl()?>/imagenes/usuarios/<?php echo $amigo->getFoto()?>"
				            	 data-content="<?php echo $amigo->getCorreo();?>"				            	 
				            	 id="contacto<?php echo $amigo->getId();?>" 
				            	 data-original-title="<?php echo $imgEmocion;?>" 
				            	 onMouseOver="popover(<?php echo $amigo->getId();?>)">
				          	</a>
				          </div>
	 				<?php } ?>
			</li>
			<li class="span3">
					<h5>Álbumes</h5>
					<p> + Crear</p>
			</li>
			<li class="span3">
					<h5>Grupos</h5>
					<p> + Crear</p>
			</li>
			<li class="span3">
					<h5>Eventos</h5>
					<p> + Crear</p>
			</li>
			<li class="span3">
					<h5>Bolsa Ciisa</h5>
					<p> + Crear</p>
			</li>
		</ul>

<script type="text/javascript">
	function popover(id)
	{
		$('#contacto' + id).popover('show');	
	}
</script>
