<?php
	$objIntegracion = new Application_Model_Integracion();
	$objIntegracionDao = new Application_Model_IntegracionDao();
	$aut = Zend_Auth::getInstance();

	//session aut
	$aut = Zend_Auth::getInstance();
	//listas
	$listaAmigos = new SplObjectStorage();
	//objetos
	$objAmigoDao = new Application_Model_AmigoDao();
	$objUsuarioDao = new Application_Model_UsuarioDao();
	$objEmocionDao = new Application_Model_EmocionDao();
	
	//obtener amigos del contacto
	$listaContactos = $objAmigoDao->obtenerCantidadContactosPorUsuarioId($aut->getIdentity()->usu_id,5);
	
	 if(count($listaContactos) > 0){ 
		 foreach ($listaContactos as $contacto){
			  $listaAmigos->attach($objUsuarioDao->obtenerPorId($contacto->getAmigoUsuarioId()));
		 }
	 }
?>

<div class="span3 wellLateralIzq">

		<a class="thumbnail" href="#">
	       	<img alt="" src="<?php echo $this->baseUrl()?>/imagenes/usuarios/<?php echo $objUsuarioDao->obtenerPorId($aut->getIdentity()->usu_id)->getFoto();?>">
	    </a>
        <ul>
        	<h5><?php echo $objUsuarioDao->obtenerPorId($aut->getIdentity()->usu_id)->getNombre();?></h5>
				<p><img src="/imagenes/proyecto/torta.png" width="15px;">&nbsp;&nbsp;
					<?php
						$utilidad = new Application_Model_Utilidad();
						echo $utilidad->girarFecha($objUsuarioDao->obtenerPorId($aut->getIdentity()->usu_id)->getFechaNacimiento());
						$utilidad = null;
					?>
				</p>
				<p>
					<?php 
						$objPerfilRedSocialDao = new Application_Model_PerfilRedSocialDao();
						echo $objPerfilRedSocialDao->obtenerPorUsuarioId($aut->getIdentity()->usu_id)->getNombre();
						$objPerfilRedSocialDao = null;
					?>
				</p>
		</ul>
        
		<img src="/imagenes/proyecto/msj.png">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<a href="/mensajes" style="color: #000;">Mensajes</a><br><br>
		<img src="/imagenes/proyecto/album.png">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<a href="/album/index/id/<?php echo $aut->getIdentity()->usu_id;?>" style="color: #000;">Álbumes</a><br><br>
		<img src="/imagenes/proyecto/calendario.png">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<a href="/evento" style="color: #000;">Eventos</a><br><br>
		<img src="/imagenes/proyecto/group.png">&nbsp;&nbsp;<a href="/grupo" style="color: #000;">Grupos</a><br><br>
		<img src="/imagenes/proyecto/contactos.png">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<a href="/contacto" style="color: #000;">Mis Contactos</a><br><br>
		
 							<?php foreach ($listaAmigos as $amigo){ ?>
							  <div style="width: 70px;">
					          	<a class="thumbnail" href="/muro/muro-contacto/id/<?php echo $amigo->getId();?>">
					            	<img alt="" 
					            	 <?php $foto = $objEmocionDao->obtenerPorId($amigo->getEmocionId())->getFoto();
					            	 	   $nombre = $amigo->getNombre();
					            	 	   $srcEmocion = $this->baseUrl()."/imagenes/minicaras/".$foto;	
					            	 	   $imgEmocion = "<table><tr><td>$nombre</td><td><div style='width: 60px;'>";
					            	 	   $imgEmocion = $imgEmocion . "<a class='thumbnail'>";
					            	 	   $imgEmocion = $imgEmocion . "<img src='$srcEmocion'>";
					            	 	   $imgEmocion = $imgEmocion . "</a>";
					            	 	   $imgEmocion = $imgEmocion . "</div></td</tr></table>";
					            	 ?>
					            	 src="<?php echo $this->baseUrl()?>/imagenes/usuarios/icono/<?php echo $amigo->getFoto()?>"
					            	 data-content="<?php 
					            	 				$objPerfilRedSocialDao = new Application_Model_PerfilRedSocialDao();
					            	 				echo $amigo->getCorreo()." - <b>".$objPerfilRedSocialDao->obtenerPorUsuarioId($amigo->getId())->getNombre()."</b>";
					            	 				$objPerfilRedSocialDao = null;
					            	 				?>"				            	 
					            	 id="contacto<?php echo $amigo->getId();?>" 
					            	 data-original-title="<?php echo $imgEmocion;?>" 
					            	 onMouseOver="popover(<?php echo $amigo->getId();?>)">
						          	</a>
						          </div>
			 				<?php } ?>
</div>

<script type="text/javascript">
	function popover(id)
	{
		$('#contacto' + id).popover('show');	
	}
</script>
