<?php
$objIntegracion = new Application_Model_Integracion();
$objIntegracionDao = new Application_Model_IntegracionDao();
$aut = Zend_Auth::getInstance();

if ($objIntegracionDao->obtenerLlavesIntegracion($aut->getIdentity()->usu_id,3) != null)
{
    define("API_CONSUMER_KEY", "qolg75ipkngf");
    define("API_CONSUMER_SECRET", "LNITIz9Vd9hdw7uW");
    require 'linkedin/helpers.php';
    $oauth = new OAuth(API_CONSUMER_KEY, API_CONSUMER_SECRET);
    $objIntegracion = $objIntegracionDao->obtenerLlavesIntegracion($aut->getIdentity()->usu_id,3);
    $oauth->setToken($objIntegracion->getToken(),$objIntegracion->getSecret());
    $api_url = "http://api.linkedin.com/v1/people/~:(first-name,last-name,headline,picture-url,public-profile-url)";
    $oauth->fetch($api_url, array(), OAUTH_HTTP_METHOD_GET, array('x-li-format' => 'json'));
    $profile = json_decode($oauth->getLastResponse());
}

?>
<?php
	//session aut
	$aut = Zend_Auth::getInstance();
	//listas
	$listaAmigos = new SplObjectStorage();
	//objetos
	$objAmigoDao = new Application_Model_AmigoDao();
	$objUsuarioDao = new Application_Model_UsuarioDao();
	$objEmocionDao = new Application_Model_EmocionDao();
	
	//obtener amigos del contacto
	$listaContactos = $objAmigoDao->obtenerCantidadContactosPorUsuarioId($aut->getIdentity()->usu_id,5);
	
	 if(count($listaContactos) > 0){ 
		 foreach ($listaContactos as $contacto){
			  $listaAmigos->attach($objUsuarioDao->obtenerPorId($contacto->getAmigoUsuarioId()));
		 }
	 }
?>
<div class="span3 well" style="width: 300px; left: 0px; top:40px; width:300px; height:1500px; background-color: #999">
         <a class="thumbnail" href="#">
	       	<img alt="" src="<?php echo $this->baseUrl()?>/imagenes/usuarios/<?php echo $aut->getIdentity()->usu_foto;?>">
         </a>
        <ul>
	        <li class="span3">
	        	<h5><?php echo $aut->getIdentity()->usu_nombre;?></h5>
				<p>Nacido: <?php echo substr($aut->getIdentity()->usu_fecha_nacimiento,0,10); ?></p>
				<p><?php echo $aut->getIdentity()->perfil_ciisa;?></p>
			</li>
		</ul>
        
        <ul class="nav nav-list">
	        <li class="span3">
					<h5>Mensajes</h5>
					<p> Recibidos </p>
					<p> Enviados </p>
			</li>
			<li class="span3">
					<h5>Contactos</h5>
					<p> Solicitudes</p>
							
					<?php foreach ($listaAmigos as $amigo){ ?>
						  <div style="width: 70px;">
				          	<a class="thumbnail" href="#">
				            	<img alt="" 
				            	 <?php $foto = $objEmocionDao->obtenerPorId($amigo->getEmocionId())->getFoto();
				            	 	   $nombre = $amigo->getNombre();
				            	 	   $srcEmocion = $this->baseUrl()."/imagenes/minicaras/".$foto;	
				            	 	   $imgEmocion = "<table><tr><td>$nombre</td><td><div style='width: 60px;'>";
				            	 	   $imgEmocion = $imgEmocion . "<a class='thumbnail'>";
				            	 	   $imgEmocion = $imgEmocion . "<img src='$srcEmocion'>";
				            	 	   $imgEmocion = $imgEmocion . "</a>";
				            	 	   $imgEmocion = $imgEmocion . "</div></td</tr></table>";
				            	 ?>
				            	 src="<?php echo $this->baseUrl()?>/imagenes/usuarios/<?php echo $amigo->getFoto()?>"
				            	 data-content="<?php echo $amigo->getCorreo();?>"				            	 
				            	 id="contacto<?php echo $amigo->getId();?>" 
				            	 data-original-title="<?php echo $imgEmocion;?>" 
				            	 onMouseOver="popover(<?php echo $amigo->getId();?>)">
				          	</a>
				          </div>
	 				<?php } ?>
			</li>
			<li class="span3">
					<h5>Álbumes</h5>
					<p> + Crear</p>
			</li>
			<li class="span3">
					<h5>Grupos</h5>
					<p> + Crear</p>
			</li>
			<li class="span3">
					<h5>Eventos</h5>
					<p> + Crear</p>
			</li>
			<li class="span3">
					<h5>Bolsa Ciisa</h5>
					<p> + Crear</p>
			</li>
		</ul>
		
		
</div>


<?php if ($objIntegracionDao->obtenerLlavesIntegracion($aut->getIdentity()->usu_id,3) != null) {?>
<table>
	<tr>
		<td colspan="2">
			<?php echo $profile->firstName." ".$profile->lastName;?> 
		</td>
	</tr>
	<tr>
		<td colspan="2">
			<?php echo $profile->headline;?>
		</td>
	</tr>
	<tr>
		<td><img src="<?php echo $profile->pictureUrl; ?>"></td>
		<td><a href="<?php echo $profile->publicProfileUrl;?>">Ver Perfil</a></td>
	</tr>

</table>
<?php }?>

<script type="text/javascript">
	function popover(id)
	{
		$('#contacto' + id).popover('show');	
	}	
</script>

