<?php
	require_once 'Twitter/tmhUtilities.php';
	$objIntegracion = new Application_Model_Integracion();
	$objIntegracionDao = new Application_Model_IntegracionDao();
	$aut = Zend_Auth::getInstance();

	//session aut
	$aut = Zend_Auth::getInstance();
	//listas
	$listaAmigos = new SplObjectStorage();
	//objetos
	$objAmigoDao = new Application_Model_AmigoDao();
	$objUsuarioDao = new Application_Model_UsuarioDao();
	$objEmocionDao = new Application_Model_EmocionDao();
	
	//obtener amigos del contacto
	$listaContactos = $objAmigoDao->obtenerCantidadContactosPorUsuarioId($aut->getIdentity()->usu_id,5);
	
	 if(count($listaContactos) > 0){ 
		 foreach ($listaContactos as $contacto){
			  $listaAmigos->attach($objUsuarioDao->obtenerPorId($contacto->getAmigoUsuarioId()));
		 }
	 }
?>
			<?php if ( $aut->getIdentity()->facebookNombre != null) {?>
			<div class="span3 well">
						<table>
						  	 <tr>
						  		<td align="center" colspan="2" class="label label-info" style="width: 200px;"><img src="/imagenes/proyecto/facebook.png">&nbsp;&nbsp; Facebook</td>
						  	</tr>
							<tr>
								<td colspan="2">
									<?php echo $aut->getIdentity()->facebookNombre;?>
								</td>
							</tr>
						  	<tr>
							<td>
								<img src="<?php echo $aut->getIdentity()->facebookFoto; ?>" style="width: 50px;">
							</td>
							<td>
								<a href="<?php echo $aut->getIdentity()->facebookLink;?>" class="btn">Ver Perfil</a>
							</td>
						</tr>
						  
						</table>
			</div> 				
			<?php 
				}
				else
				{    
			?>
				<div class="span3 well">
					<table>
						<tr>
							<td align="center" colspan="2" class="label label-info" style="width: 200px;"><img src="/imagenes/proyecto/facebook.png">&nbsp;&nbsp; Facebook</td>
						</tr>
						<tr>
							<td align="center"><a href="/integracion/facebook/" class="btn btn" >Integrar</a></td>
						</tr>
					</table>
				</div>
			<?php }?>
			
		<?php if ( $aut->getIdentity()->linkedinNombre != null ) {?>
			<div class="span3 well">
			<table>
			  <tr>
			    <td style="width: 200px;" align="center" colspan="2" class="label label-info"><img src="/imagenes/proyecto/linkedin.png">&nbsp;&nbsp;Linked In</td>
			  </tr>
				<tr>
					<td colspan="2">
						<?php echo $aut->getIdentity()->linkedinNombre." ".$aut->getIdentity()->linkedinApellido; ?>
					</td>
				</tr>
				<tr>
					<td colspan="2">
						<?php echo $aut->getIdentity()->linkedinEmpleo;?>
					</td>
				</tr>
				<tr>
					<td>
						<img src="<?php echo $aut->getIdentity()->linkedinFoto; ?>">
					</td>
					<td>
						<a href="<?php echo $aut->getIdentity()->linkedinPerfil;?>" class="btn">Ver Perfil</a>
					</td>
				</tr>
			
			</table>
			</div>
			
			<?php }
				else 
				{    
			?>
				<div class="span3 well">
					<table>
						<tr>
							<td align="center" colspan="2" class="label label-info" style="width: 200px;"><img src="/imagenes/proyecto/linkedin.png">&nbsp;&nbsp; LinkedIn</td>
						</tr>
						<tr>
							<td align="center"><a href="/integracion/linkedin/" class="btn btn" >Integrar</a></td>
						</tr>
					</table>
				</div>
			<?php }?>
			
			<?php if ($aut->getIdentity()->twitterArregloDatos != null)
				{?>
				<div class="span3 well">
				<table>
				   <tr>
			    	<td style="width: 200px;" colspan="2" class="label label-info" align="center">
			    			<img src="/imagenes/proyecto/twitter.png">&nbsp;&nbsp;Twiiter
			    	</td>
			  	   </tr>
				  <tr>
				    <td rowspan="2">
				    	<img src="<?php echo $aut->getIdentity()->twitterArregloDatos->profile_image_url; ?>" style="width: 50px;"> 
				    </td>
				    <td> 
				    	<p>Sigo:<span class="badge badge-info"><?php echo $aut->getIdentity()->twitterArregloDatos->friends_count; ?></span></p>
				    	<p>Me siguen:<span class="badge badge-info"><?php echo $aut->getIdentity()->twitterArregloDatos->followers_count; ?></span></p> 
				    </td>
				  </tr>
				</table>  
				<?php
					
					    $timeline = $aut->getIdentity()->twitterArregloTweet;
						foreach ($timeline as $tweet) :
							$entified_tweet = tmhUtilities::entify_with_options($tweet);
							$is_retweet = isset($tweet['retweeted_status']);
						
							$diff = time() - strtotime($tweet['created_at']);
							if ($diff < 60*60)
								$created_at = 'Hace '.floor($diff/60). ' minutos ';
							elseif ($diff < 60*60*24)
							$created_at = 'Hace '.floor($diff/(60*60)) . ' horas';
							else
								$created_at = date('d M', strtotime($tweet['created_at']));
						
							$permalink  = str_replace(array('%screen_name%','%id%','%created_at%'),
									array(	$tweet['user']['screen_name'],$tweet['id_str'],	$created_at,),
									'%created_at% - <a href="https://twitter.com/%screen_name%/status/%id%">Ir al Tweet</a>');
				
				?>
				
				<table>
					  <tr>
					  	<td style="width: 200px;">
					  		<div class="cont0">
					  			<?php echo $tweet['text'];?>
					  		</div>
					  		<br>
					  		<div>
					  			<?php 
					  		echo $permalink;
					  		if ($is_retweet):
					  			echo " retweet ";
					  		endif;
					  		echo " <br>Via ".$tweet['source']."<br>";
					  		?>
					  		</div>
					  	</td>
					  </tr>
					 <hr></hr>
				       <?php  
					endforeach;
					?>
					</table>
					</div>
					<?php }
					else{
					?>
					<div class="span3 well">
						<table>
							<tr>
								<td align="center" colspan="2" class="label label-info" style="width: 200px;"><img src="/imagenes/proyecto/twitter.png">&nbsp;&nbsp; Twitter</td>
							</tr>
							<tr>
								<td align="center"><a href="/integracion/twitter/" class="btn btn" >Integrar</a></td>
							</tr>
						</table>
				</div>
					<?php }?>
					
<?php 
	$objIntegracionDao = null;
	$listaAmigos = null;
	$objAmigoDao = null;
	$objUsuarioDao = null;
	$objEmocionDao = null;
	$listaContactos = null;
?>

<script type="text/javascript">
	function popover(id)
	{
		$('#contacto' + id).popover('show');	
	}
</script>
