<?php
$objIntegracion = new Application_Model_Integracion();
$objIntegracionDao = new Application_Model_IntegracionDao();
$aut = Zend_Auth::getInstance();

if ($objIntegracionDao->obtenerLlavesIntegracion($aut->getIdentity()->usu_id,2) != null)
{
    require 'Twitter/tmhOAuth.php';
    require 'Twitter/tmhUtilities.php';
    $objIntegracion = $objIntegracionDao->obtenerLlavesIntegracion($aut->getIdentity()->usu_id,2);
    $tmhOAuth = new tmhOAuth(array(
    		'consumer_key'    => '4m5dr19FvCwe534XDQ92fw',
    		'consumer_secret' => 'dobuyMsMLs8kTzSl5YDoYv9O9UZlEN1MBSGBKst9hE',
    		'user_token'      => $objIntegracion->getToken(),
    		'user_secret'     => $objIntegracion->getSecret(),
    ));
    
    $code_datos = $tmhOAuth->request('GET', $tmhOAuth->url('1/account/verify_credentials'));
    
    if ($code_datos == 200) {
    	$datos = json_decode($tmhOAuth->response['response']);
    }

    $code_tweet = $tmhOAuth->request('GET', $tmhOAuth->url('1/statuses/user_timeline'), array(
    		'include_entities' => '1',
    		'include_rts'      => '1',
    		'screen_name'      => $datos->screen_name,
    		'count'            => 5,
    ));
    
}


$objIntegracion = null;
?>
<?php
	//session aut
	$aut = Zend_Auth::getInstance();
	//listas
	$listaAmigos = new SplObjectStorage();
	//objetos
	$objAmigoDao = new Application_Model_AmigoDao();
	$objUsuarioDao = new Application_Model_UsuarioDao();
	$objEmocionDao = new Application_Model_EmocionDao();
	
	//obtener amigos del contacto
	$listaContactos = $objAmigoDao->obtenerCantidadContactosPorUsuarioId($aut->getIdentity()->usu_id,5);
	
	 if(count($listaContactos) > 0){ 
		 foreach ($listaContactos as $contacto){
			  $listaAmigos->attach($objUsuarioDao->obtenerPorId($contacto->getAmigoUsuarioId()));
		 }
	 }
?>

		<?php if ($objIntegracionDao->obtenerLlavesIntegracion($aut->getIdentity()->usu_id,3) != null) {?>
			<div class="span3 well">
			<table>
			  <tr>
			    <td align="center" colspan="2" class="label label-info">Linked In</td>
			  </tr>
				<tr>
					<td colspan="2">
						<?php echo $aut->getIdentity()->linkedinNombre." ".$aut->getIdentity()->linkedinApellido; ?>
					</td>
				</tr>
				<tr>
					<td colspan="2">
						<?php echo $aut->getIdentity()->linkedinEmpleo;?>
					</td>
				</tr>
				<tr>
					<td>
						<img src="<?php echo $aut->getIdentity()->linkedinFoto; ?>">
					</td>
					<td>
						<a href="<?php echo $aut->getIdentity()->linkedinPerfil;?>" class="btn">Ver Perfil</a>
					</td>
				</tr>
			
			</table>
			</div>
			
			<?php }?>
			
			<?php if ($objIntegracionDao->obtenerLlavesIntegracion($aut->getIdentity()->usu_id,2) != null)
				{?>
				<div class="span3 well">
				<table>
				   <tr>
			    	<td style="width: 200px;" colspan="2" class="label label-info">
			    		Twiiter
			    	</td>
			  	   </tr>
				  <tr>
				    <td rowspan="2">
				    	<img src="<?php echo $datos->profile_image_url; ?>"> 
				    </td>
				    <td> 
				    	<p>Sigo:<span class="badge badge-info"><?php echo $datos->friends_count; ?></span></p>
				    	<p>Me siguen:<span class="badge badge-info"><?php echo $datos->followers_count; ?></span></p> 
				    </td>
				  </tr>
				</table>  
				<?php
					if ($code_tweet == 200) {
					    $timeline = json_decode($tmhOAuth->response['response'], true);
						foreach ($timeline as $tweet) :
							$entified_tweet = tmhUtilities::entify_with_options($tweet);
							$is_retweet = isset($tweet['retweeted_status']);
						
							$diff = time() - strtotime($tweet['created_at']);
							if ($diff < 60*60)
								$created_at = 'Hace '.floor($diff/60). ' minutos ';
							elseif ($diff < 60*60*24)
							$created_at = 'Hace '.floor($diff/(60*60)) . ' horas';
							else
								$created_at = date('d M', strtotime($tweet['created_at']));
						
							$permalink  = str_replace(array('%screen_name%','%id%','%created_at%'),
									array(	$tweet['user']['screen_name'],$tweet['id_str'],	$created_at,),
									'<a href="https://twitter.com/%screen_name%/%id%">%created_at%</a>'	);
				
				?>
				
				<table border="2">
					  <tr style="background-color: #81BEF7">
					  	<td style="width: 200px;">
					  		<div class="cont0">
					  			<?php echo $tweet['text'];?>
					  		</div>
					  	</td>
					  </tr>
					  <tr>
					  	<td>
					  		<?php 
					  		echo $permalink;
					  		if ($is_retweet):
					  			echo " retweet ";
					  		endif;
					  		echo " <br>Via ".$tweet['source']."<br>";
					  		?>
					  	</td>
					  </tr>
				       <?php  
					endforeach;
					}
					echo "</table></div>";
					}
					?>
					
	<?php if ($objIntegracionDao->obtenerLlavesIntegracion($aut->getIdentity()->usu_id,1) != null) {?>
	<div class="span3 well">
				<table>
				  	 <tr>
				  		<td colspan="2" class="label label-info" style="width: 200px;">Facebook</td>
				  	</tr>
					<tr>
						<td colspan="2">
							<?php echo $aut->getIdentity()->facebookNombre;?>
						</td>
					</tr>
				  	<tr>
					<td>
						<img src="<?php echo $aut->getIdentity()->facebookFoto; ?>">
					</td>
					<td>
						<a href="<?php echo $aut->getIdentity()->facebookLink;?>" class="btn">Ver Perfil</a>
					</td>
				</tr>
				  
				</table>
	</div> 				
	<?php }?>				
					
<?php 
	$objIntegracionDao = null;
	$listaAmigos = null;
	$objAmigoDao = null;
	$objUsuarioDao = null;
	$objEmocionDao = null;
	$listaContactos = null;
?>

<script type="text/javascript">
	function popover(id)
	{
		$('#contacto' + id).popover('show');	
	}
</script>
