<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
    <title>Red Social IPCIISA</title>
    <meta name="author" content="Red Social IPCIISA">
    
    <script type="text/javascript" src="<?php echo $this->baseUrl()?>/bootstrap/js/jquery-1.7.2.min.js"></script>    
    <link type="text/css" href="<?php echo $this->baseUrl()?>/bootstrap/css/bootstrap.css" rel="stylesheet" />
    <link type="text/css" href="<?php echo $this->baseUrl()?>/bootstrap/css/bootstrap-responsive.css" rel="stylesheet" />	
	<script type="text/javascript" src="<?php echo $this->baseUrl()?>/bootstrap/js/bootstrap.js"></script>
	<script type="text/javascript" src="<?php echo $this->baseUrl()?>/ajax/ajax.js"></script>
	
</head>

<body style="padding-top: 40px;">

<?php
	$aut = Zend_Auth::getInstance();
	$objEmocionDao = new Application_Model_EmocionDao();
?>

<div class="navbar navbar-fixed-top" data-dropdown="dropdown">
	<div class="navbar-inner">
    	<div class="container">
    		<a class="brand" href="#">IPCIISA</a>
    	    <div class="nav-collapse">
    	    
   	    	<?php if($aut->hasIdentity()){ ?>
   	    		<ul class="nav">
			    <li class="active">
			    <a href="#">Muro Central</a>
			    </li>
			    <li><a href="#">Mi Muro</a></li>
			    <li>
			    		<div style="width: 40px;">
	       						<img alt="" src="<?php echo $this->baseUrl()?>/imagenes/caras/<?php echo $objEmocionDao->obtenerPorId($aut->getIdentity()->emo_id)->getFoto();?>">
         				</div>
			    </li>
			    </ul>
   	    	
	    	    <ul class="nav secondary-nav pull-right">
					<li class="dropdown">
		              <a class="dropdown-toggle" href="#" data-toggle="dropdown" >
							    <?php echo $aut->getIdentity()->usu_nombre; ?>
		              	<b class="caret"></b>
		              </a>
		              
		              <ul class="dropdown-menu">
		                <li><a href="#">Mi Perfil</a></li>
		                <li class="divider"></li>
		                <li><a href="/index/logout/">Cerrar Sesion</a></li>
		              </ul>
		            </li>
			    </ul>
			 <?php } ?>
			</div>
    	</div>
	</div>
</div>

<?php if($aut->hasIdentity()){ ?>
	<table>
		<tr valign="top">
			<td>
				
					<?php echo $this->render('lateral_derecha.phtml')?>
			</td>
			<td>
					<?php echo $this->layout()->content ?>
			</td>
		</tr>
	</table>
<?php }else{ ?>
	<?php echo $this->layout()->content ?>
<?php }?>

</body>
</html>
