<!DOCTYPE html>
<html lang="es">
<head>
<meta charset="utf-8">
    <title>Red Social IPCIISA</title>
    <meta name="author" content="Red Social IPCIISA">
    
    <script type="text/javascript" src="<?php echo $this->baseUrl()?>/bootstrap/js/jquery-1.7.2.min.js"></script>    
    <link type="text/css" href="<?php echo $this->baseUrl()?>/bootstrap/css/bootstrap.css" rel="stylesheet" />
    <link type="text/css" href="<?php echo $this->baseUrl()?>/bootstrap/css/bootstrap-responsive.css" rel="stylesheet" />	
	<script type="text/javascript" src="<?php echo $this->baseUrl()?>/bootstrap/js/bootstrap.js"></script>
	<script type="text/javascript" src="<?php echo $this->baseUrl()?>/ajax/ajax.js"></script>
	
	<link type="text/css" href="<?php echo $this->baseUrl()?>/bootstrap/css/cupertino/jquery-ui-1.8.21.custom.css" rel="stylesheet" />
	<script type="text/javascript" src="<?php echo $this->baseUrl()?>/bootstrap/js/jquery-ui-1.8.21.custom.min.js"></script>
	
	<link type="text/css" href="<?php echo $this->baseUrl()?>/bootstrap/css/cupertino/screen.css" rel="stylesheet" />	
		
		<style type="text/css">
			textarea {
				resize:none;
			}

			.cont0 {
				width: 150px;
				word-wrap: break-word; 
			}
			
			.cont {
				width: 600px;
				word-wrap: break-word; 
			}
			
			.cont2 {
				width: 600px;
				word-wrap: break-word; 
			}

		</style> 
		
		
		<script type="text/javascript">
			$(function(){

				// Datepicker
				$('#datepicker').datepicker({
					inline: true,
			         dateFormat: 'dd-mm-yy',
			         changeMonth: true,
			         changeYear: true,
			         dayNamesMin: ['Do','Lu', 'Ma', 'Mi', 'Ju', 'Vi', 'Sa'],
			         dayNames: ['Domingo','Lunes', 'Martes', 'Miercoles', 'Jueves', 'Viernes', 'Sabado'],
			         duration: 'fast',
			         monthNames: ['Enero','Febrero','Marzo','Abril','Mayo','Junio','Julio','Agosto','Septiembre','Octubre','Noviembre','Diciembre'],
			         monthNamesShort: ['Enero','Febrero','Marzo','Abril','Mayo','Junio','Julio','Agosto','Septiembre','Octubre','Noviembre','Diciembre'], 
			         firstDay: 1	
				});

			});
		</script>
		
		<script type="text/javascript">
			function soloLetras(e) { // 1
			    tecla = (document.all) ? e.keyCode : e.which; // 2
			    if (tecla==8) return true; // 3
			    patron =/[A-Za-zñÑ\s]/; // 4
			    te = String.fromCharCode(tecla); // 5
			    return patron.test(te); // 6
			}

			function trim(cad)
			{
				return cad.replace(/^s+|s+$/g,"");
			} 

			function ValidarCaracteres(textareaControl, maxlength) {

	            if (textareaControl.value.length > maxlength) {
	                textareaControl.value = textareaControl.value.substring(0, maxlength);
	            }
	        }		
		</script>
	
</head>

<body style="padding-top: 45px;">

<?php
	$aut = Zend_Auth::getInstance();
	$objEmocionDao = new Application_Model_EmocionDao();
	$objUsuarioDao = new Application_Model_UsuarioDao();
?>

<div class="navbar navbar-fixed-top" data-dropdown="dropdown">
	<div class="navbar-inner">
    	<div class="container">
    	
    	    <div class="nav-collapse">
    	  
   	    	<?php if($aut->hasIdentity()){ ?>
   	    	
   	    		<ul class="nav">
   	    		<li>
   	    			 <img src="/imagenes/proyecto/logo5.png">
			    </li>
   	    		<li>
			  	    <img src="/imagenes/proyecto/logo4.png" width="50%">
			    </li>
			    <li>
			    <a href="/muro/index/">Muro</a>
			    </li>
			    <li>
			    <a href="/muro/noticias/">Noticias</a>
			    </li>
			    <li><a href="/muro/mi-muro/">Mi Muro</a></li>
			    <li>
			    		<div style="width: 40px;">
	       						<img alt="" src="<?php echo $this->baseUrl()?>/imagenes/minicaras/<?php echo $objEmocionDao->obtenerPorId($aut->getIdentity()->emo_id)->getFoto();?>">
         				</div>
			    </li>
			    </ul>
   	    	
	    	    <ul class="nav secondary-nav pull-right">
					<li class="dropdown">
		              <a class="dropdown-toggle" href="#" data-toggle="dropdown">
							    <?php 
							    	echo $objUsuarioDao->obtenerPorId($aut->getIdentity()->usu_id)->getNombre();
							   	?>
		              	<b class="caret"></b>
		              </a>
		              
		              <ul class="dropdown-menu">
		                <li><a href="/perfil/">Mi Perfil</a></li>
		                <li class="divider"></li>
		                <li><a href="/muro/logout/">Cerrar Sesion</a></li>
		              </ul>
		            </li>
			    </ul>
			 <?php } ?>
			</div>
    	</div>
	</div>
</div>



<div class="colmask threecol">
	<div class="colmid">
		<div class="colleft">
		
		<table align="left" style="width: 100%">
			<tr>
				<td valign="top"><!-- style="background-color: #999" -->
					<div class="col1">
						<?php if($aut->hasIdentity()){ 
								echo $this->render('lateral_derecha.phtml');			
							   } 
						?>
					</div>
				</td>
				<td valign="top">
					<div class="col2">
						<?php echo $this->layout()->content; ?>
					</div>
				</td>
				<td valign="top">
					<div class="col3">
						<?php if($aut->hasIdentity()){ 
								echo $this->render('lateral_derecha.phtml');			
							   } 
						?>
					</div>
				</td>
			</tr>
		</table>
		
		</div>
	</div>
</div>



<div class="modal hide" id="myModalGenerico" style="width: 700px;">
    <div class="modal-header">
    <button class="close" onclick="closeModalGenerico()" data-dismiss="modal">×</button>
    	<div id="divModalGenericoTitulo">
    		<h3>Mensaje</h3>
    	</div>
    </div>
    <div class="modal-body">
    	<div id="divModalGenerico">
    	</div>
    </div>
    <div class="modal-footer">
  	    <a href="#" onclick="closeModalGenerico()" class="btn btn-success" data-dismiss="modal">Aceptar</a>
    </div>
</div>	

</body>
</html>
