<!DOCTYPE html>
<html lang="es">
<head>
<meta charset="utf-8">
<title>Red Social IPCIISA</title>
<meta name="author" content="Red Social IPCIISA">
    
<script type="text/javascript" src="<?php echo $this->baseUrl()?>/bootstrap/js/jquery-1.7.2.min.js"></script>    
<link type="text/css" href="<?php echo $this->baseUrl()?>/bootstrap/css/bootstrap.css" rel="stylesheet" />
<link type="text/css" href="<?php echo $this->baseUrl()?>/bootstrap/css/bootstrap-responsive.css" rel="stylesheet" />	
<script type="text/javascript" src="<?php echo $this->baseUrl()?>/bootstrap/js/bootstrap.js"></script>

<link type="text/css" href="<?php echo $this->baseUrl()?>/bootstrap/css/cupertino/jquery-ui-1.8.21.custom.css" rel="stylesheet" />
<script type="text/javascript" src="<?php echo $this->baseUrl()?>/bootstrap/js/jquery-ui-1.8.21.custom.min.js"></script>
		
		<style type="text/css">
			textarea {
				resize:none;
			}
			
			.contMini {
				width: 100px;
				word-wrap: break-word; 
			}

			.cont0 {
				width: 150px;
				word-wrap: break-word; 
			}
			
			.cont {
				width: 600px;
				word-wrap: break-word; 
			}
			
			.cont4 {
				width: 400px;
				word-wrap: break-word; 
			}
			
			.cont2 {
				width: 600px;
				word-wrap: break-word; 
			}

		</style> 
		
		<style type="text/css">
			  div#map {
			    position: relative;
			  	width: 100%;
			  }
			
			  div#crosshair {
			    position: absolute;
			    top: 192px;
			    height: 19px;
			    width: 19px;
			    left: 50%;
			    margin-left: -8px;
			    display: block;
			    background: url(<?php echo $this->baseUrl()?>/imagenes/proyecto/flag2_16x16.gif);
			    background-position: center center;
			    background-repeat: no-repeat;
			}
			</style>
		
		<script type="text/javascript">
			$(function(){

				// Datepicker
				$('#txtFechaNacimiento').datepicker({
					inline: true,
			         dateFormat: 'dd-mm-yy',
			         changeMonth: true,
			         changeYear: true,
			         dayNamesMin: ['Do','Lu', 'Ma', 'Mi', 'Ju', 'Vi', 'Sa'],
			         dayNames: ['Domingo','Lunes', 'Martes', 'Miercoles', 'Jueves', 'Viernes', 'Sabado'],
			         duration: 'fast',
			         monthNames: ['Enero','Febrero','Marzo','Abril','Mayo','Junio','Julio','Agosto','Septiembre','Octubre','Noviembre','Diciembre'],
			         monthNamesShort: ['Enero','Febrero','Marzo','Abril','Mayo','Junio','Julio','Agosto','Septiembre','Octubre','Noviembre','Diciembre'],
			         yearRange: "1930:2012", 
			         firstDay: 1	
				});

			});

			$(function(){

				// Datepicker
				$('#txtFechaEvento').datepicker({
					inline: true,
			         dateFormat: 'dd-mm-yy',
			         changeMonth: true,
			         changeYear: true,
			         dayNamesMin: ['Do','Lu', 'Ma', 'Mi', 'Ju', 'Vi', 'Sa'],
			         dayNames: ['Domingo','Lunes', 'Martes', 'Miercoles', 'Jueves', 'Viernes', 'Sabado'],
			         duration: 'fast',
			         monthNames: ['Enero','Febrero','Marzo','Abril','Mayo','Junio','Julio','Agosto','Septiembre','Octubre','Noviembre','Diciembre'],
			         monthNamesShort: ['Enero','Febrero','Marzo','Abril','Mayo','Junio','Julio','Agosto','Septiembre','Octubre','Noviembre','Diciembre'],
			         yearRange: "2012:2020",  
			         firstDay: 1	
				});

			});
		</script>
		
		<script type="text/javascript">
			function soloLetras(e) { // 1
			    tecla = (document.all) ? e.keyCode : e.which; // 2
			    if (tecla==8) return true; // 3
			    patron =/[A-Za-zñÑ\s]/; // 4
			    te = String.fromCharCode(tecla); // 5
			    return patron.test(te); // 6
			}

			function trim(cad)
			{
				return cad.replace(/^s+|s+$/g,"");
			} 

			function ValidarCaracteres(textareaControl, maxlength) {

	            if (textareaControl.value.length > maxlength) {
	                textareaControl.value = textareaControl.value.substring(0, maxlength);
	            }
	        }	

			function validarBusqueda()
			{
				var contenido = trim(document.getElementById("txtBuscador").value);

				if(contenido.length > 2)
				{
					document.getElementById("formBusqueda").submit();
					return;
				}
				
				document.getElementById("divModalGenerico").innerHTML = "Tu búsqueda debe contener 4 caracteres como mínimo.";
				$('#myModalGenerico').modal('show');			
			}

		</script>
	
</head>

<body style="padding-top: 25px;">

<?php
	$aut = Zend_Auth::getInstance();
	$objEmocionDao = new Application_Model_EmocionDao();
	$objUsuarioDao = new Application_Model_UsuarioDao();
?>

<form action="/contacto/busqueda/" id="formBusqueda" method="post">
<div class="navbar navbar-fixed-top" data-dropdown="dropdown">
	<div class="navbar-inner">
    	<div class="container">
    	    <div class="nav-collapse">
			   			
   	    	<?php if($aut->hasIdentity()){ ?>

   	    		<?php 
   	    			$datSource = "[";
   	    			$listaUsuarios = $objUsuarioDao->obtenerTodosLosNombres();
   	    			$i = 2;
   	    			 foreach ($listaUsuarios as $item)
   	    			 {
   	    			     if($item->getNombre() !="ADMINISTRADOR")
   	    			     {
	   	    			     $datSource .= "&quot;".$item->getNombre()."&quot;";
	   	    			     
	   	    			     if(count($listaUsuarios) != $i){
	   	    			         $datSource .= ",";
	   	    			     }
   	    			     }
   	    			     $i++;
   	    			 }
   	    			 $datSource .= "]";
   	    			 
   	    			//echo $datSource;
   	    			//$datSource = "[&quot;Claudio Derby&quot;]";
   	    		?>
   	    		
   	    		<input id="txtBuscador" name="txtBuscador" type="text" data-source="<?php echo $datSource;?>" data-items="10" data-provide="typeahead" style="margin: 0 auto;" class="search-query span2"  placeholder="Buscar..">
   	    		<button type="button" class="btn" onclick="validarBusqueda()">Ir..</button>
   	    		
   	    		<ul class="nav">
   	    		<li>
   	    			 <img src="/imagenes/proyecto/logo5.png">
			    </li>
   	    		<li>
			  	    <img src="/imagenes/proyecto/logo4.png" width="50%">
			    </li>
			    <li>
			    <a href="/muro/index/">Muro</a>
			    </li>
			    <li>
			    <a href="/muro/noticias/">Noticias</a>
			    </li>
			    <li><a href="/muro/mi-muro/">Mi Muro</a></li>
			    <li>
			    		<div style="width: 40px;">
	       						<img alt="" src="<?php echo $this->baseUrl()?>/imagenes/minicaras/<?php echo $objEmocionDao->obtenerPorId($aut->getIdentity()->emo_id)->getFoto();?>">
         				</div>
			    </li>
			    
			    </ul>
   	    	
	    	    <ul class="nav secondary-nav pull-right">
	    	    	
					<li class="dropdown">
		              <a class="dropdown-toggle" href="#" data-toggle="dropdown">
		              			<i class="icon-user icon-white"></i>
							    <?php 
							    	echo $objUsuarioDao->obtenerPorId($aut->getIdentity()->usu_id)->getNombre();
							   	?>
		              	<b class="caret"></b>
		              </a>
		              
		              <ul class="dropdown-menu">
		                <li><a href="/perfil/">Mi Perfil</a></li>
		                <li class="divider"></li>
		                <li><a href="/muro/logout/">Cerrar Sesión</a></li>
		              </ul>
		            </li>
			    </ul>
			 <?php } ?>
			</div>
    	</div>
	</div>
</div>
</form>

<div class="colmask threecol">
	<div class="colmid">
		<div class="colleft">
		
		<table align="left" style="width: 100%">
			<tr>
				<td valign="top"><!-- style="background-color: #999" -->
					<div class="col1">
						<?php if($aut->hasIdentity()){ 
								echo $this->render('lateral_izquierda.phtml');			
							   } 
						?>
					</div>
					<br>
				</td>
				<td valign="top">
					<div class="col2">
						<?php echo $this->layout()->content; ?>
					</div>
				</td>
				<td valign="top" align="rigth">
					<div class="col3" align="center">
						<br>
						<?php if($aut->hasIdentity()){ 
								echo $this->render('lateral_derecha.phtml');			
							   } 
						?>
						<br>
					</div>
				</td>
			</tr>
		</table>
		
		</div>
	</div>
</div>


<div class="modal hide" id="myModalGenerico" style="width: 700px;">
    <div class="modal-header">
    <button class="close" onclick="closeModalGenerico()" data-dismiss="modal">×</button>
    	<div id="divModalGenericoTitulo" class="cont2">
    		<h3>Mensaje</h3>
    	</div>
    </div>
    <div class="modal-body">
    	<div id="divModalGenerico">
    	</div>
    	<div id="divModalGenericoCometarios">
    	</div>
    </div>
    <div class="modal-footer">
  	    <a href="#" onclick="closeModalGenerico()" class="btn btn-success" data-dismiss="modal">Aceptar</a>
    </div>
</div>	

</body>
</html>
