<script type="text/javascript" src="/bootstrap/js/gmaps.js"></script>
 
 <?php
 	$aut = Zend_Auth::getInstance();
 	$objEventoDao = new Application_Model_EventoDao();
	$objEvento = $objEventoDao->obtenerPorId($this->id); 
 ?>
 
<br><h1> EVENTO 
<?php 
	if ($objEvento->getTipoEventoId() == "1"){
	    echo "PÚBLICO";
	}else{
	    echo "PRIVADO";
	}
?>
</h1><br>
 
 <table class="span9" style="width: 100%">
   		<tr>
   			<td>
						<?php $fechaPublicacion = strtotime($objEvento->getFechaEvento()); ?>	
						<?php
							switch (date("m", $fechaPublicacion))
							{
								case 1:
								    $ano = "Enero";
								break;
								case 2:
									$ano = "Febrero";
									break;
								case 3:
									$ano = "Marzo";
									break;
								case 4:
									$ano = "Abril";
									break;
								case 5:
									$ano = "Mayo";
									break;
								case 6:
									$ano = "Junio";
									break;
								case 7:
									$ano = "Julio";
									break;
								case 8:
									$ano = "Agosto";
									break;
								case 9:
									$ano = "Septiembre";
									break;
								case 10:
									$ano = "Octubre";
									break;
								case 11:
									$ano = "Noviembre";
									break;
								case 12:
									$ano = "Diciembre";
									break;
							}
							$mes = date("Y", $fechaPublicacion);
							$dia = date("d", $fechaPublicacion);
							$hora = $objEvento->getHora();
						?>		
							
						<h2>"<?php echo $objEvento->getNombre();?>" <h3>Se celebrará el <?php echo $dia."-".$ano."-".$mes." a las ".$hora." hrs.";?></h3></h2>
   				<table>
   					<tr>
   						<td valign="top">
							<div class="cont well">
   								<?php  echo $objEvento->getDescripcion(); ?>
   							</div>
   						</td>
   					</tr>
   				</table>
   			</td>
  		</tr>
  </table>
  
 <div class="tabbable well">
    <ul class="nav nav-tabs">
    	
    	<?php
			if($aut->getIdentity()->usu_id == $objEvento->getUsuarioId()){?>
				<li><a href="#tab2" data-toggle="tab"><img src="/imagenes/proyecto/addcontacto.png">&nbsp;&nbsp; Invitar Contactos </a></li>
				<li><a href="#tab1" data-toggle="tab"><img src="/imagenes/proyecto/minuscontacto.png">&nbsp;&nbsp; Quitar Contactos </a></li>
		  <?php }else{ ?>
		      	<li><a href="#tab1" data-toggle="tab"><img src="/imagenes/proyecto/user.png">&nbsp;&nbsp; Contactos </a></li>
		  <?php } ?>
		  		<li><a href="#tab3" data-toggle="tab"><img src="/imagenes/proyecto/tierra.png">&nbsp;&nbsp; Mapa </a></li>
    </ul>
    <div class="tab-content">
    	<div class="tab-pane" id="tab1">
				
			<?php 
				$columna = 0;
				$cantColumna = 6;
			?>
				<table width="100%" align="center">
				
					<?php foreach ($this->listaUsuariosEvento as $usuario){					    
					    
							if($columna == 0){ 
							   echo "<tr>";
							} 
							echo "<td>";?> 
							<!-- imprimir el objeto -->
								<table align="center">
									<tr>
										<td align="center">
											<a href="/muro/muro-contacto/id/<?php echo $usuario->getId();?>"><?php echo $usuario->getNombre();?></a>
										</td>
									</tr>
									<tr>
										<td align="center">
				          				<a class="thumbnail" href="#">
											<img src="<?php echo $this->baseUrl()?>/imagenes/usuarios/icono/<?php echo $usuario->getFoto(); ?>"></img>					          					
				          				</a>
										</td>
									</tr>
									<tr>
										<td align="center">
											<?php 
												$objUsuarioEventoDao = new Application_Model_UsuarioEventoDao();
												$flagEliminado = $objUsuarioEventoDao->obtenerPorGrupoYUsuario($this->id, $usuario->getId());
												if($flagEliminado == 1)
												{
												    	$flagEliminado = "checked='checked'";
												}
											?>
												
											<?php if($objEvento->getUsuarioId() == $aut->getIdentity()->usu_id){?>	
												    <?php if($usuario->getId() != $objEvento->getUsuarioId()){?>					
														<input type="checkbox" <?php echo $flagEliminado;?> name="cbxEliminar<?php echo $usuario->getId(); ?>" id="cbxEliminar<?php echo $usuario->getId(); ?>" onClick='aEliminar(<?php echo $usuario->getId();?>)'></a>
													<?php } ?>
											<?php } ?>											
										</td>
									</tr>
								</table>	
							<!-- fin de imprimir el objeto -->
							<?php 
							echo "</td>"; 
							$columna++;
							 if($columna == $cantColumna){
								 echo "</tr>";				
								 $columna = 0;
							 }						 
					}
						 echo "</tr>";
					?>
					
				</table>	
				
				 	<?php 
				 	$objUsuarioEventoDao = new Application_Model_UsuarioEventoDao();
			    	$countCheck = $objUsuarioEventoDao->obtenerMarcadosEliminar($this->id);
			    	?>
					<input type="hidden" id="hdnCountEliminar" value="<?php echo $countCheck;?>">
					
					<?php
					if($aut->getIdentity()->usu_id == $objEvento->getUsuarioId()){?>
					  <button type="button" onclick="openModalConfirmarEliminar()" id="btnEliminarContactos" name="btnEliminarContactos" class="btn btn-success" onclick="openModalConfirmarEliminar(<?php echo $this->grupoId;?>)">
						<img src="/imagenes/proyecto/papelera.png">&nbsp;&nbsp; Eliminar contactos seleccionados
					 </button>
					<?php }
					?>
    	</div>
    	<div class="tab-pane active" id="tab2">
    		
    		<?php 
				$columna = 0;
				$cantColumna = 6;
			?>
			<table width="100%" align="center">
				<?php foreach ($this->listaUsuarios as $usuario){ ?>
				    <?php
					    $objInvitacionDao = new Application_Model_InvitacionDao();
					    $flagInvitar = $objInvitacionDao->obtenerPorEventoYUsuario($this->id, $usuario->getId());
					    if($flagInvitar == 1)
					    {
					    	$flagInvitar = "checked='checked'";
					    }
					    $objUsuarioEventoDao = null;
				    ?>
				    <?php if($flagInvitar != 4){ ?>
				    <?php 
						if($columna == 0){ 
						   echo "<tr>";
						} 
						echo "<td>";?> 
						<!-- imprimir el objeto -->
							<table align="center">
								<tr>
									<td align="center">
										<a href="/muro/muro-contacto/id/"><?php echo $usuario->getNombre();?></a>
									</td>
								</tr>
								<tr>
									<td align="center">
			          				<a class="thumbnail" href="#">
										<img src="<?php echo $this->baseUrl()?>/imagenes/usuarios/icono/<?php echo $usuario->getFoto(); ?>"></img>					          					
			          				</a>
									</td>
								</tr>
								<tr>
									<td align="center">
										<?php if($flagInvitar != 2){?>
												<input type="checkbox" <?php echo $flagInvitar;?>name="cbx<?php echo $usuario->getId(); ?>" id="cbx<?php echo $usuario->getId(); ?>" onClick='aInvitar(<?php echo $usuario->getId(); ?>)'>
										<?php  }else{ ?>
											Invitación enviada
										<?php }?>
									</td>
								</tr>
							</table>	
						<!-- fin de imprimir el objeto -->
						<?php 
						echo "</td>"; 
						$columna++;
						 if($columna == $cantColumna){
							 echo "</tr>";				
							 $columna = 0;
						 }
					   } 
					 }
					 echo "</tr>";
				?>
			</table>
			
			<?php 
				$objInvitacionDao = new Application_Model_InvitacionDao();
    			$countCheck = $objInvitacionDao->obtenerCantidadSeleccionados($this->id);
    		?>	
			<input type="hidden" id="hdnCountInvitar" value="<?php echo $countCheck;?>">
			
			  <?php
					if($aut->getIdentity()->usu_id == $objEvento->getUsuarioId()){ ?>
							<center><input type="button" id="btnInvitarContactos" name="btnInvitarContactos" value="Invitar Usuarios Seleccionados" onclick="openModalConfirmarInvitar()" class="btn btn-info"></center>
			  <?php } ?>
			
    	</div>
    	<div class="tab-pane" id="tab3">
    		<a href="#" id="btnCargarMapa" class="btn btn-info" onclick="openSolapaMapa();">Click aquí para cargar el mapa..</a>
    		<div id="map_canvas" style="width: 100%; height: 400px;"></div>
    	</div>
    </div>
 </div>
 
 <input type="hidden" id="hdnCoordenadaX" value="<?php echo $objEvento->getCordenadaX();?>">
 <input type="hidden" id="hdnCoordenadaY" value="<?php echo $objEvento->getCordenadaY();?>">
 
 <div class="modal hide" id="myModalInvitar" style="width: 700px;">
    <div class="modal-header">
    <button class="close" data-dismiss="modal">×</button>
    <h2><img src="/imagenes/proyecto/Info.png">&nbsp;&nbsp;&nbsp;Invitar Usuarios</h2>
    </div>
    <div class="modal-body">
    	¿Esta seguro de Invitar a los usuarios? <div id="divEvento"></div> 
    </div>
    <div class="modal-footer">
    	<a class="btn btn-success" href="/evento/invitar-usuario-evento/id/<?php echo $this->id;?>">Si, invitar</a>
  	    <a href="#" class="btn btn-danger" data-dismiss="modal">Cancelar</a>
    </div>
</div>	

<div class="modal hide" id="myModalInvitarSinUsuarios" style="width: 700px;">
    <div class="modal-header">
    <button class="close" data-dismiss="modal">×</button>
    <h2><img src="/imagenes/proyecto/cruz.png">&nbsp;&nbsp;&nbsp;Ningún Usuario Seleccionado</h2>
    </div>
    <div class="modal-body">
    	No hay usuarios seleccionados<div id="divGrupo"></div> 
    </div>
    <div class="modal-footer">
  	    <a href="#" class="btn btn-success" data-dismiss="modal">Aceptar</a>
    </div>
</div>

<div class="modal hide" id="myModalEliminarUsuariosEvento" style="width: 700px;">
    <div class="modal-header">
    <button class="close" data-dismiss="modal">×</button>
    <h2><img src="/imagenes/proyecto/Info.png">&nbsp;&nbsp;&nbsp;Eliminar Usuarios</h2>
    </div>
    <div class="modal-body">
    	¿Estas seguro de eliminar a los usuarios seleccionados?
    </div>
    <div class="modal-footer">
  	    <a href="#" onclick="eliminarContactosDelEvento(<?php echo $this->id;?>)" class="btn btn-success" data-dismiss="modal">Si, eliminar</a>
  	    <a href="#" class="btn btn-danger" data-dismiss="modal">Cerrar</a>
    </div>
</div>

<div class="modal hide" id="myModalEliminarUsuarioGrupoNoSelecionado" style="width: 700px;">
    <div class="modal-header">
    <button class="close" data-dismiss="modal">×</button>
    <h2><img src="/imagenes/proyecto/cruz.png">&nbsp;&nbsp;&nbsp;Ningún Usuario Seleccionado</h2>
    </div>
    <div class="modal-body">
    	No has seleccionado a ningún usuario para eliminar.
    </div>
    <div class="modal-footer">
  	    <a href="#" class="btn btn-success" data-dismiss="modal">Aceptar</a>
    </div>
</div>
			
 <script type="text/javascript">
 
 var map;
 var geocoder;
 var centerChangedLast;
 var reverseGeocodedLast;
 var currentReverseGeocodeResponse;

 function initialize() {
	 
   var x = document.getElementById('hdnCoordenadaX').value;
   var y = document.getElementById('hdnCoordenadaY').value;
	 
   var latlng = new google.maps.LatLng(x, y);
   var myOptions = {
     zoom: 16,
     center: latlng,
     mapTypeId: google.maps.MapTypeId.ROADMAP
   };
   map = new google.maps.Map(document.getElementById("map_canvas"), myOptions);
   geocoder = new google.maps.Geocoder();

   var marker = new google.maps.Marker({
       position: map.getCenter(),
       map: map
   });

   //setupEvents();
   //centerChanged();

 }

 	function setupEvents() {
	    reverseGeocodedLast = new Date();
	    centerChangedLast = new Date();

	    setInterval(function() {
	      if((new Date()).getSeconds() - centerChangedLast.getSeconds() > 1) {
	        if(reverseGeocodedLast.getTime() < centerChangedLast.getTime())
	          reverseGeocode();
	      }
	    }, 1000);

	    google.maps.event.addListener(map, 'zoom_changed', function() {
	      document.getElementById("zoom_level").innerHTML = map.getZoom();
	    });

	    google.maps.event.addListener(map, 'center_changed', centerChanged);

	    google.maps.event.addDomListener(document.getElementById('crosshair'),'dblclick', function() {
	       map.setZoom(map.getZoom() + 1);
	    });

	  }

 	function getCenterLatLngText() {
 	    return '(' + map.getCenter().lat() +', '+ map.getCenter().lng() +')';
 	  }

 	  function centerChanged() {
 	    centerChangedLast = new Date();
 	    var latlng = getCenterLatLngText();
 	    document.getElementById('latlng').innerHTML = latlng;
 	    document.getElementById('hdnCordenadas').value = latlng;
 	    document.getElementById('formatedAddress').innerHTML = '';
 	    currentReverseGeocodeResponse = null;
 	  }

 	  function reverseGeocode() {
 	    reverseGeocodedLast = new Date();
 	    geocoder.geocode({latLng:map.getCenter()},reverseGeocodeResult);
 	  }

 	  function reverseGeocodeResult(results, status) {
 	    currentReverseGeocodeResponse = results;
 	    if(status == 'OK') {
 	      if(results.length == 0) {
 	        document.getElementById('formatedAddress').innerHTML = 'None';
 	      } else {
 	        document.getElementById('formatedAddress').innerHTML = results[0].formatted_address;
 	      }
 	    } else {
 	      document.getElementById('formatedAddress').innerHTML = 'Error';
 	    }
 	  }


 	  function geocode() {
 	    var address = document.getElementById("address").value;
 	    geocoder.geocode({
 	      'address': address,
 	      'partialmatch': true}, geocodeResult);
 	  }

 	  function geocodeResult(results, status) {
 	    if (status == 'OK' && results.length > 0) {
 	      map.fitBounds(results[0].geometry.viewport);
 	    } else {
 	      alert("GeoLocalización no tuvo éxito por las siguientes razones: " + status);
 	    }
 	  }

 	  function addMarkerAtCenter() {

 		initialize();

 		//GO inizialite
 	   var latlng = new google.maps.LatLng(-33.45532014786473, -70.66714304333493);
 	    var myOptions = {
 	      zoom: 16,
 	      center: latlng,
 	      mapTypeId: google.maps.MapTypeId.ROADMAP
 	    };
 	    map = new google.maps.Map(document.getElementById("map_canvas"), myOptions);
 	    geocoder = new google.maps.Geocoder();
 	    setupEvents();
 	    centerChanged(); //END inizialite
 		
 	    var marker = new google.maps.Marker({
 	        position: map.getCenter(),
 	        map: map
 	    });

 	    var text = 'Lat/Lng: ' + getCenterLatLngText();
 	    if(currentReverseGeocodeResponse) {
 	      var addr = '';
 	      if(currentReverseGeocodeResponse.size == 0) {
 	        addr = 'None';
 	      } else {
 	        addr = currentReverseGeocodeResponse[0].formatted_address;
 	      }
 	      text = text + '<br>' + 'Dirección: <br>' + addr;
 	    }

 	    var infowindow = new google.maps.InfoWindow({ content: text });

 	    google.maps.event.addListener(marker, 'click', function() {
 	      infowindow.open(map,marker);
 	    });
 	  }

 	  /*
 		END CODE MAPS
 	  */

 function openSolapaMapa()
 {
	document.getElementById("btnCargarMapa").style.display = 'none';
	initialize();	
 }

 function eliminarContactosDelEvento(id)
	{
		$.ajax(
				{
				async: true,
				type: 'POST',
				url: '<?php echo $this->baseUrl()?>/evento/eliminar-usuarios-evento',
				data: 'eventoId='+id,	
				dataTypeString: 'text',
				
				beforeSend: function(data){
					  //selectDestino.html('<img src="/imagenes/proyecto/ajax-loader.gif">');
			    },  
			    success: function(requestData){
				    var result = requestData;
				    location.href="/evento/index/se/ok";
				    
			    },  
			    error: function(requestData, strError, strTipoError){          
			    }
			    
				});
	}

 function openModalConfirmarEliminar()
	{
		if (document.getElementById("hdnCountEliminar").value > 0)
		{
			$('#myModalEliminarUsuariosEvento').modal("show");
		}		
		else
		{
			$('#myModalEliminarUsuarioGrupoNoSelecionado').modal("show");
		}		
	}

 function aEliminar(usuId)
	{
		var cbxUsuario = document.getElementById("cbxEliminar" + usuId).checked;
		var check = "";		

		if (cbxUsuario)
		{
			check = 1;
			document.getElementById("hdnCountEliminar").value = document.getElementById("hdnCountEliminar").value + 1;
		}
		else		 
		{
			check = 0;
			document.getElementById("hdnCountEliminar").value = document.getElementById("hdnCountEliminar").value - 1;
		}	

		$.ajax(
				{
				async: true,
				type: 'POST',
				url: '<?php echo $this->baseUrl()?>/evento/marcar-eliminar',
				data: 'usuarioId='+usuId+'&cbxUsuario='+check+'&eventoId='+<?php echo $this->id;?>,	
				dataTypeString: 'text',
				
				beforeSend: function(data){
					  //selectDestino.html('<img src="/imagenes/proyecto/ajax-loader.gif">');
			    },  
			    success: function(requestData){
				    var result = requestData;

			    },  
			    error: function(requestData, strError, strTipoError){          
			    }
			    
				});
	}

 function openModalConfirmarInvitar()
 {
	if (document.getElementById("hdnCountInvitar").value > 0)
	{
		$('#myModalInvitar').modal("show");
	}else{
		$('#myModalInvitarSinUsuarios').modal("show");
	}		
 }

 function aInvitar(usuId)
	{
		var cbxUsuario = document.getElementById("cbx" + usuId).checked;
		var check = "";		

		if (cbxUsuario)
		{
			check = 1;
			document.getElementById("hdnCountInvitar").value = document.getElementById("hdnCountInvitar").value + 1;
		}
		else		 
		{
			check = 0;
			document.getElementById("hdnCountInvitar").value = document.getElementById("hdnCountInvitar").value - 1;
		}	

		$.ajax(
				{
				async: true,
				type: 'POST',
				url: '<?php echo $this->baseUrl()?>/evento/marcar-invitar',
				data: 'usuarioId='+usuId+'&cbxUsuario='+check+'&eventoId='+<?php echo $this->id;?>,	
				dataTypeString: 'text',
				
				beforeSend: function(data){
					  //selectDestino.html('<img src="/imagenes/proyecto/ajax-loader.gif">');
			    },  
			    success: function(requestData){
				    var result = requestData;
			    },  
			    error: function(requestData, strError, strTipoError){          
			    }
			    
				});
	}

	function hola()
	{
		initialize();
	}

 </script>			 