<script type="text/javascript" src="/bootstrap/js/maps.js"></script>

<br>
<a href="#" onclick="openModalEvento()" class="btn"><i class="icon-calendar"></i> Crear Evento </a><br><br>

  <?php 
 		if($this->succesEliminarUsuarios == "ok")
		{
			$msj = "";
			$msj .= "<div class='alert alert-success'>";
			$msj .= "<button class='close' data-dismiss='alert'>×</button>";
			$msj .= "<strong>Éxito!</strong> Usuarios han sido eliminados del evento!!";
			$msj .= "</div>";
			
			echo $msj;	
  		}
  		
  		if($this->succesInvitarUsuarios == "ok")
  		{
  			$msj = "";
  			$msj .= "<div class='alert alert-success'>";
  			$msj .= "<button class='close' data-dismiss='alert'>×</button>";
  			$msj .= "<strong>Éxito!</strong> Usuarios han sido invitados al evento!!";
  			$msj .= "</div>";
  				
  			echo $msj;
  		}
  ?>

<div class="tabbable span9 well">
	<ul class="nav nav-tabs">
		<li class="active"><a href="#tab1" data-toggle="tab">Mis Eventos
				comprometidos</a></li>
		<li><a href="#tab2" data-toggle="tab">Invitaciones Recibidas</a></li>
	</ul>
	<div class="tab-content">
		<div class="tab-pane active" id="tab1">
		
			<div id="divMensajeEvento"></div>
		
			<table>
		    <?php
		    	echo $this->listaEventos;
		    	foreach ($this->listaEventos as $evento){ ?>
		    	<tr id="filaEventoUno<?php echo $evento->getId();?>">
					<td colspan="6">
		    			<?php echo $evento->getNombre();?>
		    		</td>
				</tr>
				<tr id="filaEventoDos<?php echo $evento->getId();?>">
					<td>
		    			<?php $fechaPublicacion = strtotime($evento->getFechaEvento()); ?>
						<table class="span2 well">
							<tr>
								<td align="center" class='label label-success'>
											<?php
												switch (date("m", $fechaPublicacion))
												{
													case 1:
													    echo "Ene";
													break;
													case 2:
														echo "Feb";
														break;
													case 3:
														echo "Mar";
														break;
													case 4:
														echo "Abr";
														break;
													case 5:
														echo "May";
														break;
													case 6:
														echo "Jun";
														break;
													case 7:
														echo "Jul";
														break;
													case 8:
														echo "Ago";
														break;
													case 9:
														echo "Sep";
														break;
													case 10:
														echo "Oct";
														break;
													case 11:
														echo "Nov";
														break;
													case 12:
														echo "Dic";
														break;
												}
												echo " - ";
												echo date("Y", $fechaPublicacion);
											?>
										</td>
							</tr>
							<tr>
								<td align="center">
									<h2><?php echo date("d", $fechaPublicacion); ?></h2>
								</td>
							</tr>
						</table>
					</td>
					<td><a class="btn btn-info"
						href="/evento/contactos/id/<?php echo $evento->getId();?>">Ver Evento</a>
					</td>
					
					<?php
					$aut = Zend_Auth::getInstance();
					if($aut->getIdentity()->usu_id == $evento->getUsuarioId()){?>
						<td><a class="btn btn-info" href="#"> Editar </a></td>
						<td><a class="btn btn-info" onclick="openMyModalCancelarEvento('<?php echo $evento->getId();?>','<?php echo $evento->getNombre();?>')" > Cancelar </a></td>
					<?php }else{ ?>
						<td><a class="btn btn-info" onclick="noAsistire(<?php echo $evento->getId();?>)"> No asistiré </a></td>
					<?php }?>
				</tr>
		    <?php } ?>
		    	</table>
		</div>
		<div class="tab-pane" id="tab2">
				<?php echo $this->listaInvitacionesEvento;
    		$objEventoDao = new Application_Model_EventoDao();
    		
    		?>
    		<div id="divMensajeInvitacion"></div>
			<table>
	    			<?php 
			    		foreach ($this->listaInvitacionesEvento as $item)
			    		{
	    			?>
						<tr id="rowUnoInvitacion<?php echo $item->getId();?>"
					style="display: block;">
					<td colspan=2>
								<?php 
									$objGrupo = $objEventoDao->obtenerPorId($item->getIdActividad());
									echo $objGrupo->getNombre();
								?>
							</td>
				</tr>
				<tr id="rowDosInvitacion<?php echo $item->getId();?>"
					style="display: block;">
					<td>
						<div style='width: 80px;'>
							<a class='thumbnail'> **EVENTO** </a>
						</div>
					</td>
					<td>
						<a class="btn btn-info" onclick="openModalAceptarInvitacion(<?php echo $item->getId();?>)"> Aceptar invitación </a> 
						<a class="btn btn-info" onclick="openMyModalRechazarEvento(<?php echo $item->getId();?>)">Rechazar invitación </a>
					</td>
				</tr>  
					<?php }?>
	    		</table>
		</div>
	</div>
</div>

<div class="modal hide" id="myModalEvento" style="width: 700px;">
	<div class="modal-header">
		<button class="close" data-dismiss="modal">×</button>
		<h3>Nuevo Evento</h3>
	</div>
	<div class="modal-body">

		<form id="formEvento" action="/evento/index/" method="POST">

			<table style="width: 100%;">
				<tr>
					<td colspan="2"><a id="arriba" name="arriba"></a>
						<div id="divErroresEvento"></div></td>
				</tr>
				<tr>
					<td>Nombre:</td>
					<td align="left"><input type="text" id="txtNombreEvento"
						name="txtNombreEvento" size="50" maxlength="49"></td>
				</tr>
				<tr>
					<td>Descripción:</td>
					<td align="left"><textarea rows="4" class="span6"
							id="txtDescripcion" name="txtDescripcion"></textarea></td>
				</tr>
				<tr>
					<td colspan="2">¿Cuál es el Lugar ? &nbsp;<input type="text"
						id="address" name="address" />&nbsp;&nbsp;<input type="button"
						value="Buscar" onclick="geocode()" class="label label-success">&nbsp;&nbsp;
						<input type="button" value="Seleccionar lugar"
						onclick="addMarkerAtCenter()" class="label label-success" />
					</td>
				</tr>
				<tr>
					<td colspan="2" class="label label-warning"><div
							id="formatedAddress"></div></td>
				</tr>
				<tr>
					<td colspan="2" align="center">
						<div id="map">
							<div id="map_canvas" style="width: 80%; height: 400px;"></div>
							<div id="crosshair"></div>
						</div>
					</td>
				</tr>
				<tr>
					<td>Fecha:</td>
					<td>
				<?
					$fecha = time();
				?> 
				<input type="text" id="txtFechaEvento" name="txtFechaEvento"
						readonly="readonly"> <select id="sltHora" name="sltHora">
							<option value="">Seleccione</option>
							<option value="01:00">01:00</option>
							<option value="02:00">02:00</option>
							<option value="03:00">03:00</option>
							<option value="04:00">04:00</option>
							<option value="05:00">05:00</option>
							<option value="06:00">06:00</option>
							<option value="07:00">07:00</option>
							<option value="08:00">08:00</option>
							<option value="09:00">09:00</option>
							<option value="10:00">10:00</option>
							<option value="11:00">11:00</option>
							<option value="12:00">12:00</option>
							<option value="13:00">13:00</option>
							<option value="14:00">14:00</option>
							<option value="15:00">15:00</option>
							<option value="16:00">16:00</option>
							<option value="17:00">17:00</option>
							<option value="18:00">18:00</option>
							<option value="19:00">19:00</option>
							<option value="20:00">20:00</option>
							<option value="21:00">21:00</option>
							<option value="22:00">22:00</option>
							<option value="23:00:00">23:00</option>
							<option value="00:00">00:00</option>
					</select>
					</td>
				</tr>
				<tr>
					<td><input type="radio" name="cbxTipo" value="1" checked> Público<br>
					</td>
					<td></td>
				</tr>
				<tr>
					<td><input type="radio" name="cbxTipo" value="2"> Privado</td>
					<td></td>
				</tr>
			</table>

			<table>
				<tr style="display: none;">
					<td>Lat/Lng:</td>
					<td><div id="latlng"></div></td>
				</tr>
				<tr style="display: none;">
					<td>Zoom Level</td>
					<td><div id="zoom_level">2</div></td>
				</tr>
			</table>

			<input type="hidden" id="hdnCordenadas" name="hdnCordenadas"> <input type="hidden" id="hdnDireccionSeleccionada" name="hdnDireccionSeleccionada">
			<input type="hidden" id="hdnIdEvento" value="<?php echo $this->id;?>">

		</form>

	</div>
	<div class="modal-footer">
		<a href="#" onclick="crearEvento();" class="btn btn-success">Crear
			Evento</a>
	</div>
</div>

<div class="modal hide" id="myModalAceptarInvitacion"
	style="width: 700px;">
	<div class="modal-header">
		<button class="close" data-dismiss="modal">×</button>
		Aceptar invitación
	</div>
	<div class="modal-body">
		¿Deseas aceptar la invitación al grupo?
		<div id="divGrupo"></div>
		<input type="hidden" id="hdnInvitacionId">
	</div>
	<div class="modal-footer">
		<a href="#" onclick="aceptarInvitacionEvento()"
			class="btn btn-success" data-dismiss="modal">Aceptar</a> <a href="#"
			class="btn btn-success" data-dismiss="modal">Cancelar</a>
	</div>
</div>

<div class="modal hide" id="myModalCancelarEvento" style="width: 700px;">
	<div class="modal-header">
		<button class="close" data-dismiss="modal">×</button>
		Cancelar Evento
	</div>
	<div class="modal-body">
		<div id="divNombreEventoCancelar"></div> 
		<input type="hidden" id="hdnEventoCancelarId">
	</div>
	<div class="modal-footer">
		<a href="#" onclick="cancelarEvento()" class="btn btn-success" data-dismiss="modal">Cancelar Evento</a> <a
			href="#" class="btn btn-error" data-dismiss="modal">Cerrar</a>
	</div>
</div>

<div class="modal hide" id="myModalRechazarEvento" style="width: 700px;">
	<div class="modal-header">
		<button class="close" data-dismiss="modal">×</button>
		Rechazar invitación
	</div>
	<div class="modal-body">
		¿Estás seguro de rechazar la invitación?
		<input type="hidden" id="hdnEventoId">
	</div>
	<div class="modal-footer">
		<a href="#" class="btn btn-success" onclick="rechazarInvitacionEvento()" data-dismiss="modal">Rechazar Invitación</a>
		<a href="#" class="btn btn-error" data-dismiss="modal">Cerrar</a>
	</div>
</div>

<script type="text/javascript">

 initialize();
	
  var map;
  var geocoder;
  var centerChangedLast;
  var reverseGeocodedLast;
  var currentReverseGeocodeResponse;

  function initialize() {
    var latlng = new google.maps.LatLng(-33.45532014786473, -70.66714304333493);
    var myOptions = {
      zoom: 16,
      center: latlng,
      mapTypeId: google.maps.MapTypeId.ROADMAP
    };
    map = new google.maps.Map(document.getElementById("map_canvas"), myOptions);
    geocoder = new google.maps.Geocoder();

    setupEvents();
    centerChanged();

  }

  function setupEvents() {
    reverseGeocodedLast = new Date();
    centerChangedLast = new Date();

    setInterval(function() {
      if((new Date()).getSeconds() - centerChangedLast.getSeconds() > 1) {
        if(reverseGeocodedLast.getTime() < centerChangedLast.getTime())
          reverseGeocode();
      }
    }, 1000);

    google.maps.event.addListener(map, 'zoom_changed', function() {
      document.getElementById("zoom_level").innerHTML = map.getZoom();
    });

    google.maps.event.addListener(map, 'center_changed', centerChanged);

    google.maps.event.addDomListener(document.getElementById('crosshair'),'dblclick', function() {
       map.setZoom(map.getZoom() + 1);
    });

  }

  function getCenterLatLngText() {
    return '(' + map.getCenter().lat() +', '+ map.getCenter().lng() +')';
  }

  function centerChanged() {
    centerChangedLast = new Date();
    var latlng = getCenterLatLngText();
    document.getElementById('latlng').innerHTML = latlng;
    document.getElementById('hdnCordenadas').value = latlng;
    document.getElementById('formatedAddress').innerHTML = '';
    currentReverseGeocodeResponse = null;
  }

  function reverseGeocode() {
    reverseGeocodedLast = new Date();
    geocoder.geocode({latLng:map.getCenter()},reverseGeocodeResult);
  }

  function reverseGeocodeResult(results, status) {
    currentReverseGeocodeResponse = results;
    if(status == 'OK') {
      if(results.length == 0) {
        document.getElementById('formatedAddress').innerHTML = 'None';
      } else {
        document.getElementById('formatedAddress').innerHTML = results[0].formatted_address;
      }
    } else {
      document.getElementById('formatedAddress').innerHTML = 'Error';
    }
  }


  function geocode() {
    var address = document.getElementById("address").value;
    geocoder.geocode({
      'address': address,
      'partialmatch': true}, geocodeResult);
  }

  function geocodeResult(results, status) {
    if (status == 'OK' && results.length > 0) {
      map.fitBounds(results[0].geometry.viewport);
    } else {
      alert("GeoLocalización no tuvo éxito por las siguientes razones: " + status);
    }
  }

  function addMarkerAtCenter() {

	document.getElementById("hdnDireccionSeleccionada").value = "SI";
	var cordenadaXeY = document.getElementById("hdnCordenadas").value;
	cordenadaXeY = cordenadaXeY.replace("(","");
	cordenadaXeY = cordenadaXeY.replace(")","");

	var arrayCordenadas = cordenadaXeY.split(",");

	initialize();

	//GO inizialite
   var latlng = new google.maps.LatLng(arrayCordenadas[0],arrayCordenadas[1]);
    var myOptions = {
      zoom: 16,
      center: latlng,
      mapTypeId: google.maps.MapTypeId.ROADMAP
    };
    map = new google.maps.Map(document.getElementById("map_canvas"), myOptions);
    geocoder = new google.maps.Geocoder();
    setupEvents();
    centerChanged(); //END inizialite
	
    var marker = new google.maps.Marker({
        position: map.getCenter(),
        map: map
    });

    var text = 'Lat/Lng: ' + getCenterLatLngText();
    if(currentReverseGeocodeResponse) {
      var addr = '';
      if(currentReverseGeocodeResponse.size == 0) {
        addr = 'None';
      } else {
        addr = currentReverseGeocodeResponse[0].formatted_address;
      }
      text = text + '<br>' + 'Dirección: <br>' + addr;
    }

    var infowindow = new google.maps.InfoWindow({ content: text });

    google.maps.event.addListener(marker, 'click', function() {
      infowindow.open(map,marker);
    });
  }

  /*
	END CODE MAPS
  */

  function crearEvento()
  {
	  var errores = false;
	  var htmlErrores = "<ul type = square>";
	  
	  if(trim(document.getElementById("txtNombreEvento").value) == "")
	  {
		  htmlErrores = htmlErrores + "<li>Debes ingresar el nombre del evento";
		  errores = true;
	  }

	  if(trim(document.getElementById("txtDescripcion").value) == "")
	  {
		  htmlErrores = htmlErrores + "<li>Debes ingresar una breve descripción";
		  errores = true;
	  }

	  if(trim(document.getElementById("address").value) == "")
	  {
		  htmlErrores = htmlErrores + "<li>Debes ingresar la dirección del evento";
		  errores = true;
	  }

	  if(trim(document.getElementById("txtFechaEvento").value) == "")
	  {
		  htmlErrores = htmlErrores + "<li>Debes ingresar la fecha del evento";
		  errores = true;
	  }

	  if(trim(document.getElementById("sltHora").value) == "")
	  {
		  htmlErrores = htmlErrores + "<li>Debes ingresar la hora del evento";
		  errores = true;
	  }

	  if(trim(document.getElementById("hdnDireccionSeleccionada").value) == "")
	  {
		  htmlErrores = htmlErrores + "<li>Debes seleccionar la ubicación específica en el mapa";
		  errores = true;
	  }

	  htmlErrores = htmlErrores + "</ul>";

	  document.getElementById("divErroresEvento").innerHTML = htmlErrores; 

	  if(errores)
	  {
		  location.href="#arriba";
	  }else{
	  	  document.getElementById("formEvento").submit();
	  }
  }

	function openModalEvento()
	{	
		$('#myModalEvento').modal('show');
		addMarkerAtCenter();		
	}

	   
    function openModalAceptarInvitacion(idInvitacion)
	{
		document.getElementById("hdnInvitacionId").value = idInvitacion;
		$('#myModalAceptarInvitacion').modal("show");	
	}

    function aceptarInvitacionEvento(){

		var invitacionId = document.getElementById("hdnInvitacionId").value;

			$.ajax(
					{
					async: true,
					type: 'POST',
					url: '<?php echo $this->baseUrl()?>/evento/aceptar-invitacion',
					data: 'invitacionId=' + invitacionId,	
					dataTypeString: 'text',
					
					beforeSend: function(data){
						  //selectDestino.html('<img src="/imagenes/proyecto/ajax-loader.gif">');
				    },  
				    success: function(requestData){

				    	var result = requestData;
				    	 
						if(result == "ok")
						{
							document.getElementById("rowUnoInvitacion" + invitacionId).style.display = "none";
							document.getElementById("rowDosInvitacion" + invitacionId).style.display = "none";

							var divMsj = "<div class='alert alert-success'>";
							divMsj = divMsj + "<button class='close' data-dismiss='alert'>×</button>";
							divMsj = divMsj + "Ahora eres parte del grupo.";
							divMsj = divMsj + "</div>";

							document.getElementById("divMensajeInvitacion").innerHTML = divMsj;  
						}
					      
				    },  
				    error: function(requestData, strError, strTipoError){          
				    }
				    
					});
	}


    function openMyModalCancelarEvento(id,nombre)
	{	
		$('#myModalCancelarEvento').modal('show');
		document.getElementById("divNombreEventoCancelar").innerHTML = '¿Estás seguro de cancelar el evento <b>' + nombre + '</b> ?';
		document.getElementById("hdnEventoCancelarId").value = id;
	}
    
    function openMyModalRechazarEvento(id)
	{	
		$('#myModalRechazarEvento').modal('show');
		document.getElementById("hdnEventoId").value = id;
	}

    function noAsistire(id){

		$.ajax(
				{
				async: true,
				type: 'POST',
				url: '<?php echo $this->baseUrl()?>/evento/no-asistir',
				data: 'id=' + id,	
				dataTypeString: 'text',
				
				beforeSend: function(data){
					  //selectDestino.html('<img src="/imagenes/proyecto/ajax-loader.gif">');
			    },  
			    success: function(requestData){
				    var result = requestData;

					if(result == "ok")
					{
						document.getElementById("filaEventoUno" + id).style.display = "none";
						document.getElementById("filaEventoDos" + id).style.display = "none";

						var divMsj = "<div class='alert alert-success'>";
						divMsj = divMsj + "<button class='close' data-dismiss='alert'>×</button>";
						divMsj = divMsj + "Has indicado que no asistirás al evento";
						divMsj = divMsj + "</div>";

						document.getElementById("divMensajeEvento").innerHTML = divMsj;  
					}
			    },  
			    error: function(requestData, strError, strTipoError){          
			    }
			    
				});
	}

    function cancelarEvento(){

		var id = document.getElementById("hdnEventoCancelarId").value;

			$.ajax(
					{
					async: true,
					type: 'POST',
					url: '<?php echo $this->baseUrl()?>/evento/cancelar-evento',
					data: 'id=' + id,	
					dataTypeString: 'text',
					
					beforeSend: function(data){
						  //selectDestino.html('<img src="/imagenes/proyecto/ajax-loader.gif">');
				    },  
				    success: function(requestData){
					    var result = requestData;

						if(result == "ok")
						{
							document.getElementById("filaEventoUno" + id).style.display = "none";
							document.getElementById("filaEventoDos" + id).style.display = "none";

							var divMsj = "<div class='alert alert-success'>";
							divMsj = divMsj + "<button class='close' data-dismiss='alert'>×</button>";
							divMsj = divMsj + "Evento ha sido cancelado";
							divMsj = divMsj + "</div>";

							document.getElementById("divMensajeEvento").innerHTML = divMsj;  
						}
				    },  
				    error: function(requestData, strError, strTipoError){          
				    }
				    
					});
	}

    function rechazarInvitacionEvento(){
    	
		var id = document.getElementById("hdnEventoId").value;

		$.ajax(
				{
				async: true,
				type: 'POST',
				url: '<?php echo $this->baseUrl()?>/evento/rechazar-invitacion',
				data: 'id=' + id,	
				dataTypeString: 'text',
				
				beforeSend: function(data){
					  //selectDestino.html('<img src="/imagenes/proyecto/ajax-loader.gif">');
			    },  
			    success: function(requestData){
				    var result = requestData;

					if(result == "ok")
					{
						document.getElementById("rowUnoInvitacion" + id).style.display = "none";
						document.getElementById("rowDosInvitacion" + id).style.display = "none";

						var divMsj = "<div class='alert alert-success'>";
						divMsj = divMsj + "<button class='close' data-dismiss='alert'>×</button>";
						divMsj = divMsj + "Evento ha sidop rechazado";
						divMsj = divMsj + "</div>";

						document.getElementById("divMensajeInvitacion").innerHTML = divMsj;  
					}
			    },  
			    error: function(requestData, strError, strTipoError){          
			    }
			    
				});
	}
  
  
</script>