<?php 
	$aut = Zend_Auth::getInstance();
	$objUsuarioGrupoDao = new Application_Model_UsuarioGrupoDao();
?>
<form action="/grupo/buscar/" method="post" enctype="<?php echo $this->formBuscar->getEnctype(); ?>">

<br><h1> BUSCAR GRUPOS </h1><br>

<table class="span9">
	<tr>
		    <td><?php echo $this->formBuscar->txtBuscar;?> </td>
		    <td><?php echo $this->formBuscar->enviar;?></td>
	</tr>
</table>
</form>

<table>
		<?php
			if (count($this->listaPublicos) > 0)
			{
				foreach ($this->listaPublicos as $item)
			{
		?>	    
		<tr>	
			<td>
		 		<div style='width: 80px;'>
					<a class='thumbnail'  href="<?php echo $this->url(array('controller'=>'muro', 'action'=>'muro-grupo', 'id'=>$item->getId())); ?>">
						<img src="/imagenes/grupos/<?php echo $item->getFoto();?>" >
					</a>
				</div>&nbsp;&nbsp;&nbsp;&nbsp;    
			</td>
			<td>
				<?php echo $item->getNombre(); ?>&nbsp;&nbsp;
			</td>
			<?php if ($objUsuarioGrupoDao->usuarioExisteEnGrupo($item->getId(), $aut->getIdentity()->usu_id) == false) {?>
				<td>
					<a id="btnUnirse<?php echo $item->getId();?>" href="#" onclick="openMyModalUnirseGrupo(<?php echo $item->getId();?>);" class="btn"><i class="icon-user"></i><i class="icon-user"></i> Unirse al Grupo </a>
				</td>
			<?php }?>
		</tr>
		<?php 
				}
			}
			else
			{    	
		?>
		<tr>
			<td>
				No hay resultados para la busqueda
			</td>
		</tr>
		<?php }?>
</table>
<?php echo $this->listaPublicos;?>

<div class="modal hide" id="myModalUnirseGrupo" style="width: 700px;">
    <div class="modal-header">
    <button class="close" data-dismiss="modal">×</button>
    <img src="/imagenes/proyecto/Info.png">&nbsp;<b>Unirse al Grupo</b>
    </div>
    <div class="modal-body">
	    <div id="divUnirseGrupo"></div>
	    ¿Deseas unirte al grupo? <div id="divGrupo"></div> 
	    <input type="hidden" id="hdnIdGrupo">
    </div>
    <div class="modal-footer">
  	    <a href="#" onclick="unirseAlGrupo()" class="btn btn-success" data-dismiss="modal">Unirse</a>
  	    <a href="#" class="btn btn-danger" data-dismiss="modal">Cancelar</a>
    </div>
</div>	

<script type="text/javascript">

	function unirseAlGrupo(){
	
		var idGrupo = document.getElementById("hdnIdGrupo").value;
		
				$.ajax(
						{
						async: true,
						type: 'POST',
						url: '<?php echo $this->baseUrl()?>/grupo/unirse2',
						data: 'idGrupo=' + idGrupo,	
						dataTypeString: 'text',
						
						beforeSend: function(data){
			                //selectDestino.html('<img src="/imagenes/proyecto/ajax-loader.gif">');
					    },  
					    success: function(requestData){  
							    	document.getElementById("btnUnirse"+idGrupo).style.display = "none";
							    	
					    },  
					    error: function(requestData, strError, strTipoError){          
					    }
					    
						});
			
	}
		

	function openMyModalUnirseGrupo(id)
	{
		document.getElementById("hdnIdGrupo").value = id;
		$('#myModalUnirseGrupo').modal('show');		
	}

		
</script>