 
 <br><h1>GRUPO
 <?php 
 	$objGrupoDao = new Application_Model_GrupoDao();
 	$objGrupo = $objGrupoDao->obtenerPorId($this->grupoId);
 	if ($objGrupo->getTipoGrupoId() == "0"){
 		echo "PÚBLICO";
 	}else{
 		echo "PRIVADO";
 	}?>
 </h1><br>
 
  <table class="span9" style="width: 100%">
   		<tr>
   			<td>
				<h2>"<?php echo $objGrupo->getNombre();?>"</h3></h2>
   				<table>
   					<tr>
   						<td valign="top">
							<div class="cont well">
   								<?php  echo $objGrupo->getDescripcion(); ?>
   							</div>
   						</td>
   					</tr>
   				</table>
   			</td>
  		</tr>
  </table>
 
<div class="tabbable span9 well">
    <ul class="nav nav-tabs">
    	<li><a href="#GruposContacto" data-toggle="tab"><img src="/imagenes/proyecto/minuscontacto.png">&nbsp;&nbsp;Contactos del grupo</a></li>
    	<li><a href="#GruposInvitarContactos" data-toggle="tab"><img src="/imagenes/proyecto/addcontacto.png">&nbsp;&nbsp;Invitar contactos</a></li>
    </ul>
    <div class="tab-content">
    	<div class="tab-pane active" id="GruposContacto">
    		<?php echo $this->listaGrupoUsuarios;?>
    		
    		<?php 
				$columna = 0;
				$cantColumna = 3;
				$countCheck = 0;
			?>
				<table width="100%" align="center" class="span9">
					<?php foreach ($this->listaGrupoUsuarios as $usuario){
							if($columna == 0){ 
							   echo "<tr>";
							} 
							echo "<td>";?> 
							<!-- imprimir el objeto -->
								<table align="center">
									<tr>
										<td align="center">
											<?php 
											echo $usuario->getNombre();
											$objUsuarioGrupoDao = new Application_Model_UsuarioGrupoDao();
											$flagEliminado = $objUsuarioGrupoDao->obtenerPorGrupoYUsuario($this->grupoId, $usuario->getId());
												if($flagEliminado == 1)
												{
												    	$flagEliminado = "checked='checked'";
												}
											?>
										</td>
									</tr>
									<tr>
										<td align="center">
												<a class='thumbnail'>
													<img src="<?php echo $this->baseUrl()?>/imagenes/usuarios/icono/<?php echo $usuario->getFoto(); ?>"></img>
												</a>
											<?php 
												$aut = Zend_Auth::getInstance();
												if($usuario->getId() != $aut->getIdentity()->usu_id){ ?>
													<input type="checkbox" <?php echo $flagEliminado; ?> id="cbx<?php echo $usuario->getId();?>" name="cbx<?php echo $usuario->getId();?>" onclick="aEliminar(<?php echo $usuario->getId();?>)">
											<?php 
											} 
											?>
										</td>
									</tr>
								</table>						
							<!-- fin de imprimir el objeto -->
							<?php 
							echo "</td>"; 
							$columna++;
							 if($columna == $cantColumna){
								 echo "</tr>";				
								 $columna = 0;
							 }
						 }
						 echo "</tr>";
					?>
				</table>
				
				<button type="button" class="btn btn-success" onclick="openModalConfirmarEliminar(<?php echo $this->grupoId;?>)">
				<img src="/imagenes/proyecto/papelera.png">&nbsp;&nbsp; Eliminar contactos seleccionados
				</button>
    		
    	</div>
    	<div class="tab-pane" id="GruposInvitarContactos">
    		<?php 
    			echo $this->listaAmigoNoInvitado;
				$columna = 0;
				$cantColumna = 3;
				$countCheck = 0;
			?>
				<table width="100%" align="center">
					<?php foreach ($this->listaAmigoNoInvitado as $usuario){
							if($columna == 0){ 
							   echo "<tr>";
							} 
							echo "<td>";?> 
							<!-- imprimir el objeto -->
								<table align="center">
									<tr>
										<td align="center">
											<?php 
											echo $usuario->getNombre();
											$objUsuarioGrupoDao = new Application_Model_UsuarioGrupoDao();
											$flagInvitado = $objUsuarioGrupoDao->obtenerPorGrupoYUsuario($this->grupoId, $usuario->getId());
												if($flagEliminado == 1)
												{
												    	$flagInvitado = "checked='checked'";
												}
											?>
										</td>
									</tr>
									<tr>
										<td align="center">
											<a class='thumbnail'>
												<img src="<?php echo $this->baseUrl()?>/imagenes/usuarios/icono/<?php echo $usuario->getFoto(); ?>"></img>
											</a>
											<?php 
												$aut = Zend_Auth::getInstance();
												$objInvitacionDao = new Application_Model_InvitacionDao();
												$objInvitacion = $objInvitacionDao->obtenerPorIdActividadUsuario($usuario->getId(), $this->grupoId);
												
												if ($objInvitacion != null)
												{
													if($objInvitacion->getEstado() != 2){ //0;1;3?>
														<?php if($objInvitacion->getEstado() == 3){ ?>
															Invitación Rechazada
														<?php }else{ ?>
															Invitar
														<?php } ?>
														<input type="checkbox" <?php echo $flagInvitado; ?> id="cbx<?php echo $usuario->getId();?>" name="cbx<?php echo $usuario->getId();?>" onclick="aInvitar(<?php echo $usuario->getId();?>)">
												<?php } ?>
												
												<?php 
												if($objInvitacion->getEstado() == 2 ){ //2?>
													Invitación enviada
												<?php } 
												}
												else
												{    
												?>
												Invitar
												<input type="checkbox" <?php echo $flagInvitado; ?> id="cbx<?php echo $usuario->getId();?>" name="cbx<?php echo $usuario->getId();?>" onclick="aInvitar(<?php echo $usuario->getId();?>)">
												<?php }?>
										</td>
									</tr>
								</table>						
							<!-- fin de imprimir el objeto -->
							<?php 
							echo "</td>"; 
							$columna++;
							 if($columna == $cantColumna){
								 echo "</tr>";				
								 $columna = 0;
							 }
						 }
						 echo "</tr>";
					?>
				</table>
				
				<?php 
				
				$objAmigoDao = new Application_Model_AmigoDao();
				$cantidad = $objAmigoDao->obtenerTodosPorUsuarioId($aut->getIdentity()->usu_id);
				
				if (count($cantidad) < 1)
				{
				    echo 'No tienes contactos agregados';
				}
				else{
				?>
					<button type="button" class="btn btn-success" onclick="openModalConfirmarInvitar(<?php echo $this->grupoId;?>)">
					Invitar los contactos seleccionados
					</button>
				<?php }?>
    	</div>
    </div>
 </div>
     	<?php 
    	$countCheck = $objUsuarioGrupoDao->obtenerMarcadosEliminar($this->grupoId);
    	?>
<input type="hidden" id="hdnCountEliminar" value="<?php echo $countCheck;?>">
<div class="modal hide" id="myModalEliminarUsuarioGrupo" style="width: 700px;">
    <div class="modal-header">
    <button class="close" data-dismiss="modal">×</button>
    <h2><img src="/imagenes/proyecto/Info.png">&nbsp;&nbsp;&nbsp;Eliminar Usuarios</h2>
    </div>
    <div class="modal-body">
    	¿Estás seguro de eliminar los usuarios? <div id="divGrupo"></div> 
    </div>
    <div class="modal-footer">
    	<a class="btn btn-success" href="/grupo/eliminar-usuario-grupo/grupoId/<?php echo $this->grupoId;?>">Si, eliminar</a>
  	    <a href="#" class="btn btn-danger" data-dismiss="modal">Cancelar</a>
    </div>
    
</div>	
 
<div class="modal hide" id="myModalEliminarUsuarioGrupoNoSelecionado" style="width: 700px;">
    <div class="modal-header">
    <button class="close" data-dismiss="modal">×</button>
    <h2><img src="/imagenes/proyecto/cruz.png">&nbsp;&nbsp;&nbsp;Eliminar Usuarios</h2>
    </div>
    <div class="modal-body">
    	No hay usuarios seleccionados<div id="divGrupo"></div> 
    </div>
    <div class="modal-footer">
  	    <a href="#" class="btn btn-success" data-dismiss="modal">Aceptar</a>
    </div>
</div>	
 
 <input type="hidden" id="hdnCountInvitar" value="<?php echo $countCheck;?>">
	<div class="modal hide" id="myModalInvitarUsuarioGrupo" style="width: 700px;">
    <div class="modal-header">
    <button class="close" data-dismiss="modal">×</button>
    <h2><img src="/imagenes/proyecto/Info.png">&nbsp;&nbsp;&nbsp;Invitar Usuarios</h2>
    </div>
    <div class="modal-body">
    	¿Esta seguro de Invitar a los usuarios? <div id="divGrupo"></div> 
    </div>
    <div class="modal-footer">
    	<a class="btn btn-success" href="/grupo/invitar-usuario-grupo/grupoId/<?php echo $this->grupoId;?>">Si</a>
  	    <a href="#" class="btn btn-success" data-dismiss="modal">No</a>
    </div>
    
</div>	
 
<div class="modal hide" id="myModalInvitarUsuarioGrupoNoSelecionado" style="width: 700px;">
    <div class="modal-header">
    <button class="close" data-dismiss="modal">×</button>
    <h2><img src="/imagenes/proyecto/Info.png">&nbsp;&nbsp;&nbsp;Invitar Usuarios</h2>
    </div>
    <div class="modal-body">
    	No hay usuarios seleccionados<div id="divGrupo"></div> 
    </div>
    <div class="modal-footer">
  	    <a href="#" class="btn btn-success" data-dismiss="modal">Aceptar</a>
    </div>
</div>	
 
 <script type="text/javascript">
 
 function openModalConfirmarEliminar(idGrupo)
	{
		if (document.getElementById("hdnCountEliminar").value > 0)
		{
			$('#myModalEliminarUsuarioGrupo').modal("show");
		}		
		else
		{
			$('#myModalEliminarUsuarioGrupoNoSelecionado').modal("show");
		}		
	}

 function aEliminar(usuId)
	{
		var cbxUsuario = document.getElementById("cbx" + usuId).checked;
		var check = "";		

		if (cbxUsuario)
		{
			check = 1;
			document.getElementById("hdnCountEliminar").value = document.getElementById("hdnCountEliminar").value + 1;
		}
		else		 
		{
			check = 0;
			document.getElementById("hdnCountEliminar").value = document.getElementById("hdnCountEliminar").value - 1;
		}	

		$.ajax(
				{
				async: true,
				type: 'POST',
				url: '<?php echo $this->baseUrl()?>/grupo/marcar-eliminar',
				data: 'usuarioId='+usuId+'&cbxUsuario='+check+'&grupoId='+<?php echo $this->grupoId;?>,	
				dataTypeString: 'text',
				
				beforeSend: function(data){
					  //selectDestino.html('<img src="/imagenes/proyecto/ajax-loader.gif">');
			    },  
			    success: function(requestData){
				    var result = requestData;

			    },  
			    error: function(requestData, strError, strTipoError){          
			    }
			    
				});
	}

 function openModalConfirmarInvitar(idGrupo)
	{
		if (document.getElementById("hdnCountInvitar").value > 0)
		{
			$('#myModalInvitarUsuarioGrupo').modal("show");
		}		
		else
		{
			$('#myModalInvitarUsuarioGrupoNoSelecionado').modal("show");
		}		
	}

 function aInvitar(usuId)
	{
		var cbxUsuario = document.getElementById("cbx" + usuId).checked;
		var check = "";		

		if (cbxUsuario)
		{
			check = 1;
			document.getElementById("hdnCountInvitar").value = document.getElementById("hdnCountInvitar").value + 1;
		}
		else		 
		{
			check = 0;
			document.getElementById("hdnCountInvitar").value = document.getElementById("hdnCountInvitar").value - 1;
		}	

		$.ajax(
				{
				async: true,
				type: 'POST',
				url: '<?php echo $this->baseUrl()?>/grupo/marcar-invitar',
				data: 'usuarioId='+usuId+'&cbxUsuario='+check+'&grupoId='+<?php echo $this->grupoId;?>,	
				dataTypeString: 'text',
				
				beforeSend: function(data){
					  //selectDestino.html('<img src="/imagenes/proyecto/ajax-loader.gif">');
			    },  
			    success: function(requestData){
				    var result = requestData;

			    },  
			    error: function(requestData, strError, strTipoError){          
			    }
			    
				});
	}
	
 </script>   		