    	 <br><h1> EDITAR GRUPO </h1><br>
    	 
    	<table class="span9">
    		<tr>
    			<td>
    				<form action="/grupo/editar/" method="post" enctype="<?php echo $this->form->getEnctype(); ?>">
						<?php
			                echo $this->form->txtNombre;
							echo $this->form->fileFoto;
							echo $this->form->hdnIdGrupo;
							echo $this->form->txtDescripcion;
							echo $this->form->enviar;
			             ?>
			        </form>
    			</td>
    		</tr>
    	</table>
    	
    	
