 <?php 
 $aut = Zend_Auth::getInstance();

 if($this->successInvitarUsuarios == "ok")
 {
 	$msj = "";
 	$msj .= "<div class='alert alert-success'>";
 	$msj .= "<button class='close' data-dismiss='alert'>×</button>";
 	$msj .=  "<strong><img src='/imagenes/proyecto/ok.png'>&nbsp;&nbsp;</strong>";
 	$msj .= "Los usuarios han sido invitados al Grupo";
 	$msj .= "</div>";
 
 	echo $msj;
 }
 ?>
 <br><h1> GRUPOS </h1><br>
 <a href="#" onclick="openModalGrupo()" class="btn"><img src="/imagenes/proyecto/grupo.png">&nbsp;&nbsp; Crear Grupo </a><br><br>
 <a href="/grupo/buscar" class="btn"><i class="icon-search"></i> Buscar grupo </a><br><br> 
 <?php 
 if($this->successEliminarUsuarios == "ok")
 {
 	$msj = "";
 	$msj .= "<div class='alert alert-success'>";
 	$msj .= "<button class='close' data-dismiss='alert'>×</button>";
 	$msj .=  "<strong><img src='/imagenes/proyecto/ok.png'>&nbsp;&nbsp;</strong>";
 	$msj .= "Los usuarios han sido eliminados del Grupo";
 	$msj .= "</div>";
 
 	echo $msj;
 }
 
if($this->mensaje_ok == "ok"){
 		echo "<div id='divMensajeDejarParticipar'><div class='alert alert-success'><button class='close' data-dismiss='alert'>×</button><strong><img src='/imagenes/proyecto/ok.png'>&nbsp;&nbsp;</strong>Grupo creado exitosamente</div></div>";
 }?>
 
 <div class="tabbable span9 well">
    <ul class="nav nav-tabs">
    	<li><a href="#misGruposParticipo" data-toggle="tab"><img src="/imagenes/proyecto/grupo.png">&nbsp;&nbsp;Mis grupos en que participo</a></li>
    	<li><a href="#misGruposInvitaciones" data-toggle="tab"><img src="/imagenes/proyecto/hoja.png">&nbsp;&nbsp;Invitaciones</a></li>
    </ul>
    <div class="tab-content">
    	<div class="tab-pane active" id="misGruposParticipo">
    		<?php echo $this->listaGrupoUsuario;?>
    		<div id="divMensajeDejarParticipar"></div>
    		<div id="divMensajeEliminar"></div>
    		
    		<?php if(count($this->listaGrupoUsuario) > 0){?>
    		
    		<table>
    			<?php 
		    		foreach ($this->listaGrupoUsuario as $item)
		    		{
    			?>
					<tr id="rowUno<?php echo $item->getId();?>" style="display: block;">
						<td colspan=2>
							<?php echo $item->getNombre();?>
						</td>			
					</tr>
					<tr id="rowDos<?php echo $item->getId();?>" style="display: block;">
						<td>
							<div style='width: 80px;'>
								<a class='thumbnail'  href="<?php echo $this->url(array('controller'=>'muro', 'action'=>'muro-grupo', 'id'=>$item->getId())); ?>">
									<img src="/imagenes/grupos/icono/<?php echo $item->getFoto();?>" >
								</a>
							</div>
						</td>
						<td>
							<?php if ($aut->getIdentity()->usu_id == $item->getUsuId()) {?>
							<a href="<?php echo $this->url(array('controller'=>'grupo', 'action'=>'contactos', 'grupoId'=>$item->getId())); ?>"  class="btn btn-info"> Contactos </a>
							<a href="<?php echo $this->url(array('controller'=>'grupo', 'action'=>'editar', 'grupoId'=>$item->getId())); ?>"  class="btn btn-info"> Editar grupo </a>
							<a class="btn btn-info" onclick="openModalBorrar(<?php echo $item->getId();?>)"> Eliminar grupo </a>
							<?php }
							else 
							{
							?>
							<a class="btn btn-info" onclick="openModalDejarParticipar(<?php echo $item->getId();?>)"> Dejar de participar </a>
							<?php }?>
						</td>			
					</tr>  
				<?php }?>
    		</table>
    		<?php }else{?>
    			No participas de ningún grupo aún..
    		<?php } ?>
    	</div>
    	<div class="tab-pane" id="misGruposInvitaciones">
    		<?php echo $this->listaInvitacionesGrupo;
    		$objGrupoDao = new Application_Model_GrupoDao()
    		
    		?>
    		<div id="divMensajeInvitacion"></div>
    		
    		<?php if(count($this->listaInvitacionesGrupo) > 0){?>
    		<table>
    			<?php 
		    		foreach ($this->listaInvitacionesGrupo as $item)
		    		{
    			?>
					<tr id="rowUnoInvitacion<?php echo $item->getId();?>" style="display: block;">
						<td colspan=2>
							<?php 
								$objGrupo = $objGrupoDao->obtenerPorId($item->getIdActividad());
								echo $objGrupo->getNombre();
							?>
						</td>			
					</tr>
					<tr id="rowDosInvitacion<?php echo $item->getId();?>" style="display: block;">
						<td>
							<div style='width: 80px;'>
								<a class='thumbnail'>
									<img src="/imagenes/grupos/icono/<?php echo $objGrupo->getFoto();?>" >
								</a>
							</div>
						</td>
						<td>
							<a class="btn btn-success" onclick="openModalAceptarInvitacion(<?php echo $item->getId();?>)"><img src="/imagenes/proyecto/ok.png" width="15px;">&nbsp;Aceptar Invitación </a>
							<a class="btn btn-danger" onclick="openModalRechazarInvitacion(<?php echo $item->getId();?>)"><img src="/imagenes/proyecto/cruz.png" width="15px;">&nbsp;Rechazar Invitación </a>
						</td>			
					</tr>  
				<?php }?>
    		</table>
    		
    		<?php }else{?>
    			No tienen ninguna invitación recibida de grupos aún..
    		<?php }?>
    	</div>
    </div>
</div>

<?php 
	$flag = "modal hide";
	if($this->error == "error")
	{
	    $flag = "modal";
	}else{
	    $flag = "modal hide";
	}
?>

<div class="<?php echo $flag;?>" id="myModalGrupo" style="width: 700px;">
    <div class="modal-header">
    <button class="close" onclick="closeModalGrupo()" data-dismiss="modal">×</button>
    <h2><img src="/imagenes/proyecto/grupo.png">&nbsp;&nbsp;Nuevo Grupo</h2>
    </div>
    <div class="modal-body">
    	<form action="/grupo/index/" method="post" enctype="<?php echo $this->form->getEnctype(); ?>">
			<?php
                echo $this->form->txtNombre;
				echo $this->form->fileFoto;
				echo $this->form->txtDescripcion;
				echo $this->form->optPublico;
				echo $this->form->optPrivado;
				echo $this->form->enviar;
             ?>
        </form>
    </div>
</div>	

<div class="modal hide" id="myModalBorrar" style="width: 700px;">
    <div class="modal-header">
    <button class="close" onclick="closeModalBorrar()" data-dismiss="modal">×</button>
    <h2><img src="/imagenes/proyecto/Info.png">&nbsp;&nbsp;&nbsp;Eliminar Grupo</h2>
    </div>
        <div class="modal-body">
    		¿Estás seguro de eliminar el grupo? <div id="divGrupo"></div> 
    	<input type="hidden" id="hdnGrupoId">
	    </div>
	    <div class="modal-footer">
	    	<a href="#" onclick="eliminarGrupo()" class="btn btn-success" data-dismiss="modal">Si, eliminar</a>
	  	    <a href="#" onclick="closeModalBorrar()" class="btn btn-danger" data-dismiss="modal">Cancelar</a>
	    </div>
</div>	

<div class="modal hide" id="myModalAceptarInvitacion" style="width: 700px;">
    <div class="modal-header">
    <button class="close" onclick="closeModalBorrar()" data-dismiss="modal">×</button>
    <h2><img src="/imagenes/proyecto/Info.png">&nbsp;&nbsp;&nbsp;Aceptar Invitación</h2>
    </div>
        <div class="modal-body">
    		¿Deseas aceptar la invitación al grupo? <div id="divGrupo"></div> 
	    	<input type="hidden" id="hdnInvitacionId">
	    </div>
	    <div class="modal-footer">
	    	<a href="#" onclick="aceptarInvitacionGrupo()" class="btn btn-success" data-dismiss="modal">Si, aceptar</a>
	  	    <a href="#" onclick="closeModalAceptarInvitacion()" class="btn btn-danger" data-dismiss="modal">Cancelar</a>
	    </div>
</div>	

<div class="modal hide" id="myModalDejarParticipar" style="width: 700px;">
    <div class="modal-header">
    <button class="close" onclick="closeModalDejarParticipar()" data-dismiss="modal">×</button>
    <h2><img src="/imagenes/proyecto/Info.png">&nbsp;&nbsp;Dejar el Grupo</h2>
    </div>
        <div class="modal-body">
    		¿Estás seguro de dejar de participar en el grupo? <div id="divGrupo"></div> 
    	<input type="hidden" id="hdnGrupoId">
	    </div>
	    <div class="modal-footer">
	    	<a href="#" onclick="dejarParticiparGrupo()" class="btn btn-success" data-dismiss="modal">Si, dejar</a>
	  	    <a href="#" onclick="closeModalDejarParticipar()" class="btn btn-danger" data-dismiss="modal">Cancelar</a>
	    </div>
</div>	

<div class="modal hide" id="myModalRechazarInvitacion" style="width: 700px;">
    <div class="modal-header">
    <button class="close" onclick="closeModalBorrar()" data-dismiss="modal">×</button>
    <h2><img src="/imagenes/proyecto/Info.png">&nbsp;&nbsp;Rechazar Invitacion</h2>
    </div>
        <div class="modal-body">
    		¿Deseas rechazar la invitacion al grupo? <div id="divGrupo"></div> 
	    	<input type="hidden" id="hdnInvitacionId">
	    </div>
	    <div class="modal-footer">
	    	<a href="#" onclick="rechazarInvitacionGrupo()" class="btn btn-success" data-dismiss="modal">Si, rechazar</a>
	  	    <a href="#" onclick="closeModalRechazarInvitacion()" class="btn btn-danger" data-dismiss="modal">Cancelar</a>
	    </div>
</div>	

<script type="text/javascript">
	function openModalGrupo()
	{
		$('#myModalGrupo').modal("show");	
	}

	function closeModalGrupo()
	{
		$('#myModalGrupo').modal();	
	}

	function openModalBorrar(idGrupo)
	{
		document.getElementById("hdnGrupoId").value = idGrupo;
		$('#myModalBorrar').modal("show");	
	}

	function openModalDejarParticipar(idGrupo)
	{
		document.getElementById("hdnGrupoId").value = idGrupo;
		$('#myModalDejarParticipar').modal("show");	
	}
	
	function openModalAceptarInvitacion(idInvitacion)
	{
		document.getElementById("hdnInvitacionId").value = idInvitacion;
		$('#myModalAceptarInvitacion').modal("show");	
	}

	function openModalRechazarInvitacion(idInvitacion)
	{
		document.getElementById("hdnInvitacionId").value = idInvitacion;
		$('#myModalRechazarInvitacion').modal("show");	
	}
	
	function closeModalBorrar()
	{
		$('#myModalBorrar').modal();	
	}

	function closeModalDejarParticipar()
	{
		$('#myModalDejarParticipar').modal();	
	}

	function closeModalAceptarInvitacion()
	{
		$('#myModalAceptarInvitacion').modal();	
	}

	function closeModalRechazarInvitacion()
	{
		$('#myModalRechazarInvitacion').modal();	
	}
	
	function eliminarGrupo(){

		var grupoId = document.getElementById("hdnGrupoId").value;

			$.ajax(
						{
						async: true,
						type: 'POST',
						url: '<?php echo $this->baseUrl()?>/grupo/eliminar',
						data: 'grupoId=' + grupoId,	
						dataTypeString: 'text',
						
						beforeSend: function(data){
							  //selectDestino.html('<img src="/imagenes/proyecto/ajax-loader.gif">');
					    },  
					    success: function(requestData){
						    var result = requestData;

							if(result == "ok")
							{
								document.getElementById("rowUno" + grupoId).style.display = "none";
								document.getElementById("rowDos" + grupoId).style.display = "none";

								var divMsj = "<div class='alert alert-success'>";
								divMsj = divMsj + "<button class='close' data-dismiss='alert'>×</button>";
								divMsj = divMsj + "<strong><img src='/imagenes/proyecto/ok.png'>&nbsp;&nbsp;</strong>";
								divMsj = divMsj + "Se ha eliminado el grupo correctamente";
								divMsj = divMsj + "</div>";

								document.getElementById("divMensajeEliminar").innerHTML = divMsj;  
							}
						      
					    },  
					    error: function(requestData, strError, strTipoError){          
					    }
					    
						});
	}
	
	function aceptarInvitacionGrupo(){

		var invitacionId = document.getElementById("hdnInvitacionId").value;

			$.ajax(
						{
						async: true,
						type: 'POST',
						url: '<?php echo $this->baseUrl()?>/grupo/aceptar-invitacion',
						data: 'invitacionId=' + invitacionId,	
						dataTypeString: 'text',
						
						beforeSend: function(data){
							  //selectDestino.html('<img src="/imagenes/proyecto/ajax-loader.gif">');
					    },  
					    success: function(requestData){
						    var result = requestData;

							if(result == "ok")
							{
								document.getElementById("rowUnoInvitacion" + invitacionId).style.display = "none";
								document.getElementById("rowDosInvitacion" + invitacionId).style.display = "none";

								var divMsj = "<div class='alert alert-success'>";
								divMsj = divMsj + "<button class='close' data-dismiss='alert'>×</button>";
								divMsj = divMsj + "<strong><img src='/imagenes/proyecto/ok.png'>&nbsp;&nbsp;</strong>";
								divMsj = divMsj + "Ahora eres parte del grupo.";
								divMsj = divMsj + "</div>";

								document.getElementById("divMensajeInvitacion").innerHTML = divMsj;  
							}
						      
					    },  
					    error: function(requestData, strError, strTipoError){          
					    }
					    
						});
	}


	function rechazarInvitacionGrupo(){

		var invitacionId = document.getElementById("hdnInvitacionId").value;

			$.ajax(
						{
						async: true,
						type: 'POST',
						url: '<?php echo $this->baseUrl()?>/grupo/rechazar-invitacion',
						data: 'invitacionId=' + invitacionId,	
						dataTypeString: 'text',
						
						beforeSend: function(data){
							  //selectDestino.html('<img src="/imagenes/proyecto/ajax-loader.gif">');
					    },  
					    success: function(requestData){
						    var result = requestData;

							if(result == "ok")
							{
								document.getElementById("rowUnoInvitacion" + invitacionId).style.display = "none";
								document.getElementById("rowDosInvitacion" + invitacionId).style.display = "none";

								var divMsj = "<div class='alert alert-success'>";
								divMsj = divMsj + "<button class='close' data-dismiss='alert'>×</button>";
								divMsj = divMsj + "<strong><img src='/imagenes/proyecto/ok.png'>&nbsp;&nbsp;</strong>";
								divMsj = divMsj + "Has rechazado la invitacion del grupo";
								divMsj = divMsj + "</div>";

								document.getElementById("divMensajeInvitacion").innerHTML = divMsj;  
							}
						      
					    },  
					    error: function(requestData, strError, strTipoError){          
					    }
					    
						});
	}
	
	function dejarParticiparGrupo(){

		var grupoId = document.getElementById("hdnGrupoId").value;

			$.ajax(
						{
						async: true,
						type: 'POST',
						url: '<?php echo $this->baseUrl()?>/grupo/dejar-participar',
						data: 'grupoId=' + grupoId,	
						dataTypeString: 'text',
						
						beforeSend: function(data){
							  //selectDestino.html('<img src="/imagenes/proyecto/ajax-loader.gif">');
					    },  
					    success: function(requestData){
						    var result = requestData;

							if(result == "ok")
							{
								document.getElementById("rowUno" + grupoId).style.display = "none";
								document.getElementById("rowDos" + grupoId).style.display = "none";

								var divMsj = "<div class='alert alert-success'>";
								divMsj = divMsj + "<button class='close' data-dismiss='alert'>×</button>";
								divMsj = divMsj + "<strong><img src='/imagenes/proyecto/ok.png'>&nbsp;&nbsp;</strong>";
								divMsj = divMsj + "Has dejado de participar en el grupo.";
								divMsj = divMsj + "</div>";

								document.getElementById("divMensajeDejarParticipar").innerHTML = divMsj; 
							}
						      
					    },  
					    error: function(requestData, strError, strTipoError){          
					    }
					    
						});
	}


	function textCounter(textarea, counterID) 
	{
		var maxLen = document.getElementById("maximoPost").value;
		document.getElementById("count_display").style.display = "block";
		
		cnt = document.getElementById(counterID);
		if (textarea.value.length > (maxLen))
		{
			textarea.value = textarea.value.substring(0,maxLen);
		}
		cnt.innerHTML = (maxLen - textarea.value.length) + ' Caracteres Restantes';
	}
</script>
