 <?php 
 $aut = Zend_Auth::getInstance();
 
 ?>
 
 <a href="#" onclick="openModalGrupo()">Crear Grupo</a>
 
 
 <div class="tabbable">
    <ul class="nav nav-tabs">
    	<li><a href="#misGruposParticipo" data-toggle="tab">Mis grupos en que participo</a></li>
    	<li><a href="#misGruposInvitaciones" data-toggle="tab">Invitaciones</a></li>
    </ul>
    <div class="tab-content">
    	<div class="tab-pane active" id="misGruposParticipo">
    		<?php echo $this->listaGrupoUsuario;?>
    		<table>
    			<?php 
		    		foreach ($this->listaGrupoUsuario as $item)
		    		{
    			?>
					<tr id="rowUno<?php echo $item->getId();?>" style="display: block;">
						<td colspan=2>
							<?php echo $item->getNombre();?>
						</td>			
					</tr>
					<tr id="rowDos<?php echo $item->getId();?>" style="display: block;">
						<td>
							<div style='width: 80px;'>
								<a class='thumbnail'>
									<img src="/imagenes/grupos/<?php echo $item->getFoto();?>" >
								</a>
							</div>
						</td>
						<td>
							<?php if ($aut->getIdentity()->usu_id == $item->getUsuId()) {?>
							<a href="<?php echo $this->url(array('controller'=>'grupo', 'action'=>'contactos', 'grupoId'=>$item->getId())); ?>"  class="btn btn-info"> Contactos </a>
							<a class="btn btn-info"> Editar grupo </a>
							<a class="btn btn-info" onclick="openModalBorrar(<?php echo $item->getId();?>)"> Borrar grupo </a>
							<?php }?>
							<a class="btn btn-info"> Ver grupo </a>
						</td>			
					</tr>  
				<?php }?>
    		</table>
    	</div>
    	<div class="tab-pane" id="misGruposInvitaciones">
    		<?php echo $this->listaInvitacionesGrupo;
    		$objGrupoDao = new Application_Model_GrupoDao()
    		
    		?>
    		<div id="divMensajeInvitacion"></div>
    		<table>
    			<?php 
		    		foreach ($this->listaInvitacionesGrupo as $item)
		    		{
    			?>
					<tr id="rowUnoInvitacion<?php echo $item->getId();?>" style="display: block;">
						<td colspan=2>
							<?php 
								$objGrupo = $objGrupoDao->obtenerPorId($item->getIdActividad());
								echo $objGrupo->getNombre();
							?>
						</td>			
					</tr>
					<tr id="rowDosInvitacion<?php echo $item->getId();?>" style="display: block;">
						<td>
							<div style='width: 80px;'>
								<a class='thumbnail'>
									<img src="/imagenes/grupos/<?php echo $objGrupo->getFoto();?>" >
								</a>
							</div>
						</td>
						<td>
							<a class="btn btn-info" onclick="openModalAceptarInvitacion(<?php echo $item->getId();?>)"> Aceptar invitacion </a>
							<a class="btn btn-info" onclick="openModalRechazarInvitacion(<?php echo $item->getId();?>)"> Rechazar invitacion </a>
						</td>			
					</tr>  
				<?php }?>
    		</table>
    	</div>
    </div>
</div>

<?php 
	$flag = "modal hide";
	if($this->error == "error")
	{
	    $flag = "modal";
	}else{
	    $flag = "modal hide";
	}
?>

<div class="<?php echo $flag;?>" id="myModalGrupo" style="width: 700px;">
    <div class="modal-header">
    <button class="close" onclick="closeModalGrupo()" data-dismiss="modal">×</button>
    		<h3>Crear Grupo</h3>
    </div>
    <div class="modal-body">
    	<form action="/grupo/index/" method="post" enctype="<?php echo $this->form->getEnctype(); ?>">
			<?php
                echo $this->form->txtNombre;
				echo $this->form->fileFoto;
			?>	
				<textarea id="txtDescripcion" name="txtDescripcion" onKeyDown="ValidarCaracteres(this, 499);"></textarea>
			<?php 	
				echo $this->form->optPublico;
				echo $this->form->optPrivado;
				echo $this->form->enviar;
             ?>
             
        </form>
    </div>
</div>	


<div class="modal hide" id="myModalBorrar" style="width: 700px;">
    <div class="modal-header">
    <button class="close" onclick="closeModalBorrar()" data-dismiss="modal">×</button>
    	Eliminar grupo
    </div>
        <div class="modal-body">
    		¿Estás seguro de eliminar el grupo? <div id="divGrupo"></div> 
    	<input type="hidden" id="hdnGrupoId">
	    </div>
	    <div class="modal-footer">
	    	<a href="#" onclick="eliminarGrupo()" class="btn btn-success" data-dismiss="modal">Eliminar</a>
	  	    <a href="#" onclick="closeModalBorrar()" class="btn btn-success" data-dismiss="modal">No</a>
	    </div>
</div>	

<div class="modal hide" id="myModalAceptarInvitacion" style="width: 700px;">
    <div class="modal-header">
    <button class="close" onclick="closeModalBorrar()" data-dismiss="modal">×</button>
    	Aceptar invitacion
    </div>
        <div class="modal-body">
    		¿Deseas aceptar la invitacion al grupo? <div id="divGrupo"></div> 
	    	<input type="hidden" id="hdnInvitacionId">
	    </div>
	    <div class="modal-footer">
	    	<a href="#" onclick="aceptarInvitacionGrupo()" class="btn btn-success" data-dismiss="modal">Aceptar</a>
	  	    <a href="#" onclick="closeModalAceptarInvitacion()" class="btn btn-success" data-dismiss="modal">Cancelar</a>
	    </div>
</div>	

<div class="modal hide" id="myModalRechazarInvitacion" style="width: 700px;">
    <div class="modal-header">
    <button class="close" onclick="closeModalBorrar()" data-dismiss="modal">×</button>
    	Rechazar invitacion
    </div>
        <div class="modal-body">
    		¿Deseas rechazar la invitacion al grupo? <div id="divGrupo"></div> 
	    	<input type="hidden" id="hdnInvitacionId">
	    </div>
	    <div class="modal-footer">
	    	<a href="#" onclick="rechazarInvitacionGrupo()" class="btn btn-success" data-dismiss="modal">Aceptar</a>
	  	    <a href="#" onclick="closeModalRechazarInvitacion()" class="btn btn-success" data-dismiss="modal">Cancelar</a>
	    </div>
</div>	


<script type="text/javascript">
	function openModalGrupo()
	{
		$('#myModalGrupo').modal("show");	
	}

	function closeModalGrupo()
	{
		$('#myModalGrupo').modal();	
	}

	function openModalBorrar(idGrupo)
	{
		document.getElementById("hdnGrupoId").value = idGrupo;
		$('#myModalBorrar').modal("show");	
	}

	function openModalAceptarInvitacion(idInvitacion)
	{
		document.getElementById("hdnInvitacionId").value = idInvitacion;
		$('#myModalAceptarInvitacion').modal("show");	
	}

	function openModalRechazarInvitacion(idInvitacion)
	{
		document.getElementById("hdnInvitacionId").value = idInvitacion;
		$('#myModalRechazarInvitacion').modal("show");	
	}
	
	function closeModalBorrar()
	{
		$('#myModalBorrar').modal();	
	}

	function closeModalAceptarInvitacion()
	{
		$('#myModalAceptarInvitacion').modal();	
	}

	function closeModalRechazarInvitacion()
	{
		$('#myModalRechazarInvitacion').modal();	
	}
	
	function eliminarGrupo(){

		var grupoId = document.getElementById("hdnGrupoId").value;

			$.ajax(
						{
						async: true,
						type: 'POST',
						url: '<?php echo $this->baseUrl()?>/grupo/eliminar',
						data: 'grupoId=' + grupoId,	
						dataTypeString: 'text',
						
						beforeSend: function(data){
							  //selectDestino.html('<img src="/imagenes/proyecto/ajax-loader.gif">');
					    },  
					    success: function(requestData){
						    var result = requestData;

							if(result == "ok")
							{
								document.getElementById("rowUno" + grupoId).style.display = "none";
								document.getElementById("rowDos" + grupoId).style.display = "none";
							}
						      
					    },  
					    error: function(requestData, strError, strTipoError){          
					    }
					    
						});
	}
	
	function aceptarInvitacionGrupo(){

		var invitacionId = document.getElementById("hdnInvitacionId").value;

			$.ajax(
						{
						async: true,
						type: 'POST',
						url: '<?php echo $this->baseUrl()?>/grupo/aceptar-invitacion',
						data: 'invitacionId=' + invitacionId,	
						dataTypeString: 'text',
						
						beforeSend: function(data){
							  //selectDestino.html('<img src="/imagenes/proyecto/ajax-loader.gif">');
					    },  
					    success: function(requestData){
						    var result = requestData;

							if(result == "ok")
							{
								document.getElementById("rowUnoInvitacion" + invitacionId).style.display = "none";
								document.getElementById("rowDosInvitacion" + invitacionId).style.display = "none";

								var divMsj = "<div class='alert alert-success'>";
								divMsj = divMsj + "<button class='close' data-dismiss='alert'>×</button>";
								divMsj = divMsj + "<strong>Éxito!</strong> Ahora eres parte del grupo !!";
								divMsj = divMsj + "</div>";

								document.getElementById("divMensajeInvitacion").innerHTML = divMsj;  
							}
						      
					    },  
					    error: function(requestData, strError, strTipoError){          
					    }
					    
						});
	}


	function rechazarInvitacionGrupo(){

		var invitacionId = document.getElementById("hdnInvitacionId").value;

			$.ajax(
						{
						async: true,
						type: 'POST',
						url: '<?php echo $this->baseUrl()?>/grupo/rechazar-invitacion',
						data: 'invitacionId=' + invitacionId,	
						dataTypeString: 'text',
						
						beforeSend: function(data){
							  //selectDestino.html('<img src="/imagenes/proyecto/ajax-loader.gif">');
					    },  
					    success: function(requestData){
						    var result = requestData;

							if(result == "ok")
							{
								document.getElementById("rowUnoInvitacion" + invitacionId).style.display = "none";
								document.getElementById("rowDosInvitacion" + invitacionId).style.display = "none";

								var divMsj = "<div class='alert alert-success'>";
								divMsj = divMsj + "<button class='close' data-dismiss='alert'>×</button>";
								divMsj = divMsj + "<strong>Éxito</strong> Has rechazado la invitacion del grupo";
								divMsj = divMsj + "</div>";

								document.getElementById("divMensajeInvitacion").innerHTML = divMsj;  
							}
						      
					    },  
					    error: function(requestData, strError, strTipoError){          
					    }
					    
						});
	}
	
	
	function textCounter(textarea, counterID) 
	{
		var maxLen = document.getElementById("maximoPost").value;
		document.getElementById("count_display").style.display = "block";
		
		cnt = document.getElementById(counterID);
		if (textarea.value.length > (maxLen))
		{
			textarea.value = textarea.value.substring(0,maxLen);
		}
		cnt.innerHTML = (maxLen - textarea.value.length) + ' Caracteres Restantes';
	}
</script>
