<?php 
$objPublicacionDao = new Application_Model_PublicacionDao();
?>
<table>
  <tr>
    <th colspan="2" >Notificaciones</th>
  </tr>
  <tr>
  	<td><br></td>
  </tr>
	<?php 
		foreach ($this->listaNotificaciones as $item)
		{  
			if ($item->getVista() == 0)
			{    
	?>
				  <tr class="alert alert-success">
				    <td><?php echo $item->getTexto();?></td>
				  </tr>
				  <tr>
				    <td>
				    	<h5><?php echo $objPublicacionDao->calcularTiempoTranscurrido($item->getFecha());?></h5>
				    	<?php 
			    			$objTipoNotificacionDao = new Application_Model_TipoNotificacionDao();
			    			$objTipoNotificacion = $objTipoNotificacionDao->obtenerPorId($item->getTipoNotificacionId());
			    		?>
			    		<a href="<?php echo $objTipoNotificacion->getUrl();?>" >Ver notificación</a>
				    <hr>
				    </td>

  	<?php 
			}
			else
			{
	?>
				<tr>
			    	<td><?php echo $item->getTexto();?></td>
			  	</tr>
			  	<tr>
			    	<td>
			    		<h5><?php echo $objPublicacionDao->calcularTiempoTranscurrido($item->getFecha());?></h5>
			    		<?php 
			    			$objTipoNotificacionDao = new Application_Model_TipoNotificacionDao();
			    			$objTipoNotificacion = $objTipoNotificacionDao->obtenerPorId($item->getTipoNotificacionId());
			    		?>
			    		
			    		<a href="<?php echo $objTipoNotificacion->getUrl();?>" >Ver notificación</a>
			    		<hr>
			    	</td>
			  	</tr>
	<?php 
			}
		}
	?>
</table>

<?php
	$aut = Zend_Auth::getInstance();
	$objNotificacionDao = new Application_Model_NotificacionDao();
	
	echo $this->listaNotificaciones;
	$objNotificacionDao->marcarComoLeido($aut->getIdentity()->usu_id);
?>
