<?php 
$objPublicacionDao = new Application_Model_PublicacionDao();
?>

 <br><h1> NOTIFICACIONES </h1><br>

<?php if(count($this->listaNotificaciones) > 0){?>
<table class="span9">
<?php 
	foreach ($this->listaNotificaciones as $item)
	{  
?>
  <tr>
    <td><?php echo $item->getTexto();?></td>
  </tr>
  <tr>
    <td><h5><?php echo $objPublicacionDao->calcularTiempoTranscurrido($item->getFecha());?></h5><hr></td>
  </tr>
  <?php }?>
</table>
<?php }else{?>
	No tienes notificaciones aún..
<?php }?>
<?php
echo $this->listaNotificaciones;
?>
