<!doctype html>
<html xmlns:fb="http://www.facebook.com/2008/fbml">
  <head>
    <style>
      body {
        font-family: 'Lucida Grande', Verdana, Arial, sans-serif;
      }
      h1 a {
        text-decoration: none;
        color: #3b5998;
      }
      h1 a:hover {
        text-decoration: underline;
      }
    </style>
  </head>
  <body>
    <?php 
    	if ($this->user)
    	{  
	       	$now   = new DateTime;
		    $ch = curl_init('https://graph.facebook.com/oauth/access_token');
		    $token = $_SESSION["fb_124399157694592_access_token"]; 
		    $post = 'client_id=124399157694592&client_secret=8c0658db1a7873a56c3551a2ee13464b&grant_type=fb_exchange_token&fb_exchange_token='.$token;
		    curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
		    curl_setopt ($ch, CURLOPT_POST, 1);
		    curl_setopt ($ch, CURLOPT_POSTFIELDS, $post);
		    $resultado = curl_exec ($ch);
		    parse_str($resultado);
	    
		    $objIntegracionDao = new Application_Model_IntegracionDao();
		    $objIntegracion = new Application_Model_Integracion();
		    $objIntegracion->setToken($access_token);
		    $objIntegracion->setFechaPermiso($now->format( 'Y-m-d' ));
		    $aut = Zend_Auth::getInstance();
		    $objIntegracion->setUsuarioId($aut->getIdentity()->usu_id);
		    $objIntegracion->setRedId("1");
		    $objIntegracionDao->guardar($objIntegracion);
		    curl_close ($ch);
    	}      
      else 
      {
          	echo "<div>";
		    echo '<a href='.$this->link.' class="btn btn" >Integrar con Facebook</a>';
		    echo "</div>";
      }?>

    <?php if ($this->user): ?>
      <h3>Sincronizacion con Facebook exitosa</h3>
      <br>
      <h3>Para ver tu perfil integrado con Facebook tienes que ingresar nuevamente.</h3>
    <?php endif ?>
      <br>
      
      <img src="/imagenes/proyecto/int_fb.png">
    	
  </body>
</html>