<script type="text/javascript">
   function show_login_status(network, status)
   {
    if (status)
    {
     document.getElementById("twitter").innerHTML="Estas logueado con Twitter";
    }else{
     document.getElementById("twitter").innerHTML="No estas logueado con Twitter";
    }
   }
 </script>
  
<img style="display:none;" src="https://twitter.com/login?redirect_after_login=%2Fimages%2Fspinner.gif" onload="show_login_status('Twitter', true)" onerror="show_login_status('Twitter', false)" />
<div id="twitter"></div>
<div id="fb-root"></div>


 <script>
 window.fbAsyncInit = function(){
  FB.init({ appId:'312220765516835', status:true,  cookie:true, xfbml:true});
  FB.getLoginStatus(function(response){
   if (response.status != "unknown")
   {
    document.getElementById("fb-root").innerHTML="Estas logueado con Facebook";
   }else{
    document.getElementById("fb-root").innerHTML="No estas logueado con Facebook";
   }
  });
 };
 // Load the SDK Asynchronously
 (function(d){
  var js, id = 'facebook-jssdk'; if (d.getElementById(id)) {return;}
  js = d.createElement('script'); js.id = id; js.async = true;
  js.src = "http://connect.facebook.net/en_US/all.js";
  d.getElementsByTagName('head')[0].appendChild(js);
 }(document));
</script>

<?php 
	$aut = Zend_Auth::getInstance();
	$objIntegracionDao = new Application_Model_IntegracionDao();
	$objFacebook = $objIntegracionDao->obtenerLlavesIntegracion($aut->getIdentity()->usu_id, 1);
	$objTwitter = $objIntegracionDao->obtenerLlavesIntegracion($aut->getIdentity()->usu_id, 2);
	$objLinkedin = $objIntegracionDao->obtenerLlavesIntegracion($aut->getIdentity()->usu_id, 3);
	$objIntegracionDao = null;
?>

<?php if ($objFacebook == null){?>
	<a href="<?php echo $this->url(array('controller'=>'integracion','action'=>'facebook'));?>">Integrar con Facebook</a><br>
<?php }else{ ?>
	<a href="<?php echo $this->url(array('controller'=>'integracion','action'=>'quitar-facebook'));?>">Quitar Facebook</a><br>
<?php } ?>

<?php if ($objTwitter == null){?>
	<a href="<?php echo $this->url(array('controller'=>'integracion','action'=>'twitter'));?>">Integrar con Twitter</a><br>
<?php }else{ ?>
	<a href="<?php echo $this->url(array('controller'=>'integracion','action'=>'quitar-twitter'));?>">Quitar Twitter</a><br>
<?php } ?>

<?php if ($objLinkedin == null){?>
	<a href="<?php echo $this->url(array('controller'=>'integracion','action'=>'linkedin'));?>">Integrar con LinkedIn</a><br>
<?php }else{ ?>
	<a href="<?php echo $this->url(array('controller'=>'integracion','action'=>'quitar-linkedin'));?>">Quitar LinkedIn</a><br>
<?php } ?>