<?php 
	$aut = Zend_Auth::getInstance();
	$objIntegracionDao = new Application_Model_IntegracionDao();
	$objFacebook = $objIntegracionDao->obtenerLlavesIntegracion($aut->getIdentity()->usu_id, 1);
	$objTwitter = $objIntegracionDao->obtenerLlavesIntegracion($aut->getIdentity()->usu_id, 2);
	$objLinkedin = $objIntegracionDao->obtenerLlavesIntegracion($aut->getIdentity()->usu_id, 3);
	$objIntegracionDao = null;
?>

<?php if ($objFacebook == null){?>
	<a href="<?php echo $this->url(array('controller'=>'integracion','action'=>'facebook'));?>">Integrar con Facebook</a><br>
<?php }else{ ?>
	<a href="<?php echo $this->url(array('controller'=>'integracion','action'=>'quitar-facebook'));?>">Quitar Facebook</a><br>
<?php } ?>

<?php if ($objTwitter == null){?>
	<a href="<?php echo $this->url(array('controller'=>'integracion','action'=>'twitter'));?>">Integrar con Twitter</a><br>
<?php }else{ ?>
	<a href="<?php echo $this->url(array('controller'=>'integracion','action'=>'quitar-twitter'));?>">Quitar Twitter</a><br>
<?php } ?>

<?php if ($objLinkedin == null){?>
	<a href="<?php echo $this->url(array('controller'=>'integracion','action'=>'linkedin'));?>">Integrar con LinkedIn</a><br>
<?php }else{ ?>
	<a href="<?php echo $this->url(array('controller'=>'integracion','action'=>'quitar-linkedin'));?>">Quitar LinkedIn</a><br>
<?php } ?>