<a href="<?php echo $this->url(array('controller'=>'integracion','action'=>'facebook'));?>">Integrar con Facebook</a><BR>
<a href="<?php echo $this->url(array('controller'=>'integracion','action'=>'twitter'));?>">Integrar con Twitter</a><BR>
<a href="<?php echo $this->url(array('controller'=>'integracion','action'=>'linkedin'));?>">Integrar con LinkedIn</a><BR>
-------------------------------------- <br>
<a href="<?php echo $this->url(array('controller'=>'integracion','action'=>'publicar-twitter'));?>">Publicar en Twitter</a><BR>
<a href="<?php echo $this->url(array('controller'=>'integracion','action'=>'publicar-linkedin'));?>">Publicar en Linkedin</a><BR>
<a href="<?php echo $this->url(array('controller'=>'integracion','action'=>'publicar-facebook'));?>">Publicar en Facebook</a><BR>