<!doctype html>
<html xmlns:fb="http://www.facebook.com/2008/fbml">
  <head>
    <style>
      body {
        font-family: 'Lucida Grande', Verdana, Arial, sans-serif;
      }
      h1 a {
        text-decoration: none;
        color: #3b5998;
      }
      h1 a:hover {
        text-decoration: underline;
      }
    </style>
  </head>
  <body>
  	<h3>Integración con LinkedIn</h3>
  	<br>
    <h3>Para ver tu perfil integrado con LinkedIn tienes que ingresar nuevamente.</h3><br>
    
    <img src="/imagenes/proyecto/int_in.png">
    
  </body>
</html>  