<!doctype html>
<html xmlns:fb="http://www.facebook.com/2008/fbml">
  <head>
    <style>
      body {
        font-family: 'Lucida Grande', Verdana, Arial, sans-serif;
      }
      h1 a {
        text-decoration: none;
        color: #3b5998;
      }
      h1 a:hover {
        text-decoration: underline;
      }
    </style>
  </head>
   <body>
  	<h3><?php echo $this->mensajeTwitter; ?></h3>
  	<br><h1>TWITTER</h1><br>
  	<h4>Para ver tu perfil integrado con Twitter tienes que ingresar nuevamente.</h4>
  	<br>
 	¡Intégrate con Twitter, unas de las Redes Sociales más importante, <br> de forma segura y confiable y podrás compartir tus  publicaciones desde nuestra Red Social CIISA hacia Twitter¡
    <br><br>
    
    <img src="/imagenes/proyecto/int_tt.png"><br><br>
    
  </body>
</html>  