<?php 
	$objUsuarioDao2 = new Application_Model_UsuarioDao();
	$objTipPublicacion = new Application_Model_TipoPublicacionDao();
?>
<center><h1>Muro</h1></center>
<?php if(count($this->listaPublicaciones) > 0){ ?>
	<?php foreach ($this->listaPublicaciones as $publicacion){?>
			<div id="publicacion<?php echo $publicacion->getId();?>">
				<table>
					<caption class="label label-success">Categoría:  <?php echo $objTipPublicacion->obtenerPorId($publicacion->getTipoId())->getNombre();?>  </caption>
					<tr>
						<td rowspan="3" valign="top">
							<div style='width: 100px;'>
								<a class="thumbnail">
	      							<img alt="" src="<?php echo $this->baseUrl()?>/imagenes/usuarios/<?php echo $objUsuarioDao2->obtenerPorId($publicacion->getUsuarioId())->getFoto();?>">
         						</a>
         					</div>
						</td>
						<td>
							<h3 style="width: 800px;"><?php echo $publicacion->getTexto();?></h3>
							<input type="hidden" id="hdnTextoPublicacion<?php echo $publicacion->getId();?>" value="<?php echo $publicacion->getTexto();?>">
							
							
							<!-- aquí se muestra la información de la publicación según... el tipo de publicación -->
							<?php 
							if($publicacion->getTipoId() == 1)
							{?>
							    txt
							<?php 
							}elseif($publicacion->getTipoId() == 2){ ?>
								<div style='width: 200px;'>
									<a class="thumbnail">
		      							<img src="<?php echo $this->baseUrl()?>/imagenes/fotos/<?php echo $publicacion->getFoto();?>" onclick="verFoto('<?php echo $publicacion->getTexto();?>','<?php echo $publicacion->getFoto();?>')">
	         						</a>
         						</div>    
							<?php 
							}elseif($publicacion->getTipoId() == 3){ ?>
								video    
							<?php 
							}elseif($publicacion->getTipoId() == 4){ ?>
								eve    
							<?php 
							}elseif($publicacion->getTipoId() == 5){ ?>
								grp    
							<?php 
							}elseif($publicacion->getTipoId() == 6){ ?>
								ofe    
							<?php 
							} 
							?>
						</td>
					</tr>
					<tr>
						<td>
							<?php 
								$objUsuarioDao = new Application_Model_UsuarioDao();
								$objComentarioDao = new Application_Model_ComentarioDao();
								$objIntegracionDao = new Application_Model_IntegracionDao();
								
								$aut = Zend_Auth::getInstance();
								$tieneFacebook = $objIntegracionDao->obtenerLlavesIntegracion($aut->getIdentity()->usu_id, 1);
								$tieneTwitter = $objIntegracionDao->obtenerLlavesIntegracion($aut->getIdentity()->usu_id, 2);
								$tieneLinkedin = $objIntegracionDao->obtenerLlavesIntegracion($aut->getIdentity()->usu_id, 3);
								$objIntegracionDao = null;
								
								$listaComentarios = $objComentarioDao->obtenerPorPublicacionId($publicacion->getId());?>
							<div id="divComentariosPublicacion<?php echo $publicacion->getId();?>">
							<?php if(count($listaComentarios) > 0){
								    foreach ($listaComentarios as $comentario){?>
								    	<table>
								    		<tr>
								    			<td valign="top">
								    				<?php $objUsuario = $objUsuarioDao->obtenerPorId($comentario->getUsuarioId());?>
								    				<div style='width: 50px;'>
														<a class="thumbnail">
							      							<img src="<?php echo $this->baseUrl()?>/imagenes/usuarios/<?php echo $objUsuario->getFoto();?>"></a>
						         					</div>
								    			</td>
								    			<td valign="top">
								    				<p class="label"><?php echo $objUsuario->getNombre(); ?></p>
								    				<p><?php echo $comentario->getTexto();?></p>
								    				<p><?php echo $comentario->getFecha();?></p>
								    			</td>
								    		</tr>
								    	</table>
							  <?php } ?>
							  comentarios: <span class="badge badge-info"><?php echo count($listaComentarios);?></span>
						  <?php } ?>
						  </div>
						</td>
					</tr>
					<tr>
						<td>
							<table>
								<tr>
									<td>
										<button class="btn btn-success">Ver publicación</button>
										<input type="text" id="txtComentario<?php echo $publicacion->getId();?>" placeholder="Escribe algo aquí..." class="span3">
										<button class="btn btn-inverse" onclick="comentarPublicacion(<?php echo $publicacion->getId();?>)">Comentar</button>
									</td>
									<td>
										<?php if ($tieneTwitter != null){?>
											<button class="btn btn-info" onclick="openModalPost(<?php echo $publicacion->getId();?>,1)">Twitter</button>
										<?php } ?>
									</td>
									<td>
										<?php if ($tieneFacebook != null){?>
											<button class="btn btn-primary" onclick="openModalPost(<?php echo $publicacion->getId();?>,2)">Facebook</button>
										<?php } ?>
									</td>
									<td>
										<?php if ($tieneLinkedin != null){?>
											<button class="btn btn-warning" onclick="openModalPost(<?php echo $publicacion->getId();?>,3)">Linkedin</button>
										<?php } ?>
										<?php
											$tieneTwitter = null;
											$tieneFacebook = null;
											$tieneLinkedin = null;
										?>
									</td>
								</tr>
							</table>
						</td>
					</tr>
				</table>
			</div>
	<?php $objUsuarioDao = null; ?>
	<?php $objComentarioDao = null; ?>
  	<?php } ?>
  	<?php echo $this->listaPublicaciones;?>
<?php } else{ ?>
			<h4>No se han encontrado publicaciones</h4>
<?php }?>

<div class="modal hide" id="myModalPost">
    <div class="modal-header">
    <button class="close" onclick="cerrarModalPost()" data-dismiss="modal">×</button>
    <h3>Compartir</h3>
    </div>
    <div class="modal-body">
    		<table>
    			<tr>
    				<td>
    					<textarea id="txtTexto" name="txtTexto">
    					</textarea>
    				</td>
    			</tr>
    		</table>
    </div>
    <div class="modal-footer">
  	    <div id="divBotonera">
  	    </div>
    </div>
</div>	

<script type="text/javascript">
	function closeModalPost()
	{		
		$('#myModalPost').modal();		
	}

	function openModalPost(id,red)
	{	
		if(red == 1){//twitter
			$boton = "<a href='#' onclick='compartirEnTwitter()' class='btn btn-success' data-dismiss='modal'>Compartir</a>";
		}
		if(red == 2){//facebook
			$boton = "<a href='#' onclick='compartirEnFacebook()' class='btn btn-success' data-dismiss='modal'>Compartir</a>";
		}
		if(red == 3){//linkedin
			$boton = "<a href='#' onclick='compartirEnLinkedin()' class='btn btn-success' data-dismiss='modal'>Compartir</a>";
		}
		$boton = $boton + "<a href='#' onclick='closeModalPost()' class='btn btn-danger'  data-dismiss='modal'>Cerrar</a>";
		
		document.getElementById("divBotonera").innerHTML = $boton;
		
		document.getElementById("txtTexto").value = document.getElementById("hdnTextoPublicacion" + id).value; 
		
		$('#myModalPost').modal('show');		
	}

	function compartirEnTwitter(){

		var texto = document.getElementById("txtTexto").value;
		
		if(texto != '') {
			//selectDestino = $('#cont_obra');
				$.ajax(
						{
						async: true,
						type: 'POST',
						url: '<?php echo $this->baseUrl()?>/integracion/publicar-twitter',
						data: 'texto=' + texto,	
						dataTypeString: 'text',
						
						beforeSend: function(data){
			                //selectDestino.html('<label>Cargando...</label>');
					    },  
					    success: function(requestData){  
					               //selectDestino.html(requestData);
							    	alert(requestData);
				               		document.getElementById("divModalGenerico").innerHTML = "Se ha compartido con éxito tu publicación en Twitter";
					    			$('#myModalGenerico').modal('show');
				               		
					    },  
					    error: function(requestData, strError, strTipoError){          
					    }
					    
						});
		}
			
	}

	function compartirEnFacebook(){

		var texto = document.getElementById("txtTexto").value;
		
		if(texto != '') {
			//selectDestino = $('#cont_obra');
				$.ajax(
						{
						async: true,
						type: 'POST',
						url: '<?php echo $this->baseUrl()?>/integracion/publicar-facebook',
						data: 'texto=' + texto,	
						dataTypeString: 'text',
						
						beforeSend: function(data){
			                //selectDestino.html('<label>Cargando...</label>');
					    },  
					    success: function(requestData){  
					               //selectDestino.html(requestData);
				               		alert(requestData);
					    			document.getElementById("divModalGenerico").innerHTML = "Se ha compartido con éxito tu publicación en Facebook";
					    			$('#myModalGenerico').modal('show');
					    },  
					    error: function(requestData, strError, strTipoError){          
					    }
					    
						});
		}
			
	}

	function compartirEnLinkedin(){

		var texto = document.getElementById("txtTexto").value;
		
		if(texto != '') {
			//selectDestino = $('#cont_obra');
				$.ajax(
						{
						async: true,
						type: 'POST',
						url: '<?php echo $this->baseUrl()?>/integracion/publicar-linkedin',
						data: 'texto=' + texto,	
						dataTypeString: 'text',
						
						beforeSend: function(data){
			                //selectDestino.html('<label>Cargando...</label>');
					    },  
					    success: function(requestData){  
					               //selectDestino.html(requestData);
				               		alert(requestData);
				               		document.getElementById("divModalGenerico").innerHTML = "Se ha compartido con éxito tu publicación en Linkedin";
					    			$('#myModalGenerico').modal('show');
				               		
					    },  
					    error: function(requestData, strError, strTipoError){          
					    }
					    
						});
		}
			
	}

	function comentarPublicacion(idPublicacion){

		//document.getElementById("divComentariosPublicacion" + idPublicacion).innerHTML = "hola";
		var texto = document.getElementById("txtComentario" + idPublicacion).value; 

		if(texto != '') {
			//selectDestino = $('#cont_obra');
				$.ajax(
						{
						async: true,
						type: 'POST',
						url: '<?php echo $this->baseUrl()?>/muro/comentar-publicacion',
						data: 'texto=' + texto + '&idPublicacion=' + idPublicacion,	
						dataTypeString: 'text',
						
						beforeSend: function(data){
			                //selectDestino.html('<label>Cargando...</label>');
					    },  
					    success: function(requestData){  
					               //selectDestino.html(requestData);
				               		result = requestData;
				               		document.getElementById("divComentariosPublicacion" + idPublicacion).innerHTML = result;
				               		document.getElementById("txtComentario" + idPublicacion).value = "";
				               		
				               		
					    },  
					    error: function(requestData, strError, strTipoError){          
					    }
					    
						});
		}
		
	}

	function verFoto(titulo,foto)
	{
		var html = ""; 
		html = html + "<div style='width: 100%;'>";
		html = html + "<a class='thumbnail'>";
		html = html + "<img src='<?php echo $this->baseUrl()?>/imagenes/fotos/"+foto+"'>";
		html = html + "</a>";
		html = html + "</div>";    
			
		document.getElementById("divModalGenerico").innerHTML = html;
		document.getElementById("divModalGenericoTitulo").innerHTML = titulo;
		
		
		$('#myModalGenerico').modal('show');
	}
</script>