<?php 
	$objUsuarioDao2 = new Application_Model_UsuarioDao();
	$objTipPublicacion = new Application_Model_TipoPublicacionDao();
?>

<br>
<table>
  <tr>
    <td><h1>MI MURO</h1></td>
    <td>
		&nbsp;&nbsp;&nbsp;&nbsp;<a href="#" class="btn btn-large" onclick="openModalPublicacion()"><img src="/imagenes/proyecto/editar.png">&nbsp;&nbsp; Pincha aquí para publicar...  </a>
    </td>
  </tr>
</table>
<br>

<?php echo $this->listaPublicaciones;?>
<?php if(count($this->listaPublicaciones) > 0){ ?>
	<?php foreach ($this->listaPublicaciones as $publicacion){?>
			<div id="publicacion<?php echo $publicacion->getId();?>" align="center" class="span9">
				<table>
					<tr>
						<td colspan="2">
							<label class="wellPublicacionTitulo">
							<a href="/muro/muro-contacto/id/<?php echo $publicacion->getUsuarioId();?>">
								<b><?php
									echo $objUsuarioDao2->obtenerPorId($publicacion->getUsuarioId())->getNombre();
								?></b>
							</a>
							</label>
						</td>
					</tr>
					<tr>
						<td rowspan="3" valign="top">
							<a class="thumbnail" href="/muro/muro-contacto/id/<?php echo $publicacion->getUsuarioId();?>">
      							<img alt="" src="<?php echo $this->baseUrl()?>/imagenes/usuarios/icono/<?php echo $objUsuarioDao2->obtenerPorId($publicacion->getUsuarioId())->getFoto();?>">
         					</a>
						</td>
						<td>
							<h5 class="cont4 well"><?php echo $publicacion->getTexto();?></h5>
							<input type="hidden" id="hdnTextoPublicacion<?php echo $publicacion->getId();?>" value="<?php echo $publicacion->getTexto();?>">
							
							
							<!-- aquí se muestra la información de la publicación según... el tipo de publicación -->
							<?php 
							$objPublicacionAux = new Application_Model_PublicacionDao();
							
							$texto = $publicacion->getTexto();
							$texto = str_replace('"',"&ldquo;",$texto);
							$texto = str_replace("'","&lsquo;",$texto);
							
							if($publicacion->getTipoId() == 1){ ?>
								<p><?php echo $objPublicacionAux->calcularTiempoTranscurrido($publicacion->getFecha());?></p>
								<a href="#" onclick="verPublicacionesConCometarios('<?php echo $publicacion->getId();?>','<?php echo $publicacion->getVideo();?>','<?php echo $publicacion->getFoto();?>','<?php echo $publicacion->getTipoId();?>','<?php echo $objUsuarioDao2->obtenerPorId($publicacion->getUsuarioId())->getNombre(); ?>')" class="btn"><i class="icon-plus"></i>&nbsp; Ver más</a>  
							<?php } ?>
								
							<?php
							if($publicacion->getTipoId() == 2){ ?>
								<div style="width: 320px; height: 100%;">
									<a class="thumbnail">
		      							<img src="<?php echo $this->baseUrl()?>/imagenes/fotos/icono/<?php echo $publicacion->getFoto();?>" onclick="verFoto('<?php echo $publicacion->getTexto();?>','<?php echo $publicacion->getFoto();?>')">
	         						</a>
         						</div><br>
         						<p><?php echo $objPublicacionAux->calcularTiempoTranscurrido($publicacion->getFecha()); ?></p>
         						<a href="#" onclick="verPublicacionesConCometarios('<?php echo $publicacion->getId();?>','<?php echo $publicacion->getVideo();?>','<?php echo $publicacion->getFoto();?>','<?php echo $publicacion->getTipoId();?>','<?php echo $objUsuarioDao2->obtenerPorId($publicacion->getUsuarioId())->getNombre(); ?>')" class="btn"><i class="icon-plus"></i>&nbsp; Ver más</a>    
							<?php } ?>
							
							<?php if($publicacion->getTipoId() == 3){ ?>
									<iframe class="youtube-player" width="320" height="190" src="http://www.youtube.com/embed/<?php echo $publicacion->getVideo();?>?wmode=transparent">
									</iframe>
									<p><?php echo $objPublicacionAux->calcularTiempoTranscurrido($publicacion->getFecha()); ?></p>
									<a href="#" onclick="verPublicacionesConCometarios('<?php echo $publicacion->getId();?>','<?php echo $publicacion->getVideo();?>','<?php echo $publicacion->getFoto();?>','<?php echo $publicacion->getTipoId();?>','<?php echo $objUsuarioDao2->obtenerPorId($publicacion->getUsuarioId())->getNombre(); ?>')" class="btn"><i class="icon-plus"></i>&nbsp; Ver más</a>      
							<?php } ?>
						</td>
					</tr>
					<tr>
						<td>
							<?php 
								$objUsuarioDao = new Application_Model_UsuarioDao();
								$objComentarioDao = new Application_Model_ComentarioDao();
								$objIntegracionDao = new Application_Model_IntegracionDao();
								
								$aut = Zend_Auth::getInstance();
								$tieneFacebook = $objIntegracionDao->obtenerLlavesIntegracion($aut->getIdentity()->usu_id, 1);
								$tieneTwitter = $objIntegracionDao->obtenerLlavesIntegracion($aut->getIdentity()->usu_id, 2);
								$tieneLinkedin = $objIntegracionDao->obtenerLlavesIntegracion($aut->getIdentity()->usu_id, 3);
								$objIntegracionDao = null;
								
								$listaComentarios = $objComentarioDao->obtenerPorPublicacionId($publicacion->getId());?>
							<div id="divComentariosPublicacion<?php echo $publicacion->getId();?>">
							<?php if(count($listaComentarios) > 0){
								    foreach ($listaComentarios as $comentario){?>
								    	<table>
								    		<tr>
								    			<td valign="top">
								    				<?php $objUsuario = $objUsuarioDao->obtenerPorId($comentario->getUsuarioId());?>
								    				<div style='width: 50px;'>
														<a class="thumbnail" href="/muro/muro-contacto/id/<?php echo $objUsuario->getId();?>">
							      							<img src="<?php echo $this->baseUrl()?>/imagenes/usuarios/icono/<?php echo $objUsuario->getFoto();?>"></a>
						         					</div>
								    			</td>
								    			<td valign="top">
								    				<p class="label"><?php echo $objUsuario->getNombre(); ?></p>
								    				<div class="cont4"><p><?php echo $comentario->getTexto();?></p></div>
								    				<p>
								    					<?php echo $objPublicacionAux->calcularTiempoTranscurrido($comentario->getFecha());?>
								    				</p>
								    			</td>
								    		</tr>
								    	</table>
							  <?php } ?>
							  comentarios: <span class="badge badge-info"><?php echo $objComentarioDao->obtenerCantidadComentariosPorPublicacionId($publicacion->getId());?></span>
						  <?php } ?>
						  <?php
						  	$objPublicacionAux = null;
						  ?>
						  </div>
						</td>
					</tr>
					<tr>
						<td>
							<table>
								<tr>
									<td>
										<div id="divLoaderComentario<?php echo $publicacion->getId();?>"></div>
										<textarea id="txtComentario<?php echo $publicacion->getId();?>" rows="1" placeholder="Escribe algo aquí..." class="span5" onkeypress="ValidarCaracteres(this, 499)"></textarea>
										<button class="btn btn-inverse" onclick="comentarPublicacion(<?php echo $publicacion->getId();?>)">Comentar</button>
									</td>
									<td>
										<?php if ($tieneTwitter != null){?>
											<a href="#"><img src="/imagenes/proyecto/twitter.png" onclick="openModalPost(<?php echo $publicacion->getId();?>,1)"></a>
										<?php } ?>
									</td>
									<td>
										<?php if ($tieneFacebook != null){?>
											<a href="#"><img src="/imagenes/proyecto/facebook.png" onclick="openModalPost(<?php echo $publicacion->getId();?>,2)"></a>
										<?php } ?>
									</td>
									<td>
										<?php if ($tieneLinkedin != null){?>
											<a href="#"><img src="/imagenes/proyecto/linkedin.png" onclick="openModalPost(<?php echo $publicacion->getId();?>,3)"></a>
										<?php } ?>
										<?php 
											$tieneTwitter = null;
											$tieneFacebook = null;
											$tieneLinkedin = null;
										?>
									</td>
								</tr>
							</table>
						</td>
					</tr>
				</table>
			</div>
	<?php $objUsuarioDao = null; ?>
	<?php $objComentarioDao = null; ?>
  	<?php } ?>
<?php } else{ ?>
			<h2>No se han encontrado publicaciones</h2>
<?php }?>

<div class="modal hide" id="myModalPost">
    <div class="modal-header">
    <button class="close" onclick="cerrarModalPost()" data-dismiss="modal">×</button>
    
    <table>
    	<tr>
    		<td>
				Compartir en     			
    		</td>
    		<td>
    			<div id="divIcoRed"></div>
    		</td>
    	</tr>
    </table>
    
    </div>
    <div class="modal-body">
    		<table>
    			<tr>
    				<td>
    					<input type="hidden" id="maximoPost" name="maximoPost">
    					<input type="hidden" id="idPost" name="idPost">
    					<textarea id="txtTexto" name="txtTexto" onKeyDown="textCounter(this, 'count_display');" class="span5">
    					</textarea>
    					<span id="count_display" style="display:none;">140 caracteres restantes</span>
    				</td>
    			</tr>
    			<tr>
    				<td align="center">
    					<div id="divLoaderCompartiendo"></div>
    				</td>
    			</tr>
    		</table>
    </div>
    <div class="modal-footer">
  	    <div id="divBotonera">
  	    </div>
    </div>
</div>

<?php 
	  $flagModal = "modal hide";
	  if($this->error == "error"){
    	$flagModal = "modal"; 
	  }else{
	      $flagModal = "modal hide";
	  }
?>

<div class="<?php echo $flagModal;?>" id="myModalPublicacion" style="width: 700px;">
    <div class="modal-header">
    <button class="close" onclick="closeModalPublicacion()" data-dismiss="modal">×</button>
	<h2><img src="/imagenes/proyecto/luz.png" width="40px;">&nbsp;&nbsp;&nbsp;Nueva Publicación</h2>
    </div>
    <div class="modal-body">
		
<form action="/muro/mi-muro/" 
	  name="<?php echo $this->formPublicacion->getName();?>"
	  id="formPublicacion"  
	  method="<?php echo $this->formPublicacion->getMethod();?>"
	  enctype="<?php echo $this->formPublicacion->getEnctype(); ?>">
	  
	<table align="center">
			<tr>
				<td></td>
				<td><?php echo $this->formPublicacion->optFoto;?></td>
				<td><?php echo $this->formPublicacion->optTexto;?></td>
				<td><?php echo $this->formPublicacion->optVideo;?></td>
			</tr>
			<tr>
				<td colspan="3"><h5>Publicación:</h5></td>
			</tr>
			<tr>
				<td colspan="4">
					<textarea rows="3" id="txtTextoPublicacion" name="txtTextoPublicacion" class="span4" onKeyDown="ValidarCaracteres(this, 999);"></textarea>
					<div id="divErrorTexto"></div>  
				</td>
			</tr>
			<tr>
				<td colspan="4">
					<div id="divFoto" style="display: block;">
							<table>
								<tr>
									<td>
										imagen: 
									</td>
									<td>
										<?php echo $this->formPublicacion->fileFoto;?>
										&nbsp;&nbsp; <b>sólo se aceptan:</b> jpg, jpeg, png, gif
										<div id="divErrorSinFoto"></div>
									</td>
								</tr>
							</table>
					</div>
				</td>
			</tr>
			
			<tr>
				<td colspan="4">
					<div id="divVideo" style="display: none;">
						<table>
							<tr>
								<td>
									ID video Youtube:
								</td>
								<td><?php echo $this->formPublicacion->txtVideo;?>
									<div id="divErrorVideo"></div>
									<input type="hidden" value="" id="hdnFlagErrorVideo" name="hdnFlagErrorVideo">
								</td>
							</tr>
						</table>
					</div>
				</td>
			</tr>
			<tr>
				<td colspan="4">
					<b>¿Quiénes podrán visualizar tu publicación ?</b>
				</td>
			</tr>
			<tr>
				<td></td>
				<td>Alumnos<?php echo $this->formPublicacion->cbxAlumno;?></td>
				<td>Profesores<?php echo $this->formPublicacion->cbxProfesor;?></td>
				<td>Funcionarios<?php echo $this->formPublicacion->cbxAcademico;?></td>
			</tr>
			<tr>
				<td colspan="4">
					<div id="divErrorPrivacidadPublicacion"></div>
				</td>
			</tr>
		</table>
</form>
		
    </div>
    <div class="modal-footer">
    	<input type="button" value="Publicar" id="btnCrearPublicacion" name="btnCrearPublicacion" onClick="validarFormPublicacion()" class="btn btn-success" style="height:30px; width: 80px;">
  	    <a href="#" onclick="closeModalPublicacion()" class="btn btn-danger" data-dismiss="modal">Cancelar</a>
    </div>
</div>	

<script type="text/javascript">

	function validarFormPublicacion()
	{

		if(document.getElementById("cbxAlumno").checked == false && document.getElementById("cbxProfesor").checked == false && document.getElementById("cbxAcademico").checked == false)
		{
			document.getElementById("divErrorPrivacidadPublicacion").innerHTML = "<ul type='square'><li><font color='red'>Debes seleccionar al menos una privacidad de publicación.... </font></ul>";
			return;
		}  
		
		//si tiene seleccionado foto
		if(document.getElementsByName("grpTipo")[0].checked == true)
		{
			if(document.getElementById("txtTextoPublicacion").value == "")
			{
				document.getElementById("divErrorTexto").innerHTML =  "<ul type='square'><li> <font color='red'>Escribe algo aquí...</font> </ul>";
				return;
			}else{
				document.getElementById("divErrorTexto").innerHTML = "";
			}

			if(document.getElementById("fileFoto").value == "")
			{
				document.getElementById("divErrorSinFoto").innerHTML =  "<ul type='square'><li><font color='red'> Tienes que subir una foto... recuerda menor a 4 MB.. </font></ul>";
				return;
			}else{
				document.getElementById("divErrorSinFoto").innerHTML = "";
			}
		}

		//si tiene seleccionado texto
		if(document.getElementsByName("grpTipo")[1].checked == true)
		{
			if(document.getElementById("txtTextoPublicacion").value == "")
			{
				document.getElementById("divErrorTexto").innerHTML =  "<ul type='square'><li><font color='red'>Escribe algo aquí...</font></ul>";
				return;
			}else{
				document.getElementById("divErrorTexto").innerHTML = "";
			}
		}

		//si tiene seleccionado video
		if(document.getElementsByName("grpTipo")[2].checked == true)
		{
			if(document.getElementById("txtTextoPublicacion").value == "")
			{
				document.getElementById("divErrorTexto").innerHTML =  "<ul type='square'><li><font color='red'>Escribe algo aquí...</font></ul>";
				return;
			}else{
				document.getElementById("divErrorTexto").innerHTML = "";
			}
			
			if(document.getElementById("txtVideo").value == "")
			{
				document.getElementById("divErrorVideo").innerHTML =  "<ul type='square'><li><font color='red'>Debes ingresar el ID de un video YouTube </font></ul>";
				return;
			}

			if(document.getElementById("hdnFlagErrorVideo").value == "error")
			{
				document.getElementById("divErrorVideo").innerHTML =  "<ul type='square'><li><font color='red'>El ID de YouTube no existe...</font></ul>";
				return;
			}else{
				document.getElementById("divErrorVideo").innerHTML = "";
				document.getElementById("hdnFlagErrorVideo").value = "";
			}
			
		}
		
		document.getElementById("formPublicacion").submit();
	}

	function textCounter(textarea, counterID) {
		
		var maxLen = document.getElementById("maximoPost").value;
		document.getElementById("count_display").style.display = "block";
		
		cnt = document.getElementById(counterID);
		if (textarea.value.length > (maxLen))
		{
			textarea.value = textarea.value.substring(0,maxLen);
		}
		cnt.innerHTML = (maxLen - textarea.value.length) + ' Caracteres Restantes';
	}

	function desabilitarFotoVideo()
	{
		document.getElementById("divFoto").style.display = "none";
		document.getElementById("divVideo").style.display = "none";
		document.getElementById("fileFoto").value = "";
		document.getElementById("txtVideo").value = "";
	}

	function desabilitarFoto()
	{
		document.getElementById("divFoto").style.display = "none";
		document.getElementById("divVideo").style.display = "block";
		document.getElementById("fileFoto").value = "";
	}

	function desabilitarVideo()
	{
		document.getElementById("divVideo").style.display = "none";
		document.getElementById("divFoto").style.display = "block";
		document.getElementById("txtVideo").value = "";
	}

	function ValidaUrlYouTube(youTubeID)
	{
		
	}

	function openModalPublicacion()
	{
		$('#myModalPublicacion').modal('show');
	}

	function closeModalPublicacion()
	{
		$('#myModalPublicacion').modal();
	}

	function closeModalPost()
	{		
		$('#myModalPost').modal();
	}

	function openModalPost(id,red)
	{	
		document.getElementById("divLoaderCompartiendo").innerHTML = "";
		
		if(red == 1){//twitter
			$boton = "<a href='#' onclick='compartirEnTwitter()' class='btn btn-success'>Compartir</a>";
			document.getElementById("divIcoRed").innerHTML = "<img src='/imagenes/proyecto/tt.png'>";
			document.getElementById("maximoPost").value = "130";
			document.getElementById("count_display").innerHTML = "140";
			document.getElementById("txtTexto").value = document.getElementById("hdnTextoPublicacion" + id).value.substring(0,139); 
		}
		if(red == 2){//facebook
			$boton = "<a href='#' onclick='compartirEnFacebook()' class='btn btn-success'>Compartir</a>";
			document.getElementById("divIcoRed").innerHTML = "<img src='/imagenes/proyecto/fb.png'>";
			document.getElementById("maximoPost").value = "500";
			document.getElementById("count_display").innerHTML = "500";
			document.getElementById("txtTexto").value = document.getElementById("hdnTextoPublicacion" + id).value.substring(0,499); 
		}
		if(red == 3){//linkedin
			$boton = "<a href='#' onclick='compartirEnLinkedin()' class='btn btn-success'>Compartir</a>";
			document.getElementById("divIcoRed").innerHTML = "<img src='/imagenes/proyecto/in.png'>";
			document.getElementById("maximoPost").value = "600";
			document.getElementById("count_display").innerHTML = "600";
			document.getElementById("txtTexto").value = document.getElementById("hdnTextoPublicacion" + id).value.substring(0,599); 
		}

		$boton = $boton + "  <a href='#'' class='btn btn-danger' data-dismiss='modal'>Cerrar</a>";		
		document.getElementById("divBotonera").innerHTML = $boton;
		
		document.getElementById("txtTexto").value = document.getElementById("hdnTextoPublicacion" + id).value; 
		document.getElementById("idPost").value = id;
		
		$('#myModalPost').modal('show');		
	}

	function compartirEnTwitter(){

		var texto = document.getElementById("txtTexto").value;

		if(texto.length > 140)
		{
			document.getElementById("divLoaderCompartiendo").innerHTML = "<p class='label label-important'>No puedes superar los 140 caracteres para compartir en twiiter !!</p>";
			return;
		}
		
		if(texto != '') {
			selectDestino = $('#divLoaderCompartiendo');
				$.ajax(
						{
						async: true,
						type: 'POST',
						url: '<?php echo $this->baseUrl()?>/integracion/publicar-twitter',
						data: 'texto=' + texto,	
						dataTypeString: 'text',
						
						beforeSend: function(data){
			                selectDestino.html('<img src="/imagenes/proyecto/ajax-loader.gif">');
					    },  
					    success: function(requestData){  
					               //selectDestino.html(requestData);
							    	//alert(requestData);
				               		document.getElementById("divModalGenerico").innerHTML = "Se ha compartido con éxito tu publicación en Twitter";
			               			document.getElementById("divLoaderCompartiendo").innerHTML = "<p class='label label-success'>Publicación compartida con éxito !!</p>";
					    			//$('#myModalGenerico').modal('show');
					    },  
					    error: function(requestData, strError, strTipoError){          
					    }
					    
						});
		}
			
	}

	function compartirEnFacebook(){

		var texto = document.getElementById("txtTexto").value;
		var id = document.getElementById("idPost").value;

		if(texto != '') {
			selectDestino = $('#divLoaderCompartiendo');
				$.ajax(
						{
						async: true,
						type: 'POST',
						url: '<?php echo $this->baseUrl()?>/integracion/publicar-facebook',
						data: 'texto=' + texto+'&id='+ id,	
						dataTypeString: 'text',
						
						beforeSend: function(data){
							  selectDestino.html('<img src="/imagenes/proyecto/ajax-loader.gif">');
					    },  
					    success: function(requestData){  
					               //selectDestino.html(requestData);
				               		//alert(requestData);
					    			document.getElementById("divModalGenerico").innerHTML = "Se ha compartido con éxito tu publicación en Facebook";
					    			document.getElementById("divLoaderCompartiendo").innerHTML = "<p class='label label-success'>Publicación compartida con éxito !!</p>";
					    			//$('#myModalGenerico').modal('show');
					    },  
					    error: function(requestData, strError, strTipoError){          
					    }
					    
						});
		}
			
	}

	function compartirEnLinkedin(){

		var texto = document.getElementById("txtTexto").value;
		
		if(texto != '') {
			selectDestino = $('#divLoaderCompartiendo');
				$.ajax(
						{
						async: true,
						type: 'POST',
						url: '<?php echo $this->baseUrl()?>/integracion/publicar-linkedin',
						data: 'texto=' + texto,	
						dataTypeString: 'text',
						
						beforeSend: function(data){
							  selectDestino.html('<img src="/imagenes/proyecto/ajax-loader.gif">');
					    },  
					    success: function(requestData){  
					               //selectDestino.html(requestData);
				               		//alert(requestData);
				               		document.getElementById("divModalGenerico").innerHTML = "Se ha compartido con éxito tu publicación en Linkedin";
				               		document.getElementById("divLoaderCompartiendo").innerHTML = "<p class='label label-success'>Publicación compartida con éxito !!</p>";
					    			//$('#myModalGenerico').modal('show');
				               		
					    },  
					    error: function(requestData, strError, strTipoError){          
					    }
					    
						});
		}
			
	}

	function comentarPublicacion(idPublicacion){
		
		//document.getElementById("divComentariosPublicacion" + idPublicacion).innerHTML = "hola";
		var texto = document.getElementById("txtComentario" + idPublicacion).value; 
		var divLoader = "divLoaderComentario" + idPublicacion;
		
		if(texto != '') {
			selectDestino = $('#' + divLoader);
				$.ajax(
						{
						async: true,
						type: 'POST',
						url: '<?php echo $this->baseUrl()?>/muro/comentar-publicacion',
						data: 'texto=' + texto + '&idPublicacion=' + idPublicacion,	
						dataTypeString: 'text',
						
						beforeSend: function(data){
			                selectDestino.html('<img src="/imagenes/proyecto/ajax-loader-bar.gif">');
					    },  
					    success: function(requestData){  
					               //selectDestino.html(requestData);
				               		result = requestData;
				               		document.getElementById("divComentariosPublicacion" + idPublicacion).innerHTML = result;
				               		document.getElementById("txtComentario" + idPublicacion).value = "";
				               		document.getElementById(divLoader).innerHTML = "";
					    },  
					    error: function(requestData, strError, strTipoError){          
					    }
					    
						});
		}
		
	}

	function verPublicacionesConCometarios(idPublicacion,video,foto,tipoPublicacion,usuarioNombre)
	{
		obtenerNombrePublicacion(idPublicacion);
		todosComentarios(idPublicacion);

		if(tipoPublicacion == 1)
		{
			var html = ""; 
		}
		
		if(tipoPublicacion == 2)
		{
			var html = ""; 
			html = html + "<div style='width: 100%;'>";
			html = html + "<a class='thumbnail'>";
			html = html + "<img src='<?php echo $this->baseUrl()?>/imagenes/fotos/"+foto+"'>";
			html = html + "</a>";
			html = html + "</div>";
		} 

		if(tipoPublicacion == 3)
		{
			html = "<iframe class='youtube-player' width='640' height='380' src='http://www.youtube.com/embed/"+video+"?wmode=transparent'></iframe>";
		}
		
		html = html + "<div class='cont wellLateralIzq'><div id='divTextoPub'></div></div>"; 
		document.getElementById("divModalGenericoTitulo").innerHTML = "<label>Publicado por: " + usuarioNombre + "</label>";
		document.getElementById("divModalGenerico").innerHTML = html;
		
		$('#myModalGenerico').modal('show');
	}



	function obtenerNombrePublicacion(idPublicacion){

		$.ajax(
				{
				async: true,
				type: 'POST',
				url: '<?php echo $this->baseUrl()?>/muro/nombre',
				data: 'id=' + idPublicacion,	
				dataTypeString: 'text',
				
				beforeSend: function(data){
			    },  
			    success: function(requestData){  
			    	document.getElementById("divTextoPub").innerHTML = requestData;
			               		
			    },  
			    error: function(requestData, strError, strTipoError){          
			    }
			    
				});
		
	}
	

	function todosComentarios(idPublicacion){

		$.ajax(
				{
				async: true,
				type: 'POST',
				url: '<?php echo $this->baseUrl()?>/muro/comentarios',
				data: 'id=' + idPublicacion,	
				dataTypeString: 'text',
				
				beforeSend: function(data){
			    },  
			    success: function(requestData){  
		               		document.getElementById("divModalGenericoCometarios").innerHTML = requestData;
			               		
			    },  
			    error: function(requestData, strError, strTipoError){          
			    }
			    
				});
		
	}

	function tooltipLapiz()
	{
		$('#tooltipLapiz').popover('show');	
	}
	
</script>
