<?php 
	$objUsuarioDao2 = new Application_Model_UsuarioDao();
	$objTipPublicacion = new Application_Model_TipoPublicacionDao();
?>
<center><h1>Mi Muro</h1></center>

<img src="/imagenes/proyecto/luz.png" width="40px;" onclick="openModalPublicacion()">

<?php echo $this->listaPublicaciones;?>
<?php if(count($this->listaPublicaciones) > 0){ ?>
	<?php foreach ($this->listaPublicaciones as $publicacion){?>
			<div id="publicacion<?php echo $publicacion->getId();?>" style="width: 100%">
				<table>
					<caption class="label label-success">Categoría:  <?php echo $objTipPublicacion->obtenerPorId($publicacion->getTipoId())->getNombre();?>  </caption>
					<tr>
						<td rowspan="3" valign="top">
							<div style='width: 100px;'>
								<a class="thumbnail" href="/muro/muro-contacto/id/<?php echo $publicacion->getUsuarioId();?>">
	      							<img alt="" src="<?php echo $this->baseUrl()?>/imagenes/usuarios/<?php echo $objUsuarioDao2->obtenerPorId($publicacion->getUsuarioId())->getFoto();?>">
         						</a>
         					</div>
						</td>
						<td>
							<h5 class="cont2"><?php echo $publicacion->getTexto();?></h5>
							<input type="hidden" id="hdnTextoPublicacion<?php echo $publicacion->getId();?>" value="<?php echo $publicacion->getTexto();?>">
							
							
								<!-- aquí se muestra la información de la publicación según... el tipo de publicación -->
							<?php 
							if($publicacion->getTipoId() == 1){ ?>
							<?php } ?>
							
							<?php
							if($publicacion->getTipoId() == 2){ ?>
								<div style='width: 200px;'>
									<a class="thumbnail">
		      							<img src="<?php echo $this->baseUrl()?>/imagenes/fotos/<?php echo $publicacion->getFoto();?>" onclick="verFoto('<?php echo $publicacion->getTexto();?>','<?php echo $publicacion->getFoto();?>')">
	         						</a>
         						</div>    
							<?php } ?>
							
							<?php if($publicacion->getTipoId() == 3){ ?>
									<iframe class="youtube-player" width="320" height="190" src="http://www.youtube.com/embed/<?php echo $publicacion->getVideo();?>">
									</iframe>
							<?php } ?>
						</td>
					</tr>
					<tr>
						<td>
							<?php 
								$objUsuarioDao = new Application_Model_UsuarioDao();
								$objComentarioDao = new Application_Model_ComentarioDao();
								$objIntegracionDao = new Application_Model_IntegracionDao();
								
								$aut = Zend_Auth::getInstance();
								$tieneFacebook = $objIntegracionDao->obtenerLlavesIntegracion($aut->getIdentity()->usu_id, 1);
								$tieneTwitter = $objIntegracionDao->obtenerLlavesIntegracion($aut->getIdentity()->usu_id, 2);
								$tieneLinkedin = $objIntegracionDao->obtenerLlavesIntegracion($aut->getIdentity()->usu_id, 3);
								$objIntegracionDao = null;
								
								$listaComentarios = $objComentarioDao->obtenerPorPublicacionId($publicacion->getId());?>
							<div id="divComentariosPublicacion<?php echo $publicacion->getId();?>">
							<?php if(count($listaComentarios) > 0){
								    foreach ($listaComentarios as $comentario){?>
								    	<table>
								    		<tr>
								    			<td valign="top">
								    				<?php $objUsuario = $objUsuarioDao->obtenerPorId($comentario->getUsuarioId());?>
								    				<div style='width: 50px;'>
														<a class="thumbnail"href="/muro/muro-contacto/id/<?php echo $objUsuario->getId();?>">
							      							<img src="<?php echo $this->baseUrl()?>/imagenes/usuarios/<?php echo $objUsuario->getFoto();?>"></a>
						         					</div>
								    			</td>
								    			<td valign="top">
								    				<p class="label"><?php echo $objUsuario->getNombre(); ?></p>
								    				<div class="cont"><p><?php echo $comentario->getTexto();?></p></div>
								    				<p><?php echo $comentario->getFecha();?></p>
								    			</td>
								    		</tr>
								    	</table>
							  <?php } ?>
							  comentarios: <span class="badge badge-info"><?php echo $objComentarioDao->obtenerCantidadComentariosPorPublicacionId($publicacion->getId());?></span>
						  <?php } ?>
						  </div>
						</td>
					</tr>
					<tr>
						<td>
							<table>
								<tr>
									<td>
										<div id="divLoaderComentario<?php echo $publicacion->getId();?>"></div>
										<textarea id="txtComentario<?php echo $publicacion->getId();?>" rows="1" placeholder="Escribe algo aquí..." class="span5"></textarea>
										<button class="btn btn-inverse" onclick="comentarPublicacion(<?php echo $publicacion->getId();?>)">Comentar</button>
									</td>
									<td>
										<?php if ($tieneTwitter != null){?>
											<button class="btn btn-info" onclick="openModalPost(<?php echo $publicacion->getId();?>,1)">Twitter</button>
										<?php } ?>
									</td>
									<td>
										<?php if ($tieneFacebook != null){?>
											<button class="btn btn-primary" onclick="openModalPost(<?php echo $publicacion->getId();?>,2)">Facebook</button>
										<?php } ?>
									</td>
									<td>
										<?php if ($tieneLinkedin != null){?>
											<button class="btn btn-warning" onclick="openModalPost(<?php echo $publicacion->getId();?>,3)">Linkedin</button>
										<?php } ?>
										<?php
											$tieneTwitter = null;
											$tieneFacebook = null;
											$tieneLinkedin = null;
										?>
									</td>
								</tr>
							</table>
						</td>
					</tr>
				</table>
			</div>
	<?php $objUsuarioDao = null; ?>
	<?php $objComentarioDao = null; ?>
  	<?php } ?>
<?php } else{ ?>
			<h4>No se han encontrado publicaciones</h4>
<?php }?>

<div class="modal hide" id="myModalPost">
    <div class="modal-header">
    <button class="close" onclick="cerrarModalPost()" data-dismiss="modal">×</button>
    
    <table>
    	<tr>
    		<td>
				Compartir en     			
    		</td>
    		<td>
    			<div id="divIcoRed"></div>
    		</td>
    	</tr>
    </table>
    
    </div>
    <div class="modal-body">
    		<table>
    			<tr>
    				<td>
    					<input type="hidden" id="maximoPost" name="maximoPost">
    					<textarea id="txtTexto" name="txtTexto" onKeyDown="textCounter(this, 'count_display');">
    					</textarea>
    					<span id="count_display" style="display:none;">140 caracteres restantes</span>
    				</td>
    			</tr>
    			<tr>
    				<td align="center">
    					<div id="divLoaderCompartiendo"></div>
    				</td>
    			</tr>
    		</table>
    </div>
    <div class="modal-footer">
  	    <div id="divBotonera">
  	    </div>
  	    
    </div>
</div>

<?php 
	  $flagModal = "modal hide";
	  if($this->error == "error"){
    	$flagModal = "modal"; 
	  }else{
	      $flagModal = "modal hide";
	  }
?>

<div class="<?php echo $flagModal;?>" id="myModalPublicacion" style="width: 700px;">
    <div class="modal-header">
    <button class="close" onclick="closeModalPublicacion()" data-dismiss="modal">×</button>
			Nueva Publicacion !!    
    </div>
    <div class="modal-body">
		
<form action="<?php echo $this->formPublicacion->getAction();?>" 
	  name="<?php echo $this->formPublicacion->getName();?>" 
	  method="<?php echo $this->formPublicacion->getMethod();?>"
	  enctype="<?php echo $this->formPublicacion->getEnctype(); ?>">
	  
	  
	  <?php echo $this->xxx;?>
	  
	<table>
			<tr>
				<td></td>
				<td><?php echo $this->formPublicacion->optTexto;?></td>
				<td><?php echo $this->formPublicacion->optFoto;?></td>
				<td><?php echo $this->formPublicacion->optVideo;?></td>
			</tr>
			<tr>
				<td colspan="4"><h5>Publicación</h5></td>
			</tr>
			<tr>
				<td></td>
				<td colspan="4"><?php echo $this->formPublicacion->txtTexto;?></td>
			</tr>
			<tr>
				<td colspan="4">
					<div id="divFoto" style="display: none;">
						<table>
							<tr>
								<td>Imagen:</td>
								<td><?php echo $this->formPublicacion->fileFoto;?></td>
							</tr>
						</table>
					</div>
				</td>
			</tr>
			<tr>
				<td colspan="4">
					<div id="divVideo" style="display: none;">
						<table>
							<tr>
								<td>
									Url Youtube:
								</td>
								<td><?php echo $this->formPublicacion->txtVideo;?>
									<div id="divErrorVideo"></div>
								</td>
							</tr>
						</table>
					</div>
				</td>
			</tr>
			<tr>
				<td colspan="4">
					<b>Quienes podrán visualizar tu publicación ?</b>
				</td>
			</tr>
			<tr>
				<td></td>
				<td>Alumnos<?php echo $this->formPublicacion->cbxAlumno;?></td>
				<td>Profesor<?php echo $this->formPublicacion->cbxProfesor;?></td>
				<td>Academico<?php echo $this->formPublicacion->cbxAcademico;?></td>
			</tr>
			<tr>
				<td colspan="3"><?php echo $this->formPublicacion->btnCrearPublicacion;?></td>
			</tr>
		</table>
</form>
		
    </div>
    <div class="modal-footer">
  	    <a href="#" onclick="closeModalPublicacion()" class="btn btn-danger" data-dismiss="modal">Cancelar</a>
    </div>
</div>	

<script type="text/javascript">

	function textCounter(textarea, counterID) {
		
		var maxLen = document.getElementById("maximoPost").value;
		document.getElementById("count_display").style.display = "block";
		
		cnt = document.getElementById(counterID);
		if (textarea.value.length > (maxLen))
		{
			textarea.value = textarea.value.substring(0,maxLen);
		}
		cnt.innerHTML = (maxLen - textarea.value.length) + ' Caracteres Restantes';
	}

	function desabilitarFotoVideo()
	{
		document.getElementById("divFoto").style.display = "none";
		document.getElementById("divVideo").style.display = "none";
	}

	function desabilitarFoto()
	{
		document.getElementById("divFoto").style.display = "none";
		document.getElementById("divVideo").style.display = "block";
	}

	function desabilitarVideo()
	{
		document.getElementById("divVideo").style.display = "none";
		document.getElementById("divFoto").style.display = "block";
	}

	function ValidaUrlYouTube(youTubeID)
	{
		if(youTubeID != '') {
				$.ajax(
						{
						async: true,
						type: 'POST',
						url: '<?php echo $this->baseUrl()?>/muro/valida-youtube',
						data: 'youtube=' + youTubeID,	
						dataTypeString: 'text',
						
						beforeSend: function(data){
			                //selectDestino.html('<label>Cargando...</label>');
					    },  
					    success: function(requestData){  
					               //selectDestino.html(requestData);
				               		var result = requestData;
							    	if(result == "error")
							    	{
								    	document.getElementById("divErrorVideo").innerHTML =  "<b class='label label-important'>El ID de Youtube no existe :( </b>";
									    	
							    	}else{
							    		document.getElementById("divErrorVideo").innerHTML = "";
							    	}
					    },  
					    error: function(requestData, strError, strTipoError){          
					    }
					    
						});
		}
		
	}

	function openModalPublicacion()
	{
		$('#myModalPublicacion').modal('show');
	}

	function closeModalPublicacion()
	{
		$('#myModalPublicacion').modal();
	}

	function closeModalPost()
	{		
		$('#myModalPost').modal();
	}

	function openModalPost(id,red)
	{	
		if(red == 1){//twitter
			$boton = "<a href='#' onclick='compartirEnTwitter()' class='btn btn-success'>Compartir</a>";
			document.getElementById("divIcoRed").innerHTML = "<img src='/imagenes/proyecto/tt.png'>";
			document.getElementById("maximoPost").value = "130";
			document.getElementById("count_display").innerHTML = "140";
		}
		if(red == 2){//facebook
			$boton = "<a href='#' onclick='compartirEnFacebook()' class='btn btn-success'>Compartir</a>";
			document.getElementById("divIcoRed").innerHTML = "<img src='/imagenes/proyecto/fb.png'>";
			document.getElementById("maximoPost").value = "500";
			document.getElementById("count_display").innerHTML = "500";
		}
		if(red == 3){//linkedin
			$boton = "<a href='#' onclick='compartirEnLinkedin()' class='btn btn-success'>Compartir</a>";
			document.getElementById("divIcoRed").innerHTML = "<img src='/imagenes/proyecto/in.png'>";
			document.getElementById("maximoPost").value = "600";
			document.getElementById("count_display").innerHTML = "600";
		}

		$boton = $boton + "  <a href='#'' class='btn btn-danger' data-dismiss='modal'>Cerrar</a>";		
		document.getElementById("divBotonera").innerHTML = $boton;
		
		document.getElementById("txtTexto").value = document.getElementById("hdnTextoPublicacion" + id).value; 
		
		$('#myModalPost').modal('show');		
	}

	function compartirEnTwitter(){

		var texto = document.getElementById("txtTexto").value;

		if(texto.length > 140)
		{
			document.getElementById("divLoaderCompartiendo").innerHTML = "<p class='label label-important'>No puedes superar los 140 caracteres para compartir en twiiter !!</p>";
			return;
		}
		
		if(texto != '') {
			selectDestino = $('#divLoaderCompartiendo');
				$.ajax(
						{
						async: true,
						type: 'POST',
						url: '<?php echo $this->baseUrl()?>/integracion/publicar-twitter',
						data: 'texto=' + texto,	
						dataTypeString: 'text',
						
						beforeSend: function(data){
			                selectDestino.html('<img src="/imagenes/proyecto/ajax-loader.gif">');
					    },  
					    success: function(requestData){  
					               //selectDestino.html(requestData);
							    	//alert(requestData);
				               		document.getElementById("divModalGenerico").innerHTML = "Se ha compartido con éxito tu publicación en Twitter";
			               			document.getElementById("divLoaderCompartiendo").innerHTML = "<p class='label label-success'>Publicación compartida con éxito !!</p>";
					    			//$('#myModalGenerico').modal('show');
					    },  
					    error: function(requestData, strError, strTipoError){          
					    }
					    
						});
		}
			
	}

	function compartirEnFacebook(){

		var texto = document.getElementById("txtTexto").value;

		/*
		if(texto.length > 501)
		{
			document.getElementById("divLoaderCompartiendo").innerHTML = "<p class='label label-important'>No puedes superar los 500 caracteres para compartir en Facebook !!</p>";
			return;
		}*/
		
		if(texto != '') {
			selectDestino = $('#divLoaderCompartiendo');
				$.ajax(
						{
						async: true,
						type: 'POST',
						url: '<?php echo $this->baseUrl()?>/integracion/publicar-facebook',
						data: 'texto=' + texto,	
						dataTypeString: 'text',
						
						beforeSend: function(data){
							  selectDestino.html('<img src="/imagenes/proyecto/ajax-loader.gif">');
					    },  
					    success: function(requestData){  
					               //selectDestino.html(requestData);
				               		//alert(requestData);
					    			document.getElementById("divModalGenerico").innerHTML = "Se ha compartido con éxito tu publicación en Facebook";
					    			document.getElementById("divLoaderCompartiendo").innerHTML = "<p class='label label-success'>Publicación compartida con éxito !!</p>";
					    			//$('#myModalGenerico').modal('show');
					    },  
					    error: function(requestData, strError, strTipoError){          
					    }
					    
						});
		}
			
	}

	function compartirEnLinkedin(){

		var texto = document.getElementById("txtTexto").value;
		
		if(texto != '') {
			selectDestino = $('#divLoaderCompartiendo');
				$.ajax(
						{
						async: true,
						type: 'POST',
						url: '<?php echo $this->baseUrl()?>/integracion/publicar-linkedin',
						data: 'texto=' + texto,	
						dataTypeString: 'text',
						
						beforeSend: function(data){
							  selectDestino.html('<img src="/imagenes/proyecto/ajax-loader.gif">');
					    },  
					    success: function(requestData){  
					               //selectDestino.html(requestData);
				               		//alert(requestData);
				               		document.getElementById("divModalGenerico").innerHTML = "Se ha compartido con éxito tu publicación en Linkedin";
				               		document.getElementById("divLoaderCompartiendo").innerHTML = "<p class='label label-success'>Publicación compartida con éxito !!</p>";
					    			//$('#myModalGenerico').modal('show');
				               		
					    },  
					    error: function(requestData, strError, strTipoError){          
					    }
					    
						});
		}
			
	}

	function comentarPublicacion(idPublicacion){
		
		//document.getElementById("divComentariosPublicacion" + idPublicacion).innerHTML = "hola";
		var texto = document.getElementById("txtComentario" + idPublicacion).value; 
		var divLoader = "divLoaderComentario" + idPublicacion;
		
		if(texto != '') {
			selectDestino = $('#' + divLoader);
				$.ajax(
						{
						async: true,
						type: 'POST',
						url: '<?php echo $this->baseUrl()?>/muro/comentar-publicacion',
						data: 'texto=' + texto + '&idPublicacion=' + idPublicacion,	
						dataTypeString: 'text',
						
						beforeSend: function(data){
			                selectDestino.html('<img src="/imagenes/proyecto/ajax-loader-bar.gif">');
					    },  
					    success: function(requestData){  
					               //selectDestino.html(requestData);
				               		result = requestData;
				               		document.getElementById("divComentariosPublicacion" + idPublicacion).innerHTML = result;
				               		document.getElementById("txtComentario" + idPublicacion).value = "";
				               		document.getElementById(divLoader).innerHTML = "";
					    },  
					    error: function(requestData, strError, strTipoError){          
					    }
					    
						});
		}
		
	}

	function verFoto(titulo,foto)
	{
		var html = ""; 
		html = html + "<div style='width: 100%;'>";
		html = html + "<a class='thumbnail'>";
		html = html + "<img src='<?php echo $this->baseUrl()?>/imagenes/fotos/"+foto+"'>";
		html = html + "</a>";
		html = html + "</div>";    
			
		document.getElementById("divModalGenerico").innerHTML = html;
		document.getElementById("divModalGenericoTitulo").innerHTML = titulo;
		
		
		$('#myModalGenerico').modal('show');
	}
</script>