<?php 
	$objUsuarioDao2 = new Application_Model_UsuarioDao();
	$objTipPublicacion = new Application_Model_TipoPublicacionDao();
?>
<br><h1> NOTICIAS </h1><br>
 
<?php echo $this->listaPublicaciones;?>
<?php if(count($this->listaPublicaciones) > 0){ ?>
	<?php foreach ($this->listaPublicaciones as $publicacion){?>
			<div id="publicacion<?php echo $publicacion->getId();?>" align="center" class="span9">
				<table class="span9">
					<tr>
						<td colspan="2">
							<label class="wellPublicacionTitulo">
							<a href="/muro/muro-contacto/id/<?php echo $publicacion->getUsuarioId();?>">
								<b><?php
									echo $objUsuarioDao2->obtenerPorId($publicacion->getUsuarioId())->getNombre();
								?></b>
							</a>
							</label>
						</td>
					</tr>
					<tr>
						<td rowspan="3" valign="top">
							<div style='width: 100px;'>
										<a class="thumbnail" href="/muro/muro-contacto/id/<?php echo $publicacion->getUsuarioId();?>">
	      								<img alt="" src="<?php echo $this->baseUrl()?>/imagenes/usuarios/icono/<?php echo $objUsuarioDao2->obtenerPorId($publicacion->getUsuarioId())->getFoto();?>">
         						</a>
         					</div>
						</td>
						<td>
							<!-- aquí se muestra la información de la publicación según... el tipo de publicación -->
							<?php 
							$objPublicacionAux = new Application_Model_PublicacionDao();
							
							$texto = $publicacion->getTexto();
							$texto = str_replace('"',"&ldquo;",$texto);
							$texto = str_replace("'","&lsquo;",$texto);
							
							if($publicacion->getTipoId() == 4){ ?>
								<?php $fechaPublicacion = strtotime($publicacion->getFecha()); ?>
								
								<h5 class="cont4 well">
								
								<?php
									$objPublicacionEventoAuxDao = new Application_Model_PublicacionEventoDao();
								?>
								
								<a href="/evento/contactos/id/<?php echo $objPublicacionEventoAuxDao->obtenerPorPublicacionId($publicacion->getId())->getEventoId();?>"><?php echo $publicacion->getTexto();?></a>
								<?php $objPublicacionEventoAuxDao = null; ?>
								
								</h5>
								<input type="hidden" id="hdnTextoPublicacion<?php echo $publicacion->getId();?>" value="<?php echo $texto;?>">
							
								<table class="span2" border="2">
									<tr>
										<td align="center" bgcolor="#DF7401">
											<?php
												switch (date("m", $fechaPublicacion))
												{
													case 1:
													    echo "Ene";
													break;
													case 2:
														echo "Feb";
														break;
													case 3:
														echo "Mar";
														break;
													case 4:
														echo "Abr";
														break;
													case 5:
														echo "May";
														break;
													case 6:
														echo "Jun";
														break;
													case 7:
														echo "Jul";
														break;
													case 8:
														echo "Ago";
														break;
													case 9:
														echo "Sep";
														break;
													case 10:
														echo "Oct";
														break;
													case 11:
														echo "Nov";
														break;
													case 12:
														echo "Dic";
														break;
												}
												echo " - ";
												echo date("Y", $fechaPublicacion);
											?>
										</td>
									 </tr>
									 <tr>
									 	<td align="center">
									 		<h2><?php 
									 				echo date("d", $fechaPublicacion); 
									 		?></h2>
									 	</td>
									 </tr>
								</table>
								<p><?php echo $objPublicacionAux->calcularTiempoTranscurrido($publicacion->getFecha());?></p>
							<?php } ?>
							<?php
							if($publicacion->getTipoId() == 5){ ?>
							<?php
								$aut = Zend_Auth::getInstance();
								$objPublicacionGrupoDao = new Application_Model_PublicacionGrupoDao();
								$objUsuarioGrupoDao = new Application_Model_UsuarioGrupoDao();
								$objGrupoDao = new Application_Model_GrupoDao();
									
								$gru_id = $objPublicacionGrupoDao->obtenerPorPublicacionId($publicacion->getId())->getGrupoId();
								$objGrupo = $objGrupoDao->obtenerPorId($gru_id);
							?>
								<h5 class="cont4 well">
								<a href="/muro/muro-grupo/id/<?php echo $objGrupo->getId();?>"><?php echo $publicacion->getTexto();?></a>
								</h5>
								<input type="hidden" id="hdnTextoPublicacion<?php echo $publicacion->getId();?>" value="<?php echo $texto;?>">
							
								<div style="width: 320px; height: 100%;">
									<a class="thumbnail">
											<img src="/imagenes/grupos/<?php echo $publicacion->getFoto();?>">
											<br>
											<?php if($objUsuarioGrupoDao->obtenerPorGrupoYUsuario($gru_id, $aut->getIdentity()->usu_id) == null){?>
												<button id="btnUnirse<?php echo $publicacion->getId();?>" href="#" onclick="openMyModalUnirseGrupo(<?php echo $publicacion->getId();?>,'<?php echo $objGrupo->getNombre();?>');" class="btn btn-success">Unete</button>
											<?php } 
											$objPublicacionGrupoDao = null;
											$objUsuarioGrupoDao = null;
											$objGrupoDao = null;
											?>
	         						</a>
         						</div>
								
								<p><?php echo $objPublicacionAux->calcularTiempoTranscurrido($publicacion->getFecha());?></p>
							<?php } ?>
						</td>
					</tr>
					<tr>
						<td>
							<?php 
								$objUsuarioDao = new Application_Model_UsuarioDao();
								$objComentarioDao = new Application_Model_ComentarioDao();
								$objIntegracionDao = new Application_Model_IntegracionDao();
								
								$aut = Zend_Auth::getInstance();
								$tieneFacebook = $objIntegracionDao->obtenerLlavesIntegracion($aut->getIdentity()->usu_id, 1);
								$tieneTwitter = $objIntegracionDao->obtenerLlavesIntegracion($aut->getIdentity()->usu_id, 2);
								$tieneLinkedin = $objIntegracionDao->obtenerLlavesIntegracion($aut->getIdentity()->usu_id, 3);
								$objIntegracionDao = null;
								
								$listaComentarios = $objComentarioDao->obtenerPorPublicacionId($publicacion->getId());?>
							<div id="divComentariosPublicacion<?php echo $publicacion->getId();?>">
							<?php if(count($listaComentarios) > 0){
								    foreach ($listaComentarios as $comentario){?>
								    	<table>
								    		<tr>
								    			<td valign="top">
								    				<?php $objUsuario = $objUsuarioDao->obtenerPorId($comentario->getUsuarioId());?>
								    				<div style='width: 50px;'>
														<a class="thumbnail" href="/muro/muro-contacto/id/<?php echo $objUsuario->getId();?>">
							      							<img src="<?php echo $this->baseUrl()?>/imagenes/usuarios/icono/<?php echo $objUsuario->getFoto();?>"></a>
						         					</div>
								    			</td>
								    			<td valign="top">
								    				<p class="label"><?php echo $objUsuario->getNombre(); ?></p>
								    				<div class="cont4"><p><?php echo $comentario->getTexto();?></p></div>
								    				<p>
								    				<?php echo $objPublicacionAux->calcularTiempoTranscurrido($comentario->getFecha());?>
								    				</p>
								    			</td>
								    		</tr>
								    	</table>
							  <?php } ?>
							  comentarios: <span class="badge badge-info"><?php echo $objComentarioDao->obtenerCantidadComentariosPorPublicacionId($publicacion->getId());?></span>
						  <?php } ?>
						  <?php
						  	$objPublicacionAux = null;
						  ?>
						  </div>
						</td>
					</tr>
					<tr>
						<td>
							<table>
								<tr>
									<td>
										<div id="divLoaderComentario<?php echo $publicacion->getId();?>"></div>
										<textarea id="txtComentario<?php echo $publicacion->getId();?>" rows="1" placeholder="Escribe algo aquí..." class="span5" onkeypress="ValidarCaracteres(this, 499)"></textarea>
										<button class="btn btn-inverse" onclick="comentarPublicacion(<?php echo $publicacion->getId();?>)">Comentar</button>
									</td>
									<td>
										<?php if ($tieneTwitter != null){?>
											<a href="#"><img src="/imagenes/proyecto/twitter.png" onclick="openModalPost(<?php echo $publicacion->getId();?>,1)"></a>
										<?php } ?>
									</td>
									<td>
										<?php if ($tieneFacebook != null){?>
											<a href="#"><img src="/imagenes/proyecto/facebook.png" onclick="openModalPost(<?php echo $publicacion->getId();?>,2)"></a>
										<?php } ?>
									</td>
									<td>
										<?php if ($tieneLinkedin != null){?>
											<a href="#"><img src="/imagenes/proyecto/linkedin.png" onclick="openModalPost(<?php echo $publicacion->getId();?>,3)"></a>
										<?php } ?>
										<?php
											$tieneTwitter = null;
											$tieneFacebook = null;
											$tieneLinkedin = null;
										?>
									</td>
								</tr>
							</table>
						</td>
					</tr>
				</table>
			</div>
	<?php $objUsuarioDao = null; ?>
	<?php $objComentarioDao = null; ?>
  	<?php } ?>
  	
<?php } else{ ?>
			<h2>No se han encontrado noticias</h2>
<?php }?>

<div class="modal hide" id="myModalPost">
    <div class="modal-header">
    <button class="close" onclick="cerrarModalPost()" data-dismiss="modal">×</button>
    
    <table>
    	<tr>
    		<td>
				Compartir en     			
    		</td>
    		<td>
    			<div id="divIcoRed"></div>
    		</td>
    	</tr>
    </table>
    
    </div>
    <div class="modal-body">
    		<table>
    			<tr>
    				<td>
    					<input type="hidden" id="maximoPost" name="maximoPost">
    					<textarea id="txtTexto" name="txtTexto" onKeyDown="textCounter(this, 'count_display');" class="span5">
    					</textarea>
    					<span id="count_display" style="display:none;">140 caracteres restantes</span>
    				</td>
    			</tr>
    			<tr>
    				<td align="center">
    					<div id="divLoaderCompartiendo"></div>
    				</td>
    			</tr>
    		</table>
    </div>
    <div class="modal-footer">
  	    <div id="divBotonera">
  	    </div>
    </div>
</div>

<div class="modal hide" id="myModalUnirseGrupo" style="width: 700px;">
    <div class="modal-header">
    <button class="close" data-dismiss="modal">×</button>
    <img src="/imagenes/proyecto/Info.png">&nbsp;<b>Unirse al Grupo</b>
    </div>
    <div class="modal-body">
	
	    <div id="divUnirseGrupo"></div>
	    <input type="hidden" id="hdnIdPublicacion">
	    <input type="hidden" id="hdnNombrePublicacion">
	    
    </div>
    <div class="modal-footer">
  	    <a href="#" onclick="unirseAlGrupo()" class="btn btn-success" data-dismiss="modal">Unirse</a>
  	    <a href="#" class="btn btn-danger" data-dismiss="modal">Cancelar</a>
    </div>
</div>	

<script type="text/javascript">

	function openMyModalUnirseGrupo(id, nombre)
	{
		document.getElementById("hdnNombrePublicacion").innerHTML = nombre;
		document.getElementById("divUnirseGrupo").innerHTML = "¿Estás seguro de unirte al grupo <b>" + nombre +"</b> ?";
		document.getElementById("hdnIdPublicacion").value = id;
		$('#myModalUnirseGrupo').modal('show');		
	}	

	function unirseAlGrupo(){

		var idPublicacion = document.getElementById("hdnIdPublicacion").value;
		
				$.ajax(
						{
						async: true,
						type: 'POST',
						url: '<?php echo $this->baseUrl()?>/grupo/unirse',
						data: 'idPublicacion=' + idPublicacion,	
						dataTypeString: 'text',
						
						beforeSend: function(data){
			                //selectDestino.html('<img src="/imagenes/proyecto/ajax-loader.gif">');
					    },  
					    success: function(requestData){  
							    	document.getElementById("btnUnirse"+idPublicacion).style.display = "none";
							    	
					    },  
					    error: function(requestData, strError, strTipoError){          
					    }
					    
						});
			
	}

	function openModalPost(id,red)
	{	
		if(red == 1){//twitter
			$boton = "<a href='#' onclick='compartirEnTwitter()' class='btn btn-success'>Compartir</a>";
			document.getElementById("divIcoRed").innerHTML = "<img src='/imagenes/proyecto/tt.png'>";
			document.getElementById("maximoPost").value = "130";
			document.getElementById("count_display").innerHTML = "140";
			document.getElementById("txtTexto").value = document.getElementById("hdnTextoPublicacion" + id).value.substring(0,139); 
		}
		if(red == 2){//facebook
			$boton = "<a href='#' onclick='compartirEnFacebook()' class='btn btn-success'>Compartir</a>";
			document.getElementById("divIcoRed").innerHTML = "<img src='/imagenes/proyecto/fb.png'>";
			document.getElementById("maximoPost").value = "500";
			document.getElementById("count_display").innerHTML = "500";
			document.getElementById("txtTexto").value = document.getElementById("hdnTextoPublicacion" + id).value.substring(0,499); 
		}
		if(red == 3){//linkedin
			$boton = "<a href='#' onclick='compartirEnLinkedin()' class='btn btn-success'>Compartir</a>";
			document.getElementById("divIcoRed").innerHTML = "<img src='/imagenes/proyecto/in.png'>";
			document.getElementById("maximoPost").value = "600";
			document.getElementById("count_display").innerHTML = "600";
			document.getElementById("txtTexto").value = document.getElementById("hdnTextoPublicacion" + id).value.substring(0,599); 
		}
	
		$boton = $boton + "  <a href='#'' class='btn btn-danger' data-dismiss='modal'>Cerrar</a>";		
		document.getElementById("divBotonera").innerHTML = $boton;
		
		document.getElementById("txtTexto").value = document.getElementById("hdnTextoPublicacion" + id).value; 
		
		$('#myModalPost').modal('show');		
	}
	
	function textCounter(textarea, counterID) {
		
		var maxLen = document.getElementById("maximoPost").value;
		document.getElementById("count_display").style.display = "block";
		
		cnt = document.getElementById(counterID);
		if (textarea.value.length > (maxLen))
		{
			textarea.value = textarea.value.substring(0,maxLen);
		}
		cnt.innerHTML = (maxLen - textarea.value.length) + ' Caracteres Restantes';
	}

	function closeModalPost()
	{		
		$('#myModalPost').modal();		
	}

	function textCounter(textarea, counterID) {
		
		var maxLen = document.getElementById("maximoPost").value;
		document.getElementById("count_display").style.display = "block";
		
		cnt = document.getElementById(counterID);
		if (textarea.value.length > (maxLen))
		{
			textarea.value = textarea.value.substring(0,maxLen);
		}
		cnt.innerHTML = (maxLen - textarea.value.length) + ' Caracteres Restantes';
	}

	function compartirEnTwitter(){

		var texto = document.getElementById("txtTexto").value;

		if(texto.length > 140)
		{
			document.getElementById("divLoaderCompartiendo").innerHTML = "<p class='label label-important'>No puedes superar los 140 caracteres para compartir en twiiter !!</p>";
			return;
		}
		
		if(texto != '') {
			selectDestino = $('#divLoaderCompartiendo');
				$.ajax(
						{
						async: true,
						type: 'POST',
						url: '<?php echo $this->baseUrl()?>/integracion/publicar-twitter',
						data: 'texto=' + texto,	
						dataTypeString: 'text',
						
						beforeSend: function(data){
			                selectDestino.html('<img src="/imagenes/proyecto/ajax-loader.gif">');
					    },  
					    success: function(requestData){  
					               //selectDestino.html(requestData);
							    	//alert(requestData);
				               		document.getElementById("divModalGenerico").innerHTML = "Se ha compartido con éxito tu publicación en Twitter";
			               			document.getElementById("divLoaderCompartiendo").innerHTML = "<p class='label label-success'>Publicación compartida con éxito !!</p>";
					    			//$('#myModalGenerico').modal('show');
					    },  
					    error: function(requestData, strError, strTipoError){          
					    }
					    
						});
		}
			
	}

	function compartirEnFacebook(){

		var texto = document.getElementById("txtTexto").value;

		if(texto != '') {
			selectDestino = $('#divLoaderCompartiendo');
				$.ajax(
						{
						async: true,
						type: 'POST',
						url: '<?php echo $this->baseUrl()?>/integracion/publicar-facebook',
						data: 'texto=' + texto,	
						dataTypeString: 'text',
						
						beforeSend: function(data){
							  selectDestino.html('<img src="/imagenes/proyecto/ajax-loader.gif">');
					    },  
					    success: function(requestData){  
					               //selectDestino.html(requestData);
				               		//alert(requestData);
					    			document.getElementById("divModalGenerico").innerHTML = "Se ha compartido con éxito tu publicación en Facebook";
					    			document.getElementById("divLoaderCompartiendo").innerHTML = "<p class='label label-success'>Publicación compartida con éxito !!</p>";
					    			//$('#myModalGenerico').modal('show');
					    },  
					    error: function(requestData, strError, strTipoError){          
					    }
					    
						});
		}
			
	}

	function compartirEnLinkedin(){

		var texto = document.getElementById("txtTexto").value;
		
		if(texto != '') {
			selectDestino = $('#divLoaderCompartiendo');
				$.ajax(
						{
						async: true,
						type: 'POST',
						url: '<?php echo $this->baseUrl()?>/integracion/publicar-linkedin',
						data: 'texto=' + texto,	
						dataTypeString: 'text',
						
						beforeSend: function(data){
							  selectDestino.html('<img src="/imagenes/proyecto/ajax-loader.gif">');
					    },  
					    success: function(requestData){  
					               //selectDestino.html(requestData);
				               		//alert(requestData);
				               		document.getElementById("divModalGenerico").innerHTML = "Se ha compartido con éxito tu publicación en Linkedin";
				               		document.getElementById("divLoaderCompartiendo").innerHTML = "<p class='label label-success'>Publicación compartida con éxito !!</p>";
					    			//$('#myModalGenerico').modal('show');
				               		
					    },  
					    error: function(requestData, strError, strTipoError){          
					    }
					    
						});
		}
			
	}

	function comentarPublicacion(idPublicacion){
		
		//document.getElementById("divComentariosPublicacion" + idPublicacion).innerHTML = "hola";
		var texto = document.getElementById("txtComentario" + idPublicacion).value; 
		var divLoader = "divLoaderComentario" + idPublicacion;
		
		if(texto != '') {
			selectDestino = $('#' + divLoader);
				$.ajax(
						{
						async: true,
						type: 'POST',
						url: '<?php echo $this->baseUrl()?>/muro/comentar-publicacion',
						data: 'texto=' + texto + '&idPublicacion=' + idPublicacion,	
						dataTypeString: 'text',
						
						beforeSend: function(data){
			                selectDestino.html('<img src="/imagenes/proyecto/ajax-loader-bar.gif">');
					    },  
					    success: function(requestData){  
					               //selectDestino.html(requestData);
				               		result = requestData;

					               	document.getElementById("divComentariosPublicacion" + idPublicacion).innerHTML = result;
				               		document.getElementById("txtComentario" + idPublicacion).value = "";
					               	document.getElementById(divLoader).innerHTML = "";
					    },  
					    error: function(requestData, strError, strTipoError){          
					    }
					    
						});
		}
		
	}

	function verFoto(titulo,foto)
	{
		var html = ""; 
		html = html + "<div style='width: 100%;'>";
		html = html + "<a class='thumbnail'>";
		html = html + "<img src='<?php echo $this->baseUrl()?>/imagenes/fotos/"+foto+"'>";
		html = html + "</a>";
		html = html + "</div>";    
			
		document.getElementById("divModalGenerico").innerHTML = html;
		document.getElementById("divModalGenericoTitulo").innerHTML = titulo;
		
		
		$('#myModalGenerico').modal('show');
	}


	function setPaginator(paginator){

		if(paginator != '') {
			//selectDestino = $('#' + divLoader);
				$.ajax(
						{
						async: true,
						type: 'POST',
						url: '<?php echo $this->baseUrl()?>/muro/set-paginator',
						data: 'paginator=' + paginator,	
						dataTypeString: 'text',
						
						beforeSend: function(data){
			                //selectDestino.html('<img src="/imagenes/proyecto/ajax-loader-bar.gif">');
					    },  
					    success: function(requestData){  
					               //selectDestino.html(requestData);
				               		alert(requestData);
					    },  
					    error: function(requestData, strError, strTipoError){          
					    }
					    
						});
		}
		
	}
</script>
